"""Unique facts M-174 through M-256: complex numbers and Calculus I."""

from __future__ import annotations


def facts() -> dict[int, dict]:
    F: dict[int, dict] = {}

    def a(n, stmt, exq, exa, gq, ga, trap, q1, a1, q2, a2):
        F[n] = dict(stmt=stmt, exq=exq, exa=exa, gq=gq, ga=ga, trap=trap, q1=q1, a1=a1, q2=q2, a2=a2)

    # D complex-number algebra
    a(174, r"A complex number in standard form is $z=a+bi$ with $a,b\in\mathbb{R}$ and $i^2=-1$. Here $a=\mathrm{Re}\,z$ and $b=\mathrm{Im}\,z$. Addition and multiplication follow the field axioms of $\mathbb{C}$, with $i^2$ reduced to $-1$.",
      r"Write $(3-2i)+(1+5i)$ and $(3-2i)(1+5i)$ in standard form.",
      r"$4+3i$. Product: $3+15i-2i-10i^2=3+13i+10=13+13i$.",
      r"$(1+i)^2$ equals", r"$1+2i+i^2=2i$.",
      r"Writing $i^2=+1$, or treating $a+bi$ as a vector and never multiplying.",
      r"Compute $(2+i)+(4-3i)$.", r"$6-2i$.",
      r"Expand $(x+i)(x-i)$.", r"$x^2+1$.")
    a(175, r"$\mathrm{Re}(a+bi)=a$ and $\mathrm{Im}(a+bi)=b$ are real-linear maps $\mathbb{C}\to\mathbb{R}$. They are not $\mathbb{C}$-linear. $z$ is real iff $\mathrm{Im}\,z=0$, pure imaginary iff $\mathrm{Re}\,z=0$.",
      r"If $z=5-7i$, find $\mathrm{Re}\,z$, $\mathrm{Im}\,z$, $\mathrm{Re}(iz)$.",
      r"$5$, $-7$. $iz=i(5-7i)=7+5i$, so $\mathrm{Re}(iz)=7$.",
      r"$\mathrm{Re}(z)+\mathrm{Im}(z)i$ equals", r"$z$ itself.",
      r"Calling $\mathrm{Im}(3i)$ equal to $3i$ instead of $3$.",
      r"$\mathrm{Im}(4)$ equals", r"$0$.",
      r"Is $\mathrm{Re}(zw)=\mathrm{Re}z\,\mathrm{Re}w$?", r"No: $(1+i)^2=2i$ has real part $0$, not $1$.")
    a(176, r"The conjugate of $z=a+bi$ is $\overline{z}=a-bi$. Conjugation is an automorphism of $\mathbb{C}$: $\overline{z+w}=\overline{z}+\overline{w}$, $\overline{zw}=\overline{z}\,\overline{w}$, $\overline{\overline{z}}=z$, and $z\overline{z}=|z|^2$. $z$ is real iff $z=\overline{z}$.",
      r"Compute $\overline{(2+3i)(1-i)}$.",
      r"Product $2-2i+3i+3=5+i$, conjugate $5-i$. Or $\overline{2+3i}\,\overline{1-i}=(2-3i)(1+i)=2+2i-3i+3=5-i$.",
      r"$z+\overline{z}$ equals", r"$2\mathrm{Re}\,z$.",
      r"Conjugating only the $i$ in a quotient after already simplifying incorrectly.",
      r"Solve $z=\overline{z}+4i$.", r"$a+bi=a-bi+4i$ so $2b=4$, $b=2$; $z=a+2i$ for any real $a$. Wait: $bi=-bi+4i$, $2b=4$, $b=2$. Yes $z=a+2i$.",
      r"Show $z\overline{z}$ is real and nonnegative.", r"$a^2+b^2\ge 0$.")
    a(177, r"The modulus is $|z|=\sqrt{z\overline{z}}=\sqrt{a^2+b^2}$. It is a norm: $|z|\ge 0$, $|z|=0\Leftrightarrow z=0$, $|zw|=|z||w|$, and $|z+w|\le|z|+|w|$. Also $|\overline{z}|=|z|$ and $|z^{-1}|=1/|z|$ for $z\neq 0$.",
      r"Compute $|3-4i|$ and $|i^{10}|$.",
      r"$5$. $|i|=1$ so $|i^{10}|=1$.",
      r"$|z|=1$ describes", r"the unit circle in the plane.",
      r"Writing $|a+bi|=a+b$, or $|z|^2=z^2$.",
      r"$|1+i|$.", r"$\sqrt{2}$.",
      r"Does $|z+w|=|z|+|w|$ for $z=1$, $w=i$?", r"No: $\sqrt{2}\neq 2$. Equality needs nonnegative-real multiple.")
    a(178, r"To divide, multiply by the conjugate of the denominator: $\dfrac{z}{w}=\dfrac{z\overline{w}}{|w|^2}$ for $w\neq 0$. The result is in standard form.",
      r"Compute $\dfrac{1+i}{1-i}$.",
      r"Multiply by $1+i$: numerator $(1+i)^2=2i$, denominator $2$, so $i$.",
      r"$\dfrac{1}{i}$ equals", r"$-i$, because $i(-i)=-i^2=1$.",
      r"Forgetting to multiply the numerator, or dividing moduli as if that gave the quotient in $\mathbb{C}$.",
      r"$\dfrac{2+4i}{1+i}$.", r"$\dfrac{(2+4i)(1-i)}{2}=3+i$.",
      r"Simplify $\dfrac{a+bi}{a-bi}$ when $a^2+b^2\neq 0$.", r"$\dfrac{(a+bi)^2}{a^2+b^2}$.")
    a(179, r"Identify $a+bi$ with the point $(a,b)$ (or the vector from the origin). Addition is vector addition. Multiplication by $re^{i\theta}$ is scaling by $r$ and rotation by $\theta$. The real axis is the horizontal axis; the imaginary axis is vertical.",
      r"What geometric map is multiplication by $i$?",
      r"Rotation by $\pi/2$ counterclockwise: $i(a+bi)=-b+ai$.",
      r"$|z-1|=2$ is", r"the circle of radius $2$ centered at $1$.",
      r"Thinking multiplication by $i$ is reflection, not rotation.",
      r"The set $|z-i|=|z+i|$ is", r"the real axis (perpendicular bisector of $i$ and $-i$).",
      r"Describe $z\mapsto \overline{z}$ geometrically.", r"Reflection through the real axis.")

    # D polar/exponential
    a(180, r"An argument of $z\neq 0$ is an angle $\theta$ with $z=|z|(\cos\theta+i\sin\theta)$. The principal argument $\mathrm{Arg}\,z$ is usually taken in $(-\pi,\pi]$ (sometimes $[0,2\pi)$). $\arg$ is defined up to $2\pi\mathbb{Z}$. $\arg(zw)=\arg z+\arg w$ up to $2\pi$.",
      r"Find $\mathrm{Arg}(-1)$ and $\mathrm{Arg}(-i)$.",
      r"$\pi$ and $-\pi/2$.",
      r"$\mathrm{Arg}(1+i)$ equals", r"$\pi/4$.",
      r"Using $\arctan(b/a)$ without the quadrant: $\mathrm{Arg}(-1-i)$ is $-3\pi/4$, not $\pi/4$.",
      r"$\mathrm{Arg}(i)$.", r"$\pi/2$.",
      r"Why is $\arg 0$ undefined?", r"$0$ has no direction in the plane.")
    a(181, r"Polar form: $z=r(\cos\theta+i\sin\theta)$ with $r=|z|$ and $\theta\in\arg z$. Equivalent: $z=re^{i\theta}$. Multiplication: $r_1 e^{i\theta_1}\cdot r_2 e^{i\theta_2}=r_1 r_2 e^{i(\theta_1+\theta_2)}$.",
      r"Write $-2$ in polar form.",
      r"$2(\cos\pi+i\sin\pi)=2e^{i\pi}$.",
      r"Polar form of $2i$ is", r"$2e^{i\pi/2}$.",
      r"Using $r$ negative in polar form without converting the angle.",
      r"Polar form of $1-i$.", r"$\sqrt{2}\,e^{-i\pi/4}$.",
      r"Product of $e^{i\pi/3}$ and $e^{i\pi/6}$.", r"$e^{i\pi/2}=i$.")
    a(182, r"Euler's formula: $e^{i\theta}=\cos\theta+i\sin\theta$ for real $\theta$ (and as an entire function of complex $\theta$). Consequences: $e^{i\pi}=-1$, $\cos\theta=(e^{i\theta}+e^{-i\theta})/2$, $\sin\theta=(e^{i\theta}-e^{-i\theta})/(2i)$.",
      r"Prove $\cos\theta+i\sin\theta$ has modulus $1$.",
      r"$|e^{i\theta}|^2=\cos^2\theta+\sin^2\theta=1$.",
      r"$e^{i\pi}+1$ equals", r"$0$.",
      r"Treating $e^{i\theta}$ as if it were real-exponential growth.",
      r"Write $\cos(\pi/3)$ via Euler.", r"$(e^{i\pi/3}+e^{-i\pi/3})/2=1/2$.",
      r"Simplify $e^{i\theta}e^{-i\theta}$.", r"$1$.")
    a(183, r"De Moivre: $[r(\cos\theta+i\sin\theta)]^n=r^n(\cos(n\theta)+i\sin(n\theta))$ for $n\in\mathbb{Z}$ (and for $n\in\mathbb{Q}$ with care about branches). Proof: $n$th power of $re^{i\theta}$.",
      r"Compute $(\cos\pi/6+i\sin\pi/6)^6$.",
      r"$\cos\pi+i\sin\pi=-1$.",
      r"$(1+i)^4$ via De Moivre", r"$(\sqrt{2})^4 e^{i\pi}=4(-1)=-4$. Angle of $1+i$ is $\pi/4$, times $4$ is $\pi$.",
      r"Applying De Moivre to a number not first written in polar form.",
      r"$(\cos\theta+i\sin\theta)^{-1}$.", r"$\cos\theta-i\sin\theta=\cos(-\theta)+i\sin(-\theta)$.",
      r"Compute $(1+i\sqrt{3})^3$ in polar form first.", r"$r=2$, $\theta=\pi/3$, so $8e^{i\pi}=-8$.")
    a(184, r"For $z=re^{i\theta}$ and real $\alpha$, one value of $z^\alpha$ is $r^\alpha e^{i\alpha\theta}$. Integer powers are unambiguous. Non-integer powers are multi-valued: extra factors $e^{i\alpha 2\pi k}$.",
      r"Compute $i^2$ and a principal value of $i^{1/2}$.",
      r"$i^2=-1$. Principal square root of $i=e^{i\pi/2}$ is $e^{i\pi/4}=\frac{\sqrt{2}}{2}(1+i)$.",
      r"$(e^{i\pi})^2$ vs $e^{i 2\pi}$", r"Both $1$. But $(e^{i\pi})^{1/2}$ is not $e^{i\pi/2}$ uniquely: also $e^{i(\pi/2+\pi)}=-i$.",
      r"Writing $a^b=e^{b\log a}$ with a real log of a negative $a$.",
      r"$ (2e^{i\pi/3})^3 $.", r"$8 e^{i\pi}=-8$.",
      r"How many values has $z^{1/3}$ for $z\neq 0$?", r"Three distinct cube roots.")
    a(185, r"The $n$th roots of $w=Re^{i\phi}$ are $z_k=R^{1/n}\exp\bigl(i(\phi+2\pi k)/n\bigr)$ for $k=0,\ldots,n-1$. They lie on the circle of radius $R^{1/n}$, equally spaced by $2\pi/n$.",
      r"Find all square roots of $-1$.",
      r"$-1=e^{i\pi}$. Roots $e^{i\pi/2}=i$ and $e^{i(\pi+2\pi)/2}=e^{i 3\pi/2}=-i$.",
      r"Cube roots of $8$ are", r"$2$, $2e^{i 2\pi/3}$, $2e^{i 4\pi/3}$.",
      r"Listing only the positive real root when $n$ is even.",
      r"Fourth roots of $1$.", r"$1,i,-1,-i$.",
      r"Product of all $n$th roots of $1$.", r"$0$ if $n>1$? Wait: they are the roots of $z^n-1=0$, product is $(-1)^n(-1)=(-1)^{n+1}$ times constant: for $z^n-1$, product of roots is $(-1)^n(-1)/1=(-1)^{n+1}$. For $n=2$: $1\cdot(-1)=-1=(-1)^{3}$. Yes.")
    a(186, r"The $n$th roots of unity are the solutions of $z^n=1$: $\omega_k=e^{2\pi i k/n}$, $k=0,\ldots,n-1$. They form a cyclic group under multiplication. A primitive $n$th root generates the group. $1+\omega+\cdots+\omega^{n-1}=0$ if $\omega\neq 1$ is an $n$th root of unity.",
      r"The primitive cube roots of unity.",
      r"$\omega=e^{2\pi i/3}=-\frac12+i\frac{\sqrt{3}}{2}$ and $\omega^2=e^{-2\pi i/3}$, with $1+\omega+\omega^2=0$ and $\omega^3=1$.",
      r"Sum of all $5$th roots of unity", r"$0$.",
      r"Calling $-1$ a primitive $4$th root (order of $-1$ is $2$, not $4$).",
      r"Is $i$ a primitive $4$th root of unity?", r"Yes: $i, i^2=-1, i^3=-i, i^4=1$.",
      r"How many primitive $6$th roots of unity?", r"$\phi(6)=2$: $e^{2\pi i/6}=e^{i\pi/3}$ and $e^{5i\pi/3}$.")
    a(187, r"The $n$th roots of a nonzero $w$ are the vertices of a regular $n$-gon on the circle $|z|=|w|^{1/n}$, one of them being a chosen polar $n$th root. Rotating by $2\pi/n$ cycles them.",
      r"Where do the cube roots of $i$ lie?",
      r"On the circle of radius $1$, at angles $(\pi/2+2\pi k)/3$ for $k=0,1,2$, i.e. $\pi/6$, $5\pi/6$, $3\pi/2$.",
      r"The fourth roots of $16$ form", r"a square with vertices $2,-2,2i,-2i$.",
      r"Drawing the polygon at radius $|w|$ instead of $|w|^{1/n}$.",
      r"Angle spacing of $5$th roots of $32$.", r"$2\pi/5$, radius $2$.",
      r"Do the $n$th roots of $-1$ include $1$?", r"Only if $n$ is even? $1^n=1\neq -1$. Never. They include $-1$ when $n$ is odd.")

    # D complex polynomials
    a(188, r"Fundamental theorem of algebra: every nonconstant polynomial with complex coefficients has a root in $\mathbb{C}$. Consequently it factors as $a(z-r_1)\cdots(z-r_n)$ over $\mathbb{C}$, counting multiplicity. $\mathbb{C}$ is algebraically closed.",
      r"How many complex roots, counting multiplicity, has $z^4+z+1=0$?",
      r"Four. (None need be real.)",
      r"$x^2+1$ over $\mathbb{R}$ vs $\mathbb{C}$", r"Irreducible over $\mathbb{R}$; $(x-i)(x+i)$ over $\mathbb{C}$.",
      r"Claiming every polynomial of odd degree has a real root — that is $\mathbb{R}$, not the FTA over $\mathbb{C}$.",
      r"Does $e^z=0$ contradict FTA?", r"No: $e^z$ is not a polynomial.",
      r"A degree-$0$ polynomial has how many roots?", r"None (unless it is the zero polynomial, which has every point as a root).")
    a(189, r"If a polynomial with real coefficients has a nonreal root $z$, then $\overline{z}$ is also a root, with the same multiplicity. Proof: coefficients real means $\overline{p(z)}=p(\overline{z})$.",
      r"$x^2-2x+2=0$ has roots $1\pm i$. Why must both appear?",
      r"Real coefficients. Discriminant $4-8=-4$.",
      r"Must $x^2+ix+1$ have conjugate roots?", r"No: coefficients are not all real.",
      r"Applying conjugate-root to a polynomial with a complex coefficient.",
      r"A real cubic has at least how many real roots?", r"At least one (odd degree over $\mathbb{R}$). Nonreal roots come in pairs, so the leftover is real.",
      r"Can a real quartic have exactly one nonreal root?", r"No: conjugates pair.")
    a(190, r"Over $\mathbb{C}$, every polynomial factors into linear factors. Over $\mathbb{R}$, the irreducible factors are linear or quadratic with negative discriminant. Factoring over $\mathbb{C}$ is writing $p(z)=a\prod(z-r_j)$.",
      r"Factor $x^4-1$ over $\mathbb{C}$ and over $\mathbb{R}$.",
      r"Over $\mathbb{C}$: $(x-1)(x+1)(x-i)(x+i)$. Over $\mathbb{R}$: $(x-1)(x+1)(x^2+1)$.",
      r"$x^2+x+1$ over $\mathbb{C}$", r"$(x-\omega)(x-\omega^2)$ with $\omega=e^{2\pi i/3}$.",
      r"Stopping at quadratics when the problem asked for factoring over $\mathbb{C}$.",
      r"Factor $x^2+2x+5$ over $\mathbb{C}$.", r"$(x+1-2i)(x+1+2i)$.",
      r"Is $x^2+1$ irreducible over $\mathbb{C}$?", r"No.")
    a(191, r"If the unknown is a power, $z^n=c$ is solved by roots of $c$. Cyclotomic substitutions $z^n=1$ collapse geometric series and many reciprocal equations. For $1+z+z^2+\cdots+z^{n-1}=0$, the solutions are the non-real $n$th roots of unity when $z\neq 1$.",
      r"Solve $z^4+z^3+z^2+z+1=0$.",
      r"Multiply by $z-1$: $z^5-1=0$ and $z\neq 1$, so primitive $5$th roots of unity.",
      r"$z^3=8$ solutions", r"$2, 2\omega, 2\omega^2$.",
      r"Dividing by $z-1$ without noting $z=1$ is not a root of the original.",
      r"Solve $z^2-z+1=0$ via roots of unity.", r"Primitive $6$th roots: $e^{i\pi/3}, e^{i 5\pi/3}$.",
      r"Sum $1+\zeta+\zeta^2$ for $\zeta=e^{2\pi i/3}$.", r"$0$.")
    a(192, r"$|zw|=|z||w|$ and $\arg(zw)=\arg z+\arg w$ (mod $2\pi$). Division: $|z/w|=|z|/|w|$ and $\arg(z/w)=\arg z-\arg w$. In particular $|z^n|=|z|^n$ and $\arg(z^n)=n\arg z$.",
      r"If $|z|=2$ and $\arg z=\pi/6$, find $|z^3|$ and $\arg(z^3)$.",
      r"$8$ and $\pi/2$.",
      r"$|z/w|=1$ means", r"$|z|=|w|$ (if $w\neq 0$).",
      r"Adding arguments without reducing mod $2\pi$ when a principal Arg is required: $\mathrm{Arg}((-1)(-1))=0\neq \pi+\pi$.",
      r"$|i^{100}|$.", r"$1$.",
      r"$\arg\bigl((1+i)/(1-i)\bigr)$.", r"$(1+i)/(1-i)=i$, so $\pi/2$.")

    # E limits
    a(193, r"The informal meaning: $\lim_{x\to a}f(x)=L$ says that $f(x)$ can be made arbitrarily close to $L$ by taking $x$ sufficiently close to $a$ but not equal to $a$. The value $f(a)$ is irrelevant and may fail to exist.",
      r"Does $\lim_{x\to 0}\dfrac{\sin x}{x}$ care that the formula is undefined at $0$?",
      r"No. The limit is $1$. The function can be defined at $0$ or not.",
      r"$\lim_{x\to 2}(x+1)$ equals", r"$3$, which happens to equal $f(2)$.",
      r"Substituting $x=a$ into a formula that is undefined at $a$ and declaring the limit DNE.",
      r"True or false: if $f(a)=L$ then $\lim_{x\to a}f(x)=L$.", r"False (jump discontinuity).",
      r"True or false: if the limit exists, $f$ is defined at $a$.", r"False.")
    a(194, r"$\lim_{x\to a}f(x)=L$ means: for every $\varepsilon>0$ there exists $\delta>0$ such that $0<|x-a|<\delta$ implies $|f(x)-L|<\varepsilon$. The $0<$ excludes $x=a$.",
      r"Prove $\lim_{x\to 3}(2x+1)=7$ from the definition.",
      r"$|2x+1-7|=2|x-3|$. Given $\varepsilon>0$, take $\delta=\varepsilon/2$. Then $0<|x-3|<\delta$ implies $|f-7|<\varepsilon$.",
      r"In $\varepsilon$-$\delta$, $\delta$ may depend on", r"$\varepsilon$ and $a$, not on $x$.",
      r"Proving the implication for one $\varepsilon$ (say $0.1$) and stopping.",
      r"Find a $\delta$ for $\lim_{x\to 1}x=1$ with $\varepsilon=0.01$.", r"$\delta=0.01$ works.",
      r"Why $0<|x-a|$?", r"The limit ignores $f(a)$.")
    a(195, r"One-sided limits: $x\to a^+$ means $x>a$, $x\to a^-$ means $x<a$. The two-sided limit exists iff both one-sided limits exist and are equal. Absolute values and piecewise functions force one-sided checks.",
      r"$\lim_{x\to 0^-}|x|/x$ and $\lim_{x\to 0^+}|x|/x$.",
      r"$-1$ and $+1$. Two-sided limit DNE.",
      r"$f(x)=\sqrt{x}$ as $x\to 0^-$", r"DNE in $\mathbb{R}$ (not in the domain).",
      r"Checking only the right-hand limit for a two-sided claim.",
      r"$\lim_{x\to 2^-}(x-2)/|x-2|$.", r"$-1$.",
      r"If both one-sided limits equal $5$, the two-sided limit is", r"$5$.")
    a(196, r"$\lim_{x\to a}f(x)=\infty$ means $f$ grows without bound as $x\to a$: for every $M>0$ there is $\delta>0$ such that $0<|x-a|<\delta$ implies $f(x)>M$. This is not a real-number limit; we still often say the two-sided limit DNE as a real.",
      r"$\lim_{x\to 0}1/x^2$.",
      r"$+\infty$ (both sides).",
      r"$\lim_{x\to 0}1/x$", r"Does not exist even as $\pm\infty$ two-sided: left $-\infty$, right $+\infty$.",
      r"Writing $\infty-\infty=0$ or treating $\infty$ as a real in arithmetic.",
      r"$\lim_{x\to 1}1/(x-1)^2$.", r"$+\infty$.",
      r"Is $\infty$ a limit in $\mathbb{R}$?", r"No. Extended reals are a separate language.")
    a(197, r"$\lim_{x\to\infty}f(x)=L$ means: for every $\varepsilon>0$ there is $N$ such that $x>N$ implies $|f(x)-L|<\varepsilon$. Horizontal asymptotes are this statement. For $-\infty$, $x<N$.",
      r"$\lim_{x\to\infty}\dfrac{3x^2-1}{x^2+5}$.",
      r"Divide by $x^2$: $3$.",
      r"$\lim_{x\to\infty}\sin x$", r"DNE (oscillation).",
      r"Canceling leading terms and getting $0$ when degrees are equal.",
      r"$\lim_{x\to\infty}(1-1/x)^x$.", r"$e^{-1}$.",
      r"$\lim_{x\to-\infty}e^x$.", r"$0$.")
    a(198, r"If $\lim f=L$ and $\lim g=M$ (finite), then limits of $f\pm g$, $fg$, and $f/g$ (if $M\neq 0$) are $L\pm M$, $LM$, $L/M$. Constants pull out. These fail if any limit is infinite or DNE, until you have a separate theorem.",
      r"$\lim_{x\to 1}(x^2+3x)(x-1)$.",
      r"$4\cdot 0=0$.",
      r"If $\lim f=0$ and $\lim g=\infty$, $\lim fg$", r"Indeterminate; can be anything.",
      r"Using the quotient law when the denominator limit is $0$.",
      r"$\lim_{x\to 2}(x+1)/(x-3)$.", r"$-3$.",
      r"Does $\lim(f+g)=\lim f+\lim g$ if $\lim f$ DNE?", r"Not in general (unless $g$ compensates).")
    a(199, r"Squeeze (sandwich): if $g(x)\le f(x)\le h(x)$ near $a$ (except possibly $a$) and $\lim g=\lim h=L$, then $\lim f=L$. Typical use: bounding a messy factor by $\pm 1$.",
      r"Prove $\lim_{x\to 0}x\sin(1/x)=0$.",
      r"$-|x|\le x\sin(1/x)\le|x|$, and $\pm|x|\to 0$.",
      r"$\lim_{x\to 0}x^2\cos(1/x)$", r"$0$ by squeeze.",
      r"Squeezing with bounds that do not share a limit.",
      r"Does squeeze apply to $\sin(1/x)$ itself as $x\to 0$?", r"No: it is not trapped by functions with a common limit.",
      r"Bound $|\sin x|\le|x|$ for the classical $\sin x/x$ argument.", r"Yes, for $x\neq 0$ in radians, geometric proof.")
    a(200, r"Standard trigonometric limits (radians): $\lim_{\theta\to 0}\dfrac{\sin\theta}{\theta}=1$, $\lim_{\theta\to 0}\dfrac{1-\cos\theta}{\theta^2}=\dfrac12$, $\lim_{\theta\to 0}\dfrac{\tan\theta}{\theta}=1$. Scale: $\lim\dfrac{\sin(kx)}{x}=k$.",
      r"$\lim_{x\to 0}\dfrac{\sin 5x}{x}$.",
      r"$5$.",
      r"$\lim_{x\to 0}\dfrac{1-\cos x}{x}$", r"$0$ (numerator $\sim x^2/2$).",
      r"Using degrees with these limits (the derivative of $\sin$ would then be $\pi/180\cos$).",
      r"$\lim_{x\to 0}\dfrac{\tan 3x}{2x}$.", r"$3/2$.",
      r"$\lim_{x\to 0}\dfrac{\sin x}{\sin 4x}$.", r"$1/4$.")
    a(201, r"Standard exponential/log limits: $\lim_{x\to 0}(e^x-1)/x=1$, $\lim_{x\to 0}\ln(1+x)/x=1$, $\lim_{n\to\infty}(1+a/n)^n=e^a$, $\lim_{x\to\infty}x^p e^{-x}=0$ for any $p$, $\lim_{x\to 0^+}x^a\ln x=0$ for $a>0$.",
      r"$\lim_{x\to 0}\dfrac{\ln(1+3x)}{x}$.",
      r"$3$.",
      r"$\lim_{x\to\infty}e^{-x}x^{100}$", r"$0$. Exponential beats polynomial.",
      r"Writing $\ln(1+x)\sim x$ as $x\to\infty$ (that is as $x\to 0$).",
      r"$\lim_{n\to\infty}(1+2/n)^n$.", r"$e^2$.",
      r"$\lim_{x\to 0^+}x\ln x$.", r"$0$.")
    a(202, r"The form $0/0$ is indeterminate: the limit of $f/g$ when both tend to $0$ can be any real, $\pm\infty$, or DNE. Algebraic repair: factor, conjugate, trig identities, or L'Hôpital once hypotheses hold.",
      r"$\lim_{x\to 1}\dfrac{x^2-1}{x-1}$.",
      r"Factor: $x+1\to 2$.",
      r"$\lim_{x\to 0}\dfrac{\sqrt{1+x}-1}{x}$", r"Rationalize: $1/(\sqrt{1+x}+1)\to 1/2$.",
      r"Canceling $x-1$ and plugging $x=1$ without stating $x\neq 1$, then claiming the original is defined at $1$.",
      r"$\lim_{x\to 2}\dfrac{x^2-4}{x^2-x-2}$.", r"$(x-2)(x+2)/(x-2)(x+1)\to 4/3$.",
      r"Can $0/0$ have limit $\infty$?", r"Yes, e.g. $x/x^2$ as $x\to 0$.")
    a(203, r"The form $\infty/\infty$ is indeterminate. Repair: divide numerator and denominator by the dominant term (highest power, or exponential vs polynomial), or L'Hôpital.",
      r"$\lim_{x\to\infty}\dfrac{4x^3-x}{2x^3+7}$.",
      r"$2$.",
      r"$\lim_{x\to\infty}\dfrac{e^x}{x^2}$", r"$+\infty$.",
      r"Comparing degrees incorrectly when the leading coefficients cancel.",
      r"$\lim_{x\to\infty}\dfrac{3x+5}{\sqrt{x^2+1}}$.", r"$3$ (divide by $x>0$).",
      r"$\lim_{x\to-\infty}\dfrac{3x}{\sqrt{x^2+1}}$.", r"$-3$ (divide by $|x|=-x$).")
    a(204, r"Other indeterminate forms: $0\cdot\infty$, $\infty-\infty$, $1^\infty$, $0^0$, $\infty^0$. Convert to $0/0$ or $\infty/\infty$ by algebra or by taking logs (for exponential forms).",
      r"$\lim_{x\to\infty}(1+1/x)^x$.",
      r"$e$. Write as $\exp\bigl(x\ln(1+1/x)\bigr)$ and $x\ln(1+1/x)\to 1$.",
      r"$\lim_{x\to 0^+}x^x$", r"$1$, via $e^{x\ln x}$ and $x\ln x\to 0$.",
      r"Declaring $1^\infty=1$ or $0^0=1$ without a limit.",
      r"$\lim_{x\to\infty}(\sqrt{x^2+x}-x)$.", r"Rationalize: $x/(\sqrt{x^2+x}+x)\to 1/2$.",
      r"Is $0^0$ as a limit always $1$?", r"No. $x^{1/\ln x}$ type examples vary.")
    a(205, r"L'Hôpital: if $f,g$ are differentiable near $a$, $g'\neq 0$ except possibly at $a$, and $f/g$ is $0/0$ or $\infty/\infty$, and $\lim f'/g'$ exists, then $\lim f/g=\lim f'/g'$. May repeat. Does not apply to other forms until rewritten.",
      r"$\lim_{x\to 0}\dfrac{\sin x-x}{x^3}$.",
      r"Three applications (or Taylor): $-1/6$.",
      r"$\lim_{x\to\infty}x/e^x$", r"$\infty/\infty$, L'Hôpital: $1/e^x\to 0$.",
      r"Applying L'Hôpital when the limit of $f'/g'$ DNE even though $f/g$ has a limit, or differentiating the quotient as a quotient rule.",
      r"$\lim_{x\to 0}\dfrac{e^x-1-x}{x^2}$.", r"$1/2$.",
      r"Does L'Hôpital apply to $\lim_{x\to 0}x/x$?", r"It is $0/0$ and works, but cancellation is cheaper; the hypotheses hold.")
    a(206, r"Asymptotic comparison: $f\sim g$ as $x\to a$ means $f/g\to 1$. Little-o: $f=o(g)$ means $f/g\to 0$. Big-O: $f=O(g)$ means $f/g$ is bounded. Polynomials are ordered by degree; exponentials dominate polynomials; polynomials dominate logs.",
      r"As $x\to 0$, $\sin x\sim$?",
      r"$x$. Also $1-\cos x\sim x^2/2$.",
      r"As $x\to\infty$, is $x^2=o(e^x)$?", r"Yes.",
      r"Writing $O(x)+O(x)=O(x^2)$.",
      r"As $x\to\infty$, $\ln x=o(x^{1/100})$?", r"Yes.",
      r"As $x\to 0$, $\tan x\sim x$ implies $\tan 5x\sim$?", r"$5x$.")

    # E continuity
    a(207, r"$f$ is continuous at $a$ if $\lim_{x\to a}f(x)=f(a)$. In particular $f$ must be defined at $a$, the limit must exist, and the two must match. $\varepsilon$-$\delta$: $|x-a|<\delta$ implies $|f(x)-f(a)|<\varepsilon$ (now including $x=a$).",
      r"Is $f(x)=x\sin(1/x)$ for $x\neq 0$, $f(0)=0$, continuous at $0$?",
      r"Yes: squeezed to $0=f(0)$.",
      r"$f(x)=(x^2-1)/(x-1)$ for $x\neq 1$, $f(1)=0$", r"Limit is $2\neq 0$, discontinuous at $1$.",
      r"Checking $f(a)$ exists and skipping the limit.",
      r"Polynomials are continuous where?", r"Everywhere on $\mathbb{R}$.",
      r"Is $|x|$ continuous at $0$?", r"Yes.")
    a(208, r"$f$ is continuous on $[a,b]$ if it is continuous at every point of $(a,b)$, right-continuous at $a$, and left-continuous at $b$. Continuous functions on a closed bounded interval are bounded and attain extrema (EVT) and hit every intermediate value (IVT).",
      r"Is $1/x$ continuous on $(0,1]$? On $[0,1]$?",
      r"Yes on $(0,1]$. No on $[0,1]$ (not defined at $0$, and unbounded).",
      r"A continuous $f:[0,1]\to\mathbb{R}$ must be", r"bounded, attain max/min, and have the intermediate value property.",
      r"Claiming continuity on an open interval implies boundedness: $\tan$ on $(0,\pi/2)$.",
      r"Is $\sqrt{x}$ continuous on $[0,1]$?", r"Yes (one-sided at $0$).",
      r"Can a function continuous on $(0,1)$ be unbounded?", r"Yes, $1/x$.")
    a(209, r"A discontinuity at $a$ is removable if $\lim_{x\to a}f(x)$ exists (finite) but is not equal to $f(a)$, or $f(a)$ is undefined. Redefining $f(a)$ to equal the limit removes it.",
      r"Classify $f(x)=\dfrac{\sin x}{x}$ at $0$.",
      r"Removable; define $f(0)=1$.",
      r"$(x^2-9)/(x-3)$ at $x=3$", r"Removable; limit $6$.",
      r"Calling a jump removable because you can draw a vertical segment.",
      r"Is $1/x$ removable at $0$?", r"No: limit infinite.",
      r"$x/|x|$ at $0$?", r"Not removable (jump).")
    a(210, r"A jump discontinuity: both one-sided limits exist and are finite but unequal. Typical of step functions and piecewise definitions that do not match at the joint.",
      r"Classify $f(x)=0$ for $x<0$ and $f(x)=1$ for $x\ge 0$ at $0$.",
      r"Jump: left $0$, right $1=f(0)$.",
      r"$\lfloor x\rfloor$ at integers", r"Jump (left value is $n-1$, right and value $n$).",
      r"Calling every piecewise function a jump.",
      r"Can a jump be made continuous by redefining one point?", r"No: one-sided limits disagree.",
      r"$|x|/x$ at $0$ is a", r"jump (if we even define it).")
    a(211, r"An infinite discontinuity: at least one one-sided limit is $\pm\infty$. Vertical asymptotes are the graph picture. Not removable.",
      r"Classify $1/(x-2)$ at $x=2$.",
      r"Infinite (two-sided does not exist; sides $\pm\infty$).",
      r"$\tan x$ at $\pi/2$", r"Infinite.",
      r"Calling $1/x^2$ a jump at $0$.",
      r"$1/x^2$ at $0$: removable?", r"No, infinite ($+\infty$ both sides).",
      r"Does an infinite discontinuity have a finite one-sided limit?", r"Not on the infinite side.")
    a(212, r"If $g$ is continuous at $a$ and $f$ is continuous at $g(a)$, then $f\circ g$ is continuous at $a$. Polynomials, exp, ln (on $(0,\infty)$), sin, cos, and rational functions (off poles) are continuous on their domains; compositions inherit this.",
      r"Where is $\ln(\sin x)$ continuous?",
      r"Where $\sin x>0$, e.g. $(2k\pi,(2k+1)\pi)$.",
      r"$\sqrt{1-x^2}$ is continuous on", r"$[-1,1]$.",
      r"Composing and forgetting the inner range must land in the outer domain: $\ln(x^2-1)$ needs $|x|>1$.",
      r"Is $\sin(e^{x})$ continuous on $\mathbb{R}$?", r"Yes.",
      r"Domain of $\arcsin(2x)$.", r"$[-1/2,1/2]$.")
    a(213, r"IVT: if $f$ is continuous on $[a,b]$ and $k$ is between $f(a)$ and $f(b)$, then some $c\in[a,b]$ has $f(c)=k$. Existence, not uniqueness. Used to prove roots exist without constructing them.",
      r"Show $x^3+x-1=0$ has a root in $(0,1)$.",
      r"$f(0)=-1<0<f(1)=1$, continuous, IVT.",
      r"Does IVT say the root is unique?", r"No. $f(x)=x^3-x$ on $[-2,2]$ hits $0$ three times.",
      r"Applying IVT to a discontinuous function: a step that skips the value.",
      r"Must a continuous $f:\mathbb{R}\to\mathbb{R}$ with $f(-1)=2$, $f(1)=-5$ have a zero?", r"Yes, on $[-1,1]$.",
      r"Can IVT fail if we drop continuity at one point?", r"Yes.")
    a(214, r"EVT: a continuous $f:[a,b]\to\mathbb{R}$ attains a maximum and a minimum. Proof uses boundedness of continuous functions on compact intervals, then a sequence approaching the sup. On open or unbounded intervals, EVT can fail.",
      r"Does $f(x)=x$ on $(0,1)$ attain a max?",
      r"No. EVT needs a closed bounded interval.",
      r"Where does $x^2$ on $[-1,2]$ attain its max?", r"$x=2$, value $4$. Min at $0$.",
      r"Looking only at critical points and forgetting endpoints.",
      r"$e^{-x}$ on $[0,\infty)$ attain a min?", r"No min (approaches $0$); max at $0$.",
      r"Why check endpoints for absolute extrema on $[a,b]$?", r"EVT says extrema exist; they occur at critical points or endpoints.")

    # E derivative definition & rules
    a(215, r"The derivative at $a$ is $f'(a)=\lim_{h\to 0}\dfrac{f(a+h)-f(a)}{h}$ when the limit exists. Equivalent: $\lim_{x\to a}\dfrac{f(x)-f(a)}{x-a}$. Differentiability at $a$ implies continuity at $a$; the converse is false.",
      r"Compute $f'(1)$ from the definition for $f(x)=x^2$.",
      r"$\lim_{h\to 0}((1+2h+h^2)-1)/h=\lim(2+h)=2$.",
      r"$|x|$ at $0$", r"Not differentiable: difference quotient $\pm 1$.",
      r"Using the definition but canceling $h$ and forgetting to take $h\to 0$.",
      r"Difference quotient of $f(x)=3x+2$.", r"Always $3$, so $f'=3$.",
      r"Does differentiability imply continuity?", r"Yes.")
    a(216, r"$f'(a)$ is the slope of the tangent line $y=f(a)+f'(a)(x-a)$ when it exists. Geometrically it is the limit of secant slopes. A corner, cusp, or vertical tangent is a geometric failure of (finite) differentiability.",
      r"Tangent line to $y=x^2$ at $x=1$.",
      r"$y=1+2(x-1)=2x-1$.",
      r"Vertical tangent of $y=x^{1/3}$ at $0$", r"$x=0$; derivative $+\infty$, not a real $f'(0)$.",
      r"Calling a secant the tangent because it looks close on a graphing window.",
      r"Slope of $y=\sqrt{x}$ at $x=4$.", r"$1/4$.",
      r"Why is there no tangent slope to $|x|$ at $0$?", r"Left and right secant limits disagree.")
    a(217, r"If $s(t)$ is position, $s'(t)$ is instantaneous velocity and $s''(t)$ is acceleration. More generally $f'(a)$ is the instantaneous rate of change of $f$ at $a$. Units: units of $f$ per unit of the input.",
      r"If $s(t)=16t^2$ feet, $t$ in seconds, velocity at $t=2$.",
      r"$s'=32t$, so $64$ ft/s.",
      r"A decreasing $f$ has", r"negative derivative (where it exists and is continuous, $f'<0$ implies decreasing).",
      r"Mixing average rate $\frac{f(b)-f(a)}{b-a}$ with $f'(a)$ without a limit.",
      r"Average velocity on $[1,3]$ for $s=t^2$.", r"$(9-1)/2=4$. Instantaneous at $2$ is $4$ as well here.",
      r"If $T$ is temperature in $^\circ$C and $t$ hours, $T'$ has units", r"$^\circ$C per hour.")
    a(218, r"Power rule: $\dfrac{d}{dx}x^n=n x^{n-1}$ for real $n$, on the natural domain ($x>0$ if $n$ is not integer, $x\neq 0$ if $n$ is negative integer, etc.). Constant multiple and sum rules let you differentiate polynomials termwise.",
      r"Differentiate $4x^5-7x+2$.",
      r"$20x^4-7$.",
      r"$\dfrac{d}{dx}\sqrt{x}$", r"$\dfrac{1}{2\sqrt{x}}$.",
      r"Writing $\frac{d}{dx}x^n=x^{n-1}$ (dropping $n$), or $\frac{d}{dx}2^x=x 2^{x-1}$.",
      r"$\dfrac{d}{dx}x^{-3}$.", r"$-3x^{-4}$.",
      r"$\dfrac{d}{dx}7$.", r"$0$.")
    a(219, r"Product rule: $(fg)'=f'g+fg'$. Not $(fg)'=f'g'$. For three factors: $f'gh+fg'h+fgh'$.",
      r"Differentiate $x^2\sin x$.",
      r"$2x\sin x+x^2\cos x$.",
      r"$(uv)'$ at a point where $u=0$", r"$u'v$ (the $uv'$ term vanishes).",
      r"Differentiating a product as a product of derivatives.",
      r"$(xe^x)'$.", r"$e^x(x+1)$.",
      r"$(fgh)'$ with $f=g=h=x$.", r"$3x^2$, matching $(x^3)'$.")
    a(220, r"Quotient rule: $\left(\dfrac{f}{g}\right)'=\dfrac{f'g-fg'}{g^2}$ where $g\neq 0$. Memory: low d-high minus high d-low, over low squared. Equivalent to product rule with $g^{-1}$.",
      r"Differentiate $\dfrac{x}{x+1}$.",
      r"$\dfrac{(x+1)-x}{(x+1)^2}=\dfrac{1}{(x+1)^2}$.",
      r"$\left(\dfrac{\sin x}{x}\right)'$", r"$\dfrac{x\cos x-\sin x}{x^2}$.",
      r"Swapping the subtraction order in the numerator.",
      r"$(1/x)'$ via quotient.", r"$-1/x^2$.",
      r"$\left(\dfrac{e^x}{x}\right)'$.", r"$e^x(x-1)/x^2$.")
    a(221, r"Chain rule: $(f\circ g)'(x)=f'(g(x))\,g'(x)$. Outside derivative, evaluated at the inside, times inside derivative. Leibniz: $\dfrac{dy}{dx}=\dfrac{dy}{du}\dfrac{du}{dx}$.",
      r"Differentiate $\sin(x^2)$.",
      r"$\cos(x^2)\cdot 2x$.",
      r"$\dfrac{d}{dx}e^{3x}$", r"$3e^{3x}$.",
      r"Forgetting to multiply by the inner derivative: $(\sin 5x)'=\cos 5x$.",
      r"$( (3x+1)^4 )'$.", r"$12(3x+1)^3$.",
      r"$\dfrac{d}{dx}\ln(\cos x)$.", r"$-\tan x$ (where $\cos x>0$).")
    a(222, r"Implicit differentiation: if $F(x,y)=0$ defines $y$ as a differentiable function of $x$ locally, differentiate both sides in $x$, treating $y=y(x)$, then solve for $y'$. The chain rule produces $y'$ terms.",
      r"Find $y'$ if $x^2+y^2=1$.",
      r"$2x+2y y'=0$, so $y'=-x/y$ if $y\neq 0$.",
      r"Tangent to $x^2+y^2=1$ at $(3/5,4/5)$", r"Slope $-3/4$.",
      r"Treating $y$ as a constant, or forgetting $y'$ on every $y$ factor.",
      r"$xy=1$, $y'$.", r"$y+xy'=0$, $y'=-y/x=-1/x^2$.",
      r"Second derivative from $y'=-x/y$.", r"$y''=-(y-xy')/y^2=-(y^2+x^2)/y^3=-1/y^3$ on the circle.")
    a(223, r"Logarithmic differentiation: for $y=f(x)^{g(x)}$ or messy products, set $\ln|y|=g\ln|f|$ (on intervals where $y\neq 0$), differentiate, then multiply by $y$. Also useful for $x^x$.",
      r"Differentiate $y=x^x$ for $x>0$.",
      r"$\ln y=x\ln x$, $y'/y=\ln x+1$, $y'=x^x(\ln x+1)$.",
      r"$y=(x^2+1)^{\sin x}$, $\ln y=$", r"$\sin x\cdot\ln(x^2+1)$.",
      r"Writing $(x^x)'=x\cdot x^{x-1}$ (power rule with variable base and exponent).",
      r"$y=(\sin x)^x$ on $(0,\pi)$, $y'$.", r"$(\sin x)^x\bigl(\ln\sin x+x\cot x\bigr)$.",
      r"Product $y=x(x+1)(x+2)$ via logs.", r"$y'=y\bigl(1/x+1/(x+1)+1/(x+2)\bigr)$.")
    a(224, r"Higher derivatives: $f''=(f')'$, $f^{(n)}$ the $n$th derivative. Notation $y''$, $\dfrac{d^n y}{dx^n}$. Patterns: polynomials eventually vanish; $\sin$ and $\cos$ cycle every $4$; $e^{ax}$ stays a multiple of itself.",
      r"$f(x)=x^4$, $f^{(4)}(x)$ and $f^{(5)}$.",
      r"$24$ and $0$.",
      r"$(\sin x)^{(n)}$", r"$\sin(x+n\pi/2)$.",
      r"Confusing $f^{(n)}$ with $(f(x))^n$.",
      r"$(\,e^{2x}\,)''$.", r"$4e^{2x}$.",
      r"If $f''=0$ on an interval, $f$ is", r"affine: $f(x)=ax+b$.")
    a(225, r"If $f$ is differentiable and $f'(a)\neq 0$ with $f$ locally invertible, then $(f^{-1})'(b)=1/f'(a)$ where $b=f(a)$. In Leibniz form $\dfrac{dx}{dy}=1\big/\dfrac{dy}{dx}$.",
      r"Derivative of $\arcsin x$ from this rule.",
      r"$y=\arcsin x$, $x=\sin y$, $dx/dy=\cos y=\sqrt{1-x^2}$ (principal range), so $dy/dx=1/\sqrt{1-x^2}$.",
      r"If $f(2)=5$ and $f'(2)=4$, $(f^{-1})'(5)$", r"$1/4$.",
      r"Using $1/f'(b)$ instead of $1/f'(a)$ where $b=f(a)$.",
      r"Derivative of $\ln x$ as inverse of $e^x$.", r"$1/x$.",
      r"If $f'(a)=0$, can $f^{-1}$ be differentiable at $f(a)$?", r"No finite derivative: horizontal tangent becomes vertical.")

    # E standard derivatives
    a(226, r"A polynomial $p(x)=\sum_{k=0}^n a_k x^k$ has $p'(x)=\sum_{k=1}^n k a_k x^{k-1}$. Term-by-term power rule. Degree drops by $1$ (unless $p$ is constant).",
      r"Differentiate $7x^3-2x^2+x-9$.",
      r"$21x^2-4x+1$.",
      r"Degree of $p'$ if $\deg p=n\ge 1$", r"$n-1$.",
      r"Differentiating $a_0$ as if it were $a_0 x$.",
      r"$(x^n-1)'$.", r"$n x^{n-1}$.",
      r"If $p$ is quadratic, $p''$ is", r"a constant (twice the leading coefficient).")
    a(227, r"$(e^x)'=e^x$. $(e^{ax})'=a e^{ax}$. $(a^x)'=a^x\ln a$ for $a>0$. The exponential is the unique (up to scalar) function equal to its derivative.",
      r"Differentiate $e^{-x^2}$.",
      r"$-2x e^{-x^2}$.",
      r"$(2^x)'$", r"$2^x\ln 2$.",
      r"Writing $(e^{x^2})'=e^{2x}$ or $(a^x)'=x a^{x-1}$.",
      r"$(e^{3x+1})'$.", r"$3e^{3x+1}$.",
      r"Solve $f'=2f$, $f(0)=3$.", r"$f=3e^{2x}$.")
    a(228, r"$(\ln x)'=1/x$ for $x>0$. $(\log_a x)'=1/(x\ln a)$. $(\ln|x|)'=1/x$ for $x\neq 0$. Chain: $(\ln u)'=u'/u$.",
      r"Differentiate $\ln(x^2+1)$.",
      r"$\dfrac{2x}{x^2+1}$.",
      r"$(\log_{10} x)'$", r"$1/(x\ln 10)$.",
      r"Writing $(\ln x)'=\ln 1=0$, or $(\ln(5x))'=1/x$ forgetting the $5$ cancels actually — wait $(\ln(5x))'=1/x$ is correct because $\ln 5+\ln x$. The trap is $(\ln(x^2))'=1/x^2$.",
      r"$(\ln(5x))'$.", r"$1/x$ for $x>0$.",
      r"$(\ln|3x-1|)'$.", r"$3/(3x-1)$.")
    a(229, r"$(\sin x)'=\cos x$, $(\cos x)'=-\sin x$, in radians. Higher derivatives cycle every $4$. Chain: $(\sin u)'=u'\cos u$.",
      r"Differentiate $\sin(3x)\cos x$.",
      r"$3\cos(3x)\cos x-\sin(3x)\sin x$.",
      r"$(\cos(x^2))'$", r"$-2x\sin(x^2)$.",
      r"Degrees; or $(\cos x)'=\sin x$ without the minus.",
      r"$(\sin 5x)'$.", r"$5\cos 5x$.",
      r"$(\sin x)^{(4)}$.", r"$\sin x$.")
    a(230, r"$(\tan x)'=\sec^2 x$, $(\cot x)'=-\csc^2 x$, off their poles. Proof: quotient of sin/cos.",
      r"Differentiate $\tan(2x)$.",
      r"$2\sec^2(2x)$.",
      r"$(\cot x)'$ at $x=\pi/4$", r"$-2$ because $\csc(\pi/4)=\sqrt{2}$, squared $2$, minus.",
      r"Writing $(\tan x)'=\sec x$.",
      r"$(\tan x-\cot x)'$.", r"$\sec^2 x+\csc^2 x$.",
      r"Domain issue: is $\tan x$ differentiable at $\pi/2$?", r"No, not even defined.")
    a(231, r"$(\sec x)'=\sec x\tan x$, $(\csc x)'=-\csc x\cot x$. Proof: $1/\cos$ and $1/\sin$ with quotient/chain.",
      r"Differentiate $\sec(x^2)$.",
      r"$2x\sec(x^2)\tan(x^2)$.",
      r"$(\csc 3x)'$", r"$-3\csc(3x)\cot(3x)$.",
      r"Dropping the $\sec$ or $\csc$ factor and keeping only tan/cot.",
      r"$(\sec x+\csc x)'$.", r"$\sec x\tan x-\csc x\cot x$.",
      r"Evaluate $(\sec x)'$ at $0$.", r"$0$ because $\tan 0=0$.")
    a(232, r"$(\arcsin x)'=1/\sqrt{1-x^2}$, $(\arccos x)'=-1/\sqrt{1-x^2}$, $(\arctan x)'=1/(1+x^2)$, on the interiors of the principal domains. $(\mathrm{arcsec}\, x)'=1/(|x|\sqrt{x^2-1})$.",
      r"Differentiate $\arctan(3x)$.",
      r"$\dfrac{3}{1+9x^2}$.",
      r"$(\arcsin x+\arccos x)'$", r"$0$ on $(-1,1)$, matching constant $\pi/2$.",
      r"Dropping the chain-rule factor, or using $\sqrt{x^2-1}$ without $|x|$ for arcsec.",
      r"$(\arcsin(x^2))'$.", r"$\dfrac{2x}{\sqrt{1-x^4}}$.",
      r"$(\arctan x)'$ at $1$.", r"$1/2$.")
    a(233, r"Hyperbolic: $\sinh x=(e^x-e^{-x})/2$, $\cosh x=(e^x+e^{-x})/2$, $\tanh=\sinh/\cosh$. Then $(\sinh x)'=\cosh x$, $(\cosh x)'=\sinh x$, $(\tanh x)'=\mathrm{sech}^2 x$. Identity: $\cosh^2-\sinh^2=1$.",
      r"Differentiate $\cosh(2x)$.",
      r"$2\sinh(2x)$.",
      r"$(\sinh x)'$ at $0$", r"$\cosh 0=1$.",
      r"Copying trig signs: thinking $(\cosh)'=-\sinh$.",
      r"$(\tanh x)'$ at $0$.", r"$1$.",
      r"Show $\cosh^2 x-\sinh^2 x=1$.", r"Direct from the exponential definitions.")

    # E applications of derivatives
    a(234, r"A critical point of $f$ is an interior point $c$ of the domain where $f'(c)=0$ or $f'(c)$ does not exist. Candidates for local extrema among interior points are critical. Endpoints of a closed interval are additional candidates for absolute extrema.",
      r"Critical points of $f(x)=x^{2/3}$ on $\mathbb{R}$.",
      r"$f'(x)=\frac{2}{3}x^{-1/3}$ DNE at $0$, never $0$. Only $x=0$.",
      r"$f(x)=x^3$, critical points", r"$x=0$ only ($f'=3x^2$). Not a local extremum.",
      r"Ignoring points where $f'$ DNE (corners, cusps).",
      r"Critical points of $x^3-3x$.", r"$f'=3x^2-3=0$, $x=\pm 1$.",
      r"Is an endpoint of $[0,1]$ a critical point of $x$?", r"Usually we do not call it critical; it is still an EVT candidate.")
    a(235, r"A local (relative) maximum at $c$ means $f(x)\le f(c)$ for all $x$ in some neighborhood of $c$ in the domain. Fermat: if a local extremum occurs at an interior point where $f'$ exists, then $f'(c)=0$. First/second derivative tests classify.",
      r"Classify the critical point of $f(x)=-x^2$ at $0$.",
      r"Local (and global) maximum, $f'(0)=0$, $f''(0)=-2<0$.",
      r"$x^3$ at $0$", r"Critical but not a local extremum (sign of $f'$ does not change).",
      r"Concluding a local max from $f'(c)=0$ alone.",
      r"Local extrema of $x^4$.", r"Min at $0$.",
      r"Can a local max occur where $f'$ DNE?", r"Yes: $-|x|$ at $0$.")
    a(236, r"An absolute (global) maximum on a set $S$ is a point $c\in S$ with $f(x)\le f(c)$ for all $x\in S$. On a closed bounded interval, check critical points and endpoints (EVT). On $\mathbb{R}$, check $\lim_{\pm\infty}$ as well.",
      r"Absolute extrema of $f(x)=x^3-3x$ on $[-2,2]$.",
      r"$f' =3(x^2-1)$, critical $\pm 1$. Values: $f(-2)=-2$, $f(-1)=2$, $f(1)=-2$, $f(2)=2$. Abs max $2$, abs min $-2$.",
      r"$e^{-x^2}$ on $\mathbb{R}$", r"Abs max $1$ at $0$; no abs min (approaches $0$).",
      r"Reporting a local max as the absolute max without checking endpoints.",
      r"Abs min of $x+\frac{1}{x}$ on $(0,\infty)$.", r"$2$ at $x=1$.",
      r"Does $x$ on $\mathbb{R}$ have an absolute max?", r"No.")
    a(237, r"First derivative test: if $f'$ changes from $+$ to $-$ at $c$, local max; $-$ to $+$, local min; no sign change, neither. Requires $f$ continuous at $c$ and differentiable on a punctured neighborhood.",
      r"Classify $x=0$ for $f(x)=x^4$.",
      r"$f'=4x^3$: $-$ to $+$ , local min.",
      r"$f(x)=x^3$ at $0$", r"$f'=3x^2\ge 0$ both sides: not an extremum.",
      r"Using the test when $f'$ does not exist on one side and you did not check the definition of local extremum.",
      r"$f(x)=|x|$, first derivative test at $0$.", r"Left $f'=-1$, right $+1$: local min.",
      r"$f(x)=-x^4$ at $0$.", r"$+$ to $-$ wait: $f'=-4x^3$, left positive, right negative: local max.")
    a(238, r"Second derivative test: if $f'(c)=0$ and $f''(c)>0$, local min; $f''(c)<0$, local max; $f''(c)=0$, test inconclusive ($x^4$, $-x^4$, $x^3$).",
      r"Classify critical points of $f(x)=x^3-3x$.",
      r"$f''=6x$. At $x=1$, $f''>0$ local min; at $x=-1$, $f''<0$ local max.",
      r"$f(x)=x^4$ at $0$", r"$f'(0)=f''(0)=0$, inconclusive; first-derivative test says min.",
      r"Declaring “inflection” whenever $f''(c)=0$.",
      r"$f(x)=\cos x$ at $0$.", r"$f'=-\sin$, $f'(0)=0$, $f''=-\cos$, $f''(0)=-1$: local max.",
      r"If $f''(c)=0$ and $f'''(c)\neq 0$, typically", r"neither max nor min (like $x^3$).")
    a(239, r"$f$ is increasing on an interval $I$ if $x_1<x_2$ implies $f(x_1)\le f(x_2)$ (strictly if $<$). If $f'>0$ on $I$, $f$ is strictly increasing (MVT). If $f'\ge 0$, $f$ is increasing, but $f'$ can vanish at isolated points ($x^3$).",
      r"Where is $f(x)=x^3-3x$ increasing?",
      r"$f'=3(x^2-1)>0$ for $|x|>1$, so on $(-\infty,-1]$ and $[1,\infty)$ in the non-strict sense of joining the critical points; strictly increasing on each of $(-\infty,-1]$ and $[1,\infty)$.",
      r"$e^{-x}$ is", r"strictly decreasing on $\mathbb{R}$.",
      r"Concluding increasing from $f'(a)>0$ at a single point.",
      r"Where is $x^2$ decreasing?", r"On $(-\infty,0]$.",
      r"Can $f'=0$ everywhere on a subinterval while $f$ is increasing?", r"Then $f$ is constant there, so not strictly increasing.")
    a(240, r"$f$ is concave up on $I$ if $f'$ is increasing on $I$ (graph lies above tangents, for twice differentiable functions). If $f''>0$, concave up; $f''<0$, concave down. Concavity is about the bending, not about $f>0$.",
      r"Concavity of $f(x)=x^3$.",
      r"$f''=6x$: down on $(-\infty,0)$, up on $(0,\infty)$.",
      r"$e^x$ is", r"concave up everywhere.",
      r"Calling $x^2$ concave down because it has a minimum.",
      r"Where is $\sin x$ concave down on $[0,2\pi]$?", r"Where $-\sin x<0$, i.e. $\sin x>0$: $(0,\pi)$.",
      r"Does $f''=0$ at a point imply a concavity change?", r"No: $x^4$ has $f''(0)=0$ and stays concave up.")
    a(241, r"An inflection point is a point on the graph where concavity changes (and typically the tangent exists). A necessary condition if $f''$ exists nearby: $f''(c)=0$ or DNE, but not sufficient.",
      r"Inflection of $f(x)=x^3$.",
      r"$(0,0)$: $f''$ changes $-$ to $+$.",
      r"$x^4$ at $0$", r"Not inflection: $f''=12x^2$ does not change sign.",
      r"Every zero of $f''$ is an inflection point.",
      r"$f(x)=\sin x$, inflections on $[0,2\pi]$.", r"$x=0,\pi,2\pi$ (endpoints of the interval if included; $f''=-\sin$ changes at $0,\pi,2\pi$).",
      r"Can inflection occur where $f''$ DNE?", r"Yes: $x^{1/3}$ at $0$.")
    a(242, r"Curve sketching combines: domain, intercepts, asymptotes (limits), first-derivative chart (inc/dec, local extrema), second-derivative chart (concavity, inflections), and a consistent picture. The GRE often asks only one of these layers.",
      r"Sketch features of $f(x)=\dfrac{x}{x-1}$.",
      r"Vertical asymptote $x=1$, horizontal $y=1$, intercept $(0,0)$, $f'=-1/(x-1)^2<0$ always decreasing on each component.",
      r"End behavior of a cubic with positive leading coefficient", r"$+\infty$ as $x\to+\infty$, $-\infty$ as $x\to-\infty$.",
      r"Drawing a graph that crosses a vertical asymptote.",
      r"Does $e^{-x^2}$ have horizontal asymptotes?", r"$y=0$ both sides.",
      r"A rational function of equal degree has horizontal asymptote", r"the ratio of leading coefficients.")
    a(243, r"Optimization: translate the story into $f(x)$ on a domain, find absolute extrema. Use constraint to reduce to one variable. Check endpoints and critical points. Units and whether a max or min is physically attained.",
      r"Maximize $xy$ subject to $x+y=10$, $x,y\ge 0$.",
      r"$y=10-x$, $f=x(10-x)$, $f'=10-2x=0$, $x=5$, $y=5$, max $25$. Endpoints $0$.",
      r"A rectangle of perimeter $20$ of maximal area is", r"a square of side $5$.",
      r"Critical point outside the domain; or maximizing a square when the problem asked for a minimum cost.",
      r"Min of $x^2+y^2$ on $x+y=1$.", r"$x=y=1/2$, value $1/2$.",
      r"Open domain $(0,\infty)$: $f(x)=x+1/x$ min?", r"Yes, $2$ at $x=1$; as $x\to 0^+$ or $\infty$, $f\to\infty$.")
    a(244, r"Related rates: if two quantities are related by an equation for all $t$, differentiate in $t$ using the chain rule, then plug in the instant asked. Draw a picture, name variables, state what is given ($dx/dt$) and asked ($dy/dt$).",
      r"A circle's radius increases at $2$ cm/s. How fast is area increasing when $r=3$?",
      r"$A=\pi r^2$, $dA/dt=2\pi r\, dr/dt=2\pi\cdot 3\cdot 2=12\pi$ cm$^2$/s.",
      r"Ladder $10$ ft, base $6$ ft from wall sliding at $1$ ft/s. Height rate?", r"$x^2+y^2=100$, $2x x'+2y y'=0$, $y=8$, $y'=-6/8=-3/4$ ft/s.",
      r"Plugging the instant into the constraint before differentiating (freezing a variable that is changing).",
      r"Cube edge $x$ growing at $1$ in/s, $dV/dt$ when $x=2$.", r"$V=x^3$, $3x^2=12$ in$^3$/s.",
      r"Similar triangles in a related-rates shadow problem: differentiate", r"the proportion, not just the similar-triangle equality frozen.")
    a(245, r"An implicit curve $F(x,y)=0$ is analyzed by implicit $y'$, locating points where $y'=0$ (horizontal tangent) or where the denominator vanishes (vertical tangent, if numerator $\neq 0$). Intersections with axes and symmetry help.",
      r"Horizontal tangents of $x^2+y^2+xy=3$.",
      r"$2x+2y y'+y+x y'=0$, $y'(2y+x)=-(2x+y)$, so $y'=0$ when $2x+y=0$ and $2y+x\neq 0$. Substitute $y=-2x$ into the curve.",
      r"The folium $x^3+y^3=3xy$ at the origin", r"A double point / self-crossing; two tangent directions.",
      r"Setting $dy/dx=0$ without using the original equation to find the points.",
      r"Vertical tangents of $x^2+y^2=1$.", r"$x=\pm 1$ ($y=0$).",
      r"Can an implicit curve fail the vertical-line test?", r"Yes: it is not the graph of a single $y(x)$.")
    a(246, r"For $x=x(t)$, $y=y(t)$, $\dfrac{dy}{dx}=\dfrac{y'(t)}{x'(t)}$ when $x'(t)\neq 0$. $\dfrac{d^2 y}{dx^2}=\dfrac{d}{dt}(dy/dx)\big/ x'(t)$. Speed is $\sqrt{x'^2+y'^2}$, not $dy/dx$.",
      r"For $x=\cos t$, $y=\sin t$, $dy/dx$.",
      r"$y'/x'=\cos t/(-\sin t)=-\cot t$, matching $-x/y$ on the circle.",
      r"When $x'(t)=0$ and $y'(t)\neq 0$", r"Vertical tangent in the $xy$-plane.",
      r"Confusing $dy/dx$ with $dy/dt$.",
      r"Second derivative for $x=t^2$, $y=t^3$ at $t=1$.", r"$dy/dx=3t/2$, $\frac{d}{dt}(3t/2)/ (2t)=3/4$ at $t=1$? Wait: $d^2y/dx^2=\frac{3/2}{2t}=3/(4t)$, at $t=1$ is $3/4$.",
      r"Parametric speed of $(\cos t,\sin t)$.", r"$1$.")
    a(247, r"Linear approximation: $f(x)\approx f(a)+f'(a)(x-a)$ for $x$ near $a$. This is the tangent line. Useful for GRE mental estimates: $\sqrt{4.1}$, $\sin(0.1)$, etc.",
      r"Approximate $\sqrt{9.2}$ using $a=9$.",
      r"$f=x^{1/2}$, $f'=1/(2\sqrt{x})$, $3+\frac{1}{6}\cdot 0.2=3.033\ldots$.",
      r"$\sin(0.1)\approx$", r"$0.1$ (using $a=0$).",
      r"Using a linearization far from $a$ and treating it as exact.",
      r"$e^{0.1}\approx$.", r"$1.1$.",
      r"Linearization of $1/x$ at $a=1$.", r"$2-x$.")
    a(248, r"The differential $df=f'(x)\,dx$ estimates $\Delta f$. Relative error $|\Delta f/f|$; percentage $100$ times that. For products, logarithmic differentials add relative errors.",
      r"If $x=2$ with possible error $0.01$, estimate error in $x^3$.",
      r"$d(x^3)=3x^2 dx=12\cdot 0.01=0.12$.",
      r"Relative error in $A=\pi r^2$ is", r"$2\,|dr/r|$.",
      r"Adding absolute errors of factors instead of relative errors for a product.",
      r"$f=1/x$ at $x=10$, $dx=0.1$, $df$.", r"$-0.1/100=-0.001$.",
      r"If all sides of a cube are $2\%$ high, volume is about", r"$6\%$ high (three relative errors).")
    a(249, r"MVT: if $f$ is continuous on $[a,b]$ and differentiable on $(a,b)$, then some $c\in(a,b)$ has $f'(c)=\dfrac{f(b)-f(a)}{b-a}$. Mean slope is a tangent slope. Hypotheses matter: $|x|$ on $[-1,1]$ fails differentiability at $0$ and MVT fails for the two-sided slope $0$.",
      r"Apply MVT to $f(x)=x^2$ on $[1,3]$.",
      r"$f'(c)=2c=(9-1)/2=4$, $c=2$.",
      r"Why MVT implies $f'=0\Rightarrow f$ constant on an interval", r"For $x_1<x_2$, $f(x_2)-f(x_1)=f'(c)(x_2-x_1)=0$.",
      r"Using MVT when $f$ is not differentiable on the whole open interval.",
      r"Does there exist $c\in(0,1)$ with $e^c=e-1$?", r"MVT on $e^x$ on $[0,1]$: $e^c=e-1$, yes $c=\ln(e-1)$.",
      r"$f(x)=x^{1/3}$ on $[-1,1]$: MVT?", r"Not in the finite-derivative sense: $f'(0)$ infinite. Average slope $0$, no finite $c$ with $f'(c)=0$.")
    a(250, r"Rolle: if $f$ is continuous on $[a,b]$, differentiable on $(a,b)$, and $f(a)=f(b)$, then some $c\in(a,b)$ has $f'(c)=0$. Special case of MVT. Used to prove uniqueness of roots: between two roots of $f$ lies a root of $f'$.",
      r"Show $x^2-1=0$ has a point with $f'=0$ in $(-1,1)$.",
      r"$f(-1)=f(1)=0$, Rolle, $f'=2x=0$ at $0$.",
      r"Can $x^3-x-1$ have two real roots?", r"If two roots, Rolle gives $f'=0$ i.e. $3x^2-1=0$, $x=\pm 1/\sqrt{3}$. Checking values shows only one sign change of $f$: one real root.",
      r"Applying Rolle without $f(a)=f(b)$.",
      r"$f(x)=\sin x$ on $[0,\pi]$. Rolle point?", r"$x=\pi/2$.",
      r"If $f'$ has no zero, $f$ has at most how many zeros?", r"One (Rolle contrapositive).")

    # E Taylor
    a(251, r"The Taylor polynomial of degree $n$ for $f$ at $a$ is $P_n(x)=\sum_{k=0}^n \dfrac{f^{(k)}(a)}{k!}(x-a)^k$. It is the unique degree $\le n$ polynomial matching $f$ and its first $n$ derivatives at $a$.",
      r"$P_2$ for $e^x$ at $0$.",
      r"$1+x+x^2/2$.",
      r"$P_1$ is exactly", r"the linearization $f(a)+f'(a)(x-a)$.",
      r"Forgetting $k!$ in the coefficients.",
      r"$P_2$ for $\sin x$ at $0$.", r"$x$ (even part vanishes; $P_2=P_1$).",
      r"$P_2$ for $\ln(1+x)$ at $0$.", r"$x-x^2/2$.")
    a(252, r"A Maclaurin polynomial is a Taylor polynomial at $a=0$: $P_n(x)=\sum_{k=0}^n f^{(k)}(0)\, x^k/k!$. Standard Maclaurin polynomials should be memorized: $e^x$, $\sin x$, $\cos x$, $1/(1-x)$, $\ln(1+x)$.",
      r"Maclaurin $P_3$ of $\cos x$.",
      r"$1-x^2/2$ (odd terms vanish; the $x^3$ term is $0$).",
      r"Maclaurin $P_3$ of $\sin x$", r"$x-x^3/6$.",
      r"Expanding $\cos$ with a $x$ term.",
      r"Maclaurin $P_n$ of a polynomial of degree $n$.", r"The polynomial itself.",
      r"$P_2$ of $1/(1-x)$ at $0$.", r"$1+x+x^2$.")
    a(253, r"Lagrange remainder: $f(x)=P_n(x)+R_n(x)$ with $R_n(x)=\dfrac{f^{(n+1)}(c)}{(n+1)!}(x-a)^{n+1}$ for some $c$ between $a$ and $x$. Bounding $|f^{(n+1)}|$ bounds the error.",
      r"Bound the error of $P_1$ for $e^x$ at $0$ on $[0,1]$.",
      r"$R_1=e^c x^2/2$, $|R_1|\le e/2$ on $[0,1]$. Sharper: $e^x\le e$.",
      r"If $|f^{(n+1)}|\le M$, $|R_n(x)|\le$", r"$M|x-a|^{n+1}/(n+1)!$.",
      r"Thinking the remainder is the next Taylor term exactly (it is that term at a mystery $c$).",
      r"Does $R_n(a)=0$?", r"Yes.",
      r"For $\sin x$, $|R_3(x)|$ near $0$ is $O($?", r"$|x|^5$ because the degree-$4$ term vanishes too; Lagrange with $n=3$ gives $O(x^4)$, but the next nonzero is $x^5$.")
    a(254, r"Local approximation: near $a$, $f(x)=f(a)+f'(a)(x-a)+\frac12 f''(a)(x-a)^2+o((x-a)^2)$ if $f''$ is continuous. The quadratic Taylor polynomial is the best parabolic fit at $a$. Used to read local min/max from the second-degree term.",
      r"Local shape of $\cos x$ near $0$.",
      r"$1-x^2/2+\cdots$: a downward parabola, local max.",
      r"$e^x$ near $0$ vs $1+x$", r"The next term $x^2/2>0$ so $e^x$ lies above its tangent.",
      r"Using a global identity when the question only needs local behavior.",
      r"Local approximation of $\sqrt{1+h}$ for small $h$.", r"$1+h/2-h^2/8+\cdots$.",
      r"Why does $f''(a)>0$ give a local min?", r"The quadratic term $\frac12 f''(a)(x-a)^2$ dominates and is positive.")
    a(255, r"Little-o and big-O for errors: $f(x)=P_n(x)+O((x-a)^{n+1})$ as $x\to a$ if $f^{(n+1)}$ is bounded near $a$. $o((x-a)^n)$ is smaller than the last kept term. GRE limits are often Taylor with $O(x^k)$ bookkeeping.",
      r"As $x\to 0$, $\sin x=x-\dfrac{x^3}{6}+O(x^5)$. Then $\dfrac{\sin x-x}{x^3}\to$?",
      r"$-1/6$.",
      r"$1-\cos x=O(?)$ as $x\to 0$", r"$O(x^2)$.",
      r"Writing $O(x^2)+O(x^3)=O(x^5)$.",
      r"$\ln(1+x)=x+O(x^2)$ implies $\dfrac{\ln(1+x)}{x}\to$?", r"$1$.",
      r"Is $x^2=o(x)$ as $x\to 0$?", r"Yes. As $x\to\infty$, no.")
    a(256, r"To evaluate a limit, replace each function by its Taylor expansion to the first order that does not cancel, then simplify. This is L'Hôpital with bookkeeping. Standard replacements: $\sin x=x-x^3/6+O(x^5)$, $e^x=1+x+x^2/2+O(x^3)$, $\ln(1+x)=x-x^2/2+O(x^3)$.",
      r"$\lim_{x\to 0}\dfrac{e^x-1-x}{x^2}$.",
      r"$e^x=1+x+x^2/2+O(x^3)$, numerator $x^2/2+O(x^3)$, limit $1/2$.",
      r"$\lim_{x\to 0}\dfrac{1-\cos x}{x\sin x}$", r"$(x^2/2+O(x^4))/(x\cdot x+O(x^3))=1/2$.",
      r"Expanding numerator to order $1$ when the first two orders cancel.",
      r"$\lim_{x\to 0}\dfrac{\tan x-x}{x^3}$.", r"$1/3$ (use $\tan x=x+x^3/3+O(x^5)$).",
      r"Why is Taylor often faster than three L'Hôpitals?", r"You see the first surviving degree in one line.")

    return F
