"""Unique facts M-756 through M-868."""

from __future__ import annotations


def facts() -> dict[int, dict]:
    F: dict[int, dict] = {}

    def a(n, stmt, exq, exa, gq, ga, trap, q1, a1, q2, a2):
        F[n] = dict(stmt=stmt, exq=exq, exa=exa, gq=gq, ga=ga, trap=trap, q1=q1, a1=a1, q2=q2, a2=a2)

    # R counting principles 756-765
    a(756, r"Addition principle: if $A_1,\ldots,A_m$ are pairwise disjoint finite sets, then $\bigl|\bigcup_i A_i\bigr|=\sum_i|A_i|$. Equivalently, if a task can be done in one of $m$ mutually exclusive types, add the number of ways of each type. Overlapping types need inclusion-exclusion, not raw addition.",
      r"A menu has $17$ vegetarian plates, $11$ fish plates, and $8$ steak plates, all distinct. How many ways to choose one plate?",
      r"The collections are disjoint, so $17+11+8=36$.",
      r"From $\{1,\ldots,20\}$, integers that are even or (exclusively) odd: how many?",
      r"$10+10=20$, the whole set; even and odd partition.",
      r"Adding $|A|$ and $|B|$ when $A\cap B\neq\emptyset$ double-counts the overlap.",
      r"A password is either a $3$-digit string from $\{0,\ldots,9\}$ or a $2$-letter string from $\{A,B,C,D\}$. How many passwords?",
      r"$10^3+4^2=1000+16=1016$.",
      r"How many integers in $\{1,\ldots,30\}$ are divisible by $2$ or by $5$?",
      r"Not $15+6=21$: overlap of multiples of $10$. Correct: $15+6-3=18$.")
    a(757, r"Multiplication principle: if a procedure is a sequence of $k$ independent stages with $n_i$ choices at stage $i$, there are $n_1 n_2\cdots n_k$ outcomes. Independence here means the number of options at stage $i$ does not depend on previous choices (the labels of the options may).",
      r"A sundae: $6$ ice-cream flavors, $4$ sauces, $3$ toppings. How many sundaes if one of each is chosen?",
      r"$6\cdot 4\cdot 3=72$.",
      r"License plates: $2$ letters then $3$ digits, repetition allowed. Count.",
      r"$26^2\cdot 10^3=676000$.",
      r"Multiplying after an either/or split, or treating dependent later-stage counts as constant.",
      r"From $8$ distinct books, in how many ways can you line up $3$ of them on a shelf?",
      r"$8\cdot 7\cdot 6=336$ (order matters).",
      r"A $4$-digit PIN with no repeated digits, first digit nonzero. Count.",
      r"$9\cdot 9\cdot 8\cdot 7=4536$ (second digit may be $0$, so $9$ choices remain after using one of $1$--$9$).")
    a(758, r"$n!=n(n-1)\cdots 1$ for $n\ge 1$, and $0!=1$ by empty product (so $\binom{n}{0}=1$ and $P(n,n)=n!$). Recursively $n!=n\cdot(n-1)!$. $n!$ counts permutations of $n$ distinct objects.",
      r"Compute $7!$ and $9!/6!$.",
      r"$7!=5040$. $9!/6!=9\cdot 8\cdot 7=504$.",
      r"$0!+1!+2!+3!$ equals",
      r"$1+1+2+6=10$.",
      r"Declaring $0!$ undefined, or writing $n!/(n-k)!=(n-k)!$.",
      r"Simplify $\dfrac{8!}{5!\,3!}$.",
      r"$\dfrac{8\cdot 7\cdot 6}{6}=56$.",
      r"How many ways to seat $5$ distinct people in $5$ labeled chairs?",
      r"$5!=120$.")
    a(759, r"A $k$-permutation of $n$ distinct objects is an ordered selection of $k$ of them: $P(n,k)=n!/(n-k)! = n(n-1)\cdots(n-k+1)$ for $0\le k\le n$. Order matters; repetition is forbidden.",
      r"Compute $P(9,4)$.",
      r"$9\cdot 8\cdot 7\cdot 6=3024$.",
      r"$P(11,3)$ equals",
      r"$11\cdot 10\cdot 9=990$.",
      r"Using $\binom{n}{k}$ when the problem ranks or sequences the chosen objects.",
      r"How many $3$-letter codes from $26$ letters, no repeats, order matters?",
      r"$P(26,3)=26\cdot 25\cdot 24=15600$.",
      r"$P(n,1)$ and $P(n,n)$ in closed form.",
      r"$n$ and $n!$.")
    a(760, r"A $k$-combination of $n$ distinct objects is an unordered subset of size $k$: $\binom{n}{k}=n!/(k!\,(n-k)!)=P(n,k)/k!$. Order does not matter. $\binom{n}{k}=0$ for $k>n$ or $k<0$ (usual convention).",
      r"Compute $\binom{14}{3}$.",
      r"$\dfrac{14\cdot 13\cdot 12}{6}=364$.",
      r"A committee of $4$ from $13$ people: how many?",
      r"$\binom{13}{4}=715$.",
      r"Forgetting to divide by $k!$ after forming an ordered list, doubling a round table, or using $n^k$.",
      r"$\binom{10}{2}$ equals",
      r"$45$.",
      r"You choose $5$ cards from $12$ distinct cards. Ordered vs unordered counts?",
      r"$P(12,5)=12\cdot 11\cdot 10\cdot 9\cdot 8=95040$ ordered; $\binom{12}{5}=792$ unordered.")
    a(761, r"Binomial coefficients $\binom{n}{k}$ satisfy $\binom{n}{k}=\binom{n}{n-k}$, $\binom{n}{0}=\binom{n}{n}=1$, and $\binom{n}{1}=n$. They count $k$-subsets and appear as coefficients in $(x+y)^n$. Pascal's triangle is their table.",
      r"Compute $\binom{16}{3}$ and check $\binom{16}{13}$.",
      r"$\binom{16}{3}=560=\binom{16}{13}$.",
      r"$\binom{n}{2}$ equals",
      r"$\dfrac{n(n-1)}{2}$, the number of edges of $K_n$.",
      r"Writing $\binom{n}{k}=n!/k!$ (dropping $(n-k)!$), or claiming $\binom{n}{k}$ is defined only for $k\le n/2$.",
      r"Evaluate $\binom{15}{5}$.",
      r"$3003$.",
      r"Why is $\binom{8}{3}=\binom{8}{5}$ combinatorially?",
      r"Choosing $3$ to include is choosing $5$ to exclude.")
    a(762, r"The multinomial coefficient $\dbinom{n}{n_1,\ldots,n_r}=\dfrac{n!}{n_1!\cdots n_r!}$ with $n_1+\cdots+n_r=n$ counts: partitions of $n$ distinct objects into labeled groups of those sizes; and distinct words with letter frequencies $n_i$. It is $\binom{n}{n_1}\binom{n-n_1}{n_2}\cdots$.",
      r"How many distinct rearrangements of the letters in PEPPER?",
      r"$6$ letters, frequencies $3,2,1$: $6!/(3!\,2!\,1!)=60$.",
      r"Distribute $12$ distinct books into labeled boxes of sizes $5,4,3$. Count.",
      r"$12!/(5!\,4!\,3!)=27720$.",
      r"Treating the groups as unlabeled when they have equal size (must divide by the symmetry of those groups), or using $\binom{n}{r}$ for more than two types.",
      r"Coefficient of $x^2 y^3 z$ in $(x+y+z)^6$.",
      r"$\dbinom{6}{2,3,1}=60$.",
      r"Distinct permutations of MISSISSIPPI.",
      r"$11!/(4!\,4!\,2!\,1!)=34650$.")
    a(763, r"With repetition allowed and order mattering, there are $n^k$ words of length $k$ on an $n$-letter alphabet (functions $[k]\to[n]$). Without repetition: $P(n,k)$. Unordered with repetition (multisets) is stars-and-bars, not $n^k$.",
      r"How many $4$-letter strings from $\{A,B,C,D,E,F,G\}$, letters reusable?",
      r"$7^4=2401$.",
      r"$3$-digit numbers with digits from $0$--$9$, repetition allowed, leading zeros allowed as strings: count.",
      r"$10^3=1000$. As integers $000$ through $999$.",
      r"Using $\binom{n+k-1}{k}$ when the problem is ordered (PIN codes, sequences).",
      r"Binary strings of length $8$.",
      r"$2^8=256$.",
      r"Passwords of length $5$ from $12$ symbols, no repeat vs repeat.",
      r"$P(12,5)=12\cdot 11\cdot 10\cdot 9\cdot 8=95040$ vs $12^5=248832$.")
    a(764, r"Circular permutations of $n$ distinct objects: two linear arrangements that differ by a rotation represent the same seating, so there are $(n-1)!$ ways up to rotation. If reflections are identified (necklace that can flip), there are $(n-1)!/2$ for $n\ge 3$ with no symmetry leftover.",
      r"How many ways to seat $10$ distinct people around a round table, rotations the same, reflections different?",
      r"$(10-1)! =9!=362880$.",
      r"$7$ distinct beads on a necklace that may be flipped. Count.",
      r"$(7-1)!/2=360$.",
      r"Using $n!$ for a round table, or dividing by $2n$ when flips are not allowed.",
      r"Seat $5$ people around a table with one seat marked `head'. Count.",
      r"The mark breaks rotational symmetry: $5!=120$.",
      r"Arrangements of $6$ distinct cards in a circle, rotations same. Count.",
      r"$5!=120$.")
    a(765, r"Counting by complement: $|S\setminus A|=|S|-|A|$. Use when `at least one' or `not all' is messier than the forbidden set. Combine with inclusion-exclusion when the bad set is a union.",
      r"How many length-$6$ binary strings are not the zero string?",
      r"$2^6-1=63$.",
      r"From $\binom{9}{4}$ $4$-subsets of $\{1,\ldots,9\}$, how many contain at least one even? (evens: $2,4,6,8$).",
      r"Complement: subsets of the $5$ odds: $\binom{9}{4}-\binom{5}{4}=126-5=121$.",
      r"Subtracting only one bad type when several bad types overlap, or subtracting from the wrong universe.",
      r"Positive integers $\le 100$ not divisible by $7$.",
      r"$100-\lfloor 100/7\rfloor=100-14=86$.",
      r"$5$-letter words from $\{A,B,C\}$ that use at least two distinct letters.",
      r"$3^5-3=243-3=240$ (subtract the three constant words).")

    # R combinatorial identities 766-774
    a(766, r"Pascal's identity: $\binom{n}{k}=\binom{n-1}{k}+\binom{n-1}{k-1}$ for $n\ge k\ge 1$. Combinatorially: among $n$-sets, either $n$ is omitted ($\binom{n-1}{k}$) or included ($\binom{n-1}{k-1}$). This is the recurrence of Pascal's triangle.",
      r"Check $\binom{13}{5}=\binom{12}{5}+\binom{12}{4}$.",
      r"$1287=792+495$.",
      r"$\binom{8}{3}$ via Pascal from row $7$.",
      r"$\binom{7}{3}+\binom{7}{2}=35+21=56$.",
      r"Adding $\binom{n}{k}+\binom{n}{k}$ or shifting the lower index the wrong way: $\binom{n}{k}\neq\binom{n-1}{k}+\binom{n-1}{k}$.",
      r"Compute $\binom{11}{4}$ from $\binom{10}{4}$ and $\binom{10}{3}$.",
      r"$210+120=330$.",
      r"Iterate Pascal to write $\binom{6}{2}$ as a sum of $\binom{i}{1}$.",
      r"Hockey-stick $\sum_{i=1}^{5}\binom{i}{1}=\binom{6}{2}=15$, i.e. $1+2+3+4+5=15$.")
    a(767, r"Binomial theorem: $(x+y)^n=\sum_{k=0}^{n}\binom{n}{k}x^{n-k}y^k$. Special cases: $(1+1)^n=2^n=\sum\binom{n}{k}$, $(1-1)^n=0=\sum(-1)^k\binom{n}{k}$ for $n>0$, and $(1+x)^n$ generates $\binom{n}{k}$.",
      r"Coefficient of $x^4$ in $(3+2x)^6$.",
      r"$\binom{6}{4}3^{2}(2)^4=15\cdot 9\cdot 16=2160$.",
      r"Expand $(1-1)^5$ as a binomial sum. What does it show?",
      r"$0=\sum_{k=0}^{5}(-1)^k\binom{5}{k}$; equal number of even- and odd-sized subsets, $16$ each.",
      r"Using $\binom{n}{k}x^k$ without the matching power of the other summand, or evaluating $(2+3)^n$ as $2^n+3^n$.",
      r"Coefficient of $x^3$ in $(1+x)^9$.",
      r"$\binom{9}{3}=84$.",
      r"Compute $\sum_{k=0}^{4}\binom{4}{k}2^k$.",
      r"$(1+2)^4=81$.")
    a(768, r"Vandermonde: $\sum_{j}\binom{m}{j}\binom{n}{r-j}=\binom{m+n}{r}$. Combinatorially: choose $r$ people from $m$ men and $n$ women. Algebraically it is the coefficient of $x^r$ in $(1+x)^m(1+x)^n=(1+x)^{m+n}$.",
      r"Choose $3$ from $4$ men and $6$ women. Expand by how many men are chosen and total.",
      r"$\binom{4}{0}\binom{6}{3}+\binom{4}{1}\binom{6}{2}+\binom{4}{2}\binom{6}{1}+\binom{4}{3}\binom{6}{0}=20+60+36+4=120=\binom{10}{3}$.",
      r"$\sum_{j}\binom{8}{j}\binom{5}{3-j}$ equals",
      r"$\binom{13}{3}=286$.",
      r"Summing $\binom{m}{j}\binom{n}{j}$ and calling it $\binom{m+n}{j}$ (that is a different, unsigned, identity only after extra factors).",
      r"Committee of $4$ from $7$ juniors and $5$ seniors. Number of committees with exactly $2$ juniors.",
      r"$\binom{7}{2}\binom{5}{2}=21\cdot 10=210$, one Vandermonde term.",
      r"Check $j=0$ to $2$ for $\sum\binom{3}{j}\binom{2}{2-j}$.",
      r"$\binom{3}{0}\binom{2}{2}+\binom{3}{1}\binom{2}{1}+\binom{3}{2}\binom{2}{0}=1+6+3=10=\binom{5}{2}$.")
    a(769, r"Stars and bars: the number of nonnegative integer solutions of $x_1+\cdots+x_k=n$ is $\binom{n+k-1}{k-1}=\binom{n+k-1}{n}$. For positive solutions $x_i\ge 1$, substitute $y_i=x_i-1$ to get $\binom{n-1}{k-1}$ provided $n\ge k$. Bounded variables need inclusion-exclusion on top.",
      r"Nonnegative solutions of $x+y+z+w=9$.",
      r"$\binom{9+4-1}{4-1}=\binom{12}{3}=220$.",
      r"Positive integer solutions of $x_1+x_2+x_3=7$.",
      r"$y_i=x_i-1\ge 0$, $y_1+y_2+y_3=4$, $\binom{4+2}{2}=\binom{6}{2}=15$.",
      r"Using $\binom{n+k-1}{k}$ with the wrong index, or applying the positive formula when zeros are allowed.",
      r"Number of multisets of size $6$ from $4$ types.",
      r"$\binom{6+4-1}{6}=\binom{9}{6}=84$.",
      r"Nonnegative solutions of $x+y+z=5$ with $x\ge 2$.",
      r"Set $x'=x-2$: $x'+y+z=3$, $\binom{3+2}{2}=\binom{5}{2}=10$.")
    a(770, r"Inclusion-exclusion: $\bigl|\bigcup_{i=1}^{n} A_i\bigr|=\sum|A_i|-\sum|A_i\cap A_j|+\sum|A_i\cap A_j\cap A_k|-\cdots+(-1)^{n+1}|A_1\cap\cdots\cap A_n|$. Two-set case: $|A\cup B|=|A|+|B|-|A\cap B|$.",
      r"$|A|=28$, $|B|=25$, $|C|=22$, $|A\cap B|=10$, $|A\cap C|=8$, $|B\cap C|=7$, $|A\cap B\cap C|=4$. Find $|A\cup B\cup C|$.",
      r"$28+25+22-10-8-7+4=54$.",
      r"Integers in $\{1,\ldots,60\}$ divisible by $2$ or $3$.",
      r"$\lfloor 60/2\rfloor+\lfloor 60/3\rfloor-\lfloor 60/6\rfloor=30+20-10=40$.",
      r"Stopping after subtracting pairwise intersections (the triple has been subtracted too often and must be added back).",
      r"$|A\cup B|$ if $|A|=47$, $|B|=31$, $|A\cap B|=12$.",
      r"$47+31-12=66$.",
      r"How many integers in $\{1,\ldots,100\}$ are not divisible by $2$, $3$, or $5$?",
      r"$100-(50+33+20)+(16+10+6)-3=100-103+32-3=26$.")
    a(771, r"Pigeonhole principle: if $n$ pigeons go into $m$ holes and $n>m$, some hole has at least two. Generalized: to guarantee at least $k+1$ in one hole, you need $mk+1$ pigeons. Equivalently $\lceil n/m\rceil$ is a lower bound on the fullest hole.",
      r"How many people are needed to guarantee two share a birthday month?",
      r"$13=12\cdot 1+1$.",
      r"With $8$ drawers, how many socks guarantee at least $4$ in one drawer?",
      r"$8\cdot 3+1=25$.",
      r"Using $mk$ instead of $mk+1$ for a guarantee (the worst case still has only $k$ per hole).",
      r"Among $37$ integers, why must two have the same residue mod $12$?",
      r"Already $13$ suffice. With $37$ one can say more: $\lceil 37/12\rceil=4$ in some residue class.",
      r"Five lattice points in $\{1,2,3\}^2$. Why two share an $x$-coordinate?",
      r"Only $3$ possible $x$-values; $5>3$.")
    a(772, r"Double counting: evaluate the same finite set of pairs (or flags) in two ways. The equality of the two expressions is an identity. Prototype: count pairs $(v,e)$ with $v$ incident to $e$ to get $\sum_v\deg v=2|E|$.",
      r"Count pairs (committee of $2$ from $n$ people, chair of that committee) two ways.",
      r"Choose the pair then the chair: $\binom{n}{2}\cdot 2$. Choose the chair then the other member: $n(n-1)$. Hence $n(n-1)=n(n-1)$.",
      r"Number of edges in $K_7$ by double counting degrees.",
      r"Each of $7$ vertices has degree $6$, sum $42$, so $|E|=21=\binom{7}{2}$.",
      r"Counting ordered pairs on one side and unordered pairs on the other without converting.",
      r"How many ways to choose a $3$-subset of $[10]$ and then an element of it?",
      r"$\binom{10}{3}\cdot 3=360= \binom{9}{2}\cdot 10$, since pick the element first ($10$) then $2$ companions from $9$.",
      r"Prove $\sum_{k} k\binom{n}{k}=n 2^{n-1}$ by double counting.",
      r"Left: choose a marked $k$-subset. Right: pick the marked element ($n$) then any subset of the rest ($2^{n-1}$).")
    a(773, r"A bijection $f:A\to B$ proves $|A|=|B|$. GRE counting often hides a bijection: subsets $\leftrightarrow$ binary strings, compositions of $n$ with $k$ parts $\leftrightarrow$ stars-and-bars, Dyck paths $\leftrightarrow$ valid parenthesis strings (Catalan).",
      r"Give a bijection between subsets of $\{1,2,3,4,5,6\}$ and binary strings of length $6$. How many?",
      r"Characteristic vector: $i$ is in the subset iff bit $i$ is $1$. Count $2^6=64$.",
      r"The Catalan number $C_4=\frac{1}{5}\binom{8}{4}$ counts what parentheses?",
      r"$C_4=14$ correctly matched strings of $4$ pairs.",
      r"Exhibiting an injection and claiming equal cardinality without a matching reverse map (or without Cantor–Bernstein when infinite).",
      r"Bijection between odd- and even-cardinality subsets of $[7]$ for nonempty universe.",
      r"Toggle membership of a fixed element, say $1$. Pairs them; $2^6=64$ of each type.",
      r"Number of functions $[5]\to\{0,1\}$ equals number of subsets of $[5]$ because",
      r"each function is a characteristic function; $32$.")
    a(774, r"Recurrence-based counting: let $a_n$ be the unknown count, condition on the first choice (or last cell), and obtain a relation such as $a_n=a_{n-1}+a_{n-2}$. Solve by unfolding, generating functions, or the characteristic equation, using small-$n$ base cases computed by hand.",
      r"Tile a $1\times n$ board with tiles of length $1$ and $2$. Let $a_n$ be the number of tilings. Recurrence and $a_6$.",
      r"$a_n=a_{n-1}+a_{n-2}$, $a_0=1$, $a_1=1$ (or $a_1=1$, $a_2=2$). Then $1,1,2,3,5,8,13$ so $a_6=13$.",
      r"Strings of length $n$ over $\{0,1\}$ with no two consecutive $1$s. Recurrence?",
      r"$b_n=b_{n-1}+b_{n-2}$: a valid string ending in $0$ is a valid $(n-1)$-string plus $0$; ending in $1$ must end in $01$. $b_1=2$, $b_2=3$.",
      r"Writing a recurrence without checking two base cases, so the sequence is shifted.",
      r"$a_n=2a_{n-1}$ with $a_0=3$. Closed form and $a_5$.",
      r"$a_n=3\cdot 2^n$, $a_5=96$.",
      r"Number of subsets of $[n]$ by recurrence.",
      r"$s_n=2s_{n-1}$, $s_0=1$, hence $2^n$: each subset of $[n-1]$ either gains $n$ or not.")

    # R advanced counting 775-780
    a(775, r"A derangement is a permutation with no fixed points. The number is $!n=n!\sum_{k=0}^{n}(-1)^k/k!$, equivalently $!n=(n-1)\bigl[!(n-1)+!(n-2)\bigr]$ with $!0=1$, $!1=0$. Also $!n$ is the nearest integer to $n!/e$.",
      r"Compute $!4$ and $!5$.",
      r"$!4=9$, $!5=44$. Check: $24(1-1+1/2-1/6+1/24)=24\cdot 9/24=9$; $120\cdot(1-1+1/2-1/6+1/24-1/120)=44$.",
      r"$!6$ equals",
      r"$265$.",
      r"Using $n!-1$ (that only removes the identity) or $n!/e$ without rounding, or counting permutations that fix at least one point as $n$.",
      r"Probability that a random permutation of $8$ letters is a derangement, to two decimals.",
      r"$!8/8!\approx 1/e\approx 0.37$.",
      r"Hats returned at random to $3$ people. $P(\text{no one gets own hat})$.",
      r"$!3/3!=2/6=1/3$.")
    a(776, r"The ordinary generating function (OGF) of a sequence $(a_n)$ is $A(x)=\sum_{n\ge 0}a_n x^n$. Product of OGFs convolves sequences: coefficients of $A(x)B(x)$ are $\sum_{k=0}^{n}a_k b_{n-k}$. Geometric series: $1/(1-x)=\sum x^n$. $(1-x)^{-k}=\sum\binom{n+k-1}{k-1}x^n$.",
      r"Coefficient of $x^5$ in $(1-x)^{-4}$.",
      r"$\binom{5+4-1}{4-1}=\binom{8}{3}=56$.",
      r"OGF for the number of unrestricted compositions of $n$ with parts in $\{1,2,3\}$ is",
      r"$1/(1-(x+x^2+x^3))$ for $n\ge 1$ after dropping the constant $1$.",
      r"Reading $[x^n](1-x)^{-k}$ as $\binom{n}{k}$ instead of $\binom{n+k-1}{k-1}$.",
      r"$[x^4](1+x+x^2)^3$.",
      r"Stars and bars with each factor contributing $0,1,$ or $2$: solutions of $y_1+y_2+y_3=4$ with $0\le y_i\le 2$. Count: $6$ (the triples $(2,2,0)$ and permutations: $3$, and $(2,1,1)$ and permutations: $3$).",
      r"OGF for $\binom{n}{2}$ is",
      r"$\sum\binom{n}{2}x^n=x^2/(1-x)^3$ for $n\ge 0$.")
    a(777, r"The exponential generating function (EGF) of $(a_n)$ is $\sum a_n x^n/n!$. Products of EGFs correspond to partitioning a labeled set into labeled blocks (the exponential formula). $e^x$ is the EGF for $a_n=1$; $1/(1-x)$ is the EGF for $a_n=n!$; $\exp(e^x-1)$ enumerates set partitions (Bell numbers).",
      r"What sequence has EGF $e^{2x}$? Evaluate $a_4$.",
      r"$a_n=2^n$, so $a_4=16$. (Functions from an $n$-set to a $2$-set, or subsets of a labeled $n$-set with $2$ colors.)",
      r"EGF for derangements is",
      r"$\sum !n\, x^n/n! = e^{-x}/(1-x)$.",
      r"Treating an EGF like an OGF and reading $a_n$ as the raw coefficient instead of $n![x^n]$.",
      r"$n!\,[x^n]e^{x}$ equals",
      r"$1$.",
      r"EGF for $a_n=n!$ is $1/(1-x)$. What does $a_n$ count?",
      r"Permutations of an $n$-element labeled set.")
    a(778, r"A linear homogeneous recurrence $a_n=c_1 a_{n-1}+\cdots+c_d a_{n-d}$ is determined by $d$ consecutive initial values. First-order $a_n=r a_{n-1}$ solves as $a_n=a_0 r^n$. Nonhomogeneous equations add a particular solution of the same shape as the forcing term.",
      r"$a_n=4a_{n-1}$ with $a_0=7$. Find $a_n$ and $a_3$.",
      r"$a_n=7\cdot 4^n$, $a_3=448$.",
      r"$a_n=a_{n-1}+6$ with $a_0=2$. Closed form?",
      r"$a_n=2+6n$.",
      r"Solving $a_n=3a_{n-1}+2$ as if it were homogeneous, getting only $A\cdot 3^n$ and missing the particular constant $-1$.",
      r"$a_n=3a_{n-1}+2$, $a_0=1$. Find $a_n$.",
      r"Particular $a=-1$; homogeneous $A\cdot 3^n$; $A-1=1$ so $A=2$; $a_n=2\cdot 3^n-1$. Check $a_1=5=3\cdot 1+2$.",
      r"Fibonacci $F_0=0$, $F_1=1$, $F_n=F_{n-1}+F_{n-2}$. $F_8$.",
      r"$21$. Sequence: $0,1,1,2,3,5,8,13,21$.")
    a(779, r"Characteristic equation of $a_n=c_1 a_{n-1}+\cdots+c_d a_{n-d}$ is $r^d=c_1 r^{d-1}+\cdots+c_d$. Distinct roots $r_i$ give $a_n=\sum A_i r_i^n$. A root of multiplicity $m$ contributes $(A_0+A_1 n+\cdots+A_{m-1}n^{m-1})r^n$. Constants $A_i$ are fixed by initial conditions.",
      r"$a_n=6a_{n-1}-8a_{n-2}$, $a_0=3$, $a_1=10$. Closed form?",
      r"$r^2-6r+8=0$, $(r-2)(r-4)=0$. $a_n=A\cdot 2^n+B\cdot 4^n$. $A+B=3$, $2A+4B=10\Rightarrow A+2B=5$, so $B=2$, $A=1$. Thus $a_n=2^n+2\cdot 4^n$.",
      r"$a_n=4a_{n-1}-4a_{n-2}$ has characteristic root",
      r"$r=2$ doubled: $a_n=(A+Bn)2^n$.",
      r"Forgetting the $n^j$ factors for a repeated root, or using $A r^n$ when two different roots are present but fitting only one initial condition.",
      r"$a_n=5a_{n-1}-6a_{n-2}$, $a_0=1$, $a_1=5$. Find $a_n$.",
      r"Roots $2,3$: $A+B=1$, $2A+3B=5\Rightarrow A=-2$, $B=3$. Thus $a_n=-2\cdot 2^n+3\cdot 3^n=-2^{n+1}+3^{n+1}$.",
      r"Check that formula at $n=2$.",
      r"$a_2=5\cdot 5-6\cdot 1=19$. Formula: $-8+27=19$.")
    a(780, r"Combinatorial probability: if every outcome in a finite sample space $S$ is equally likely, $P(A)=|A|/|S|$. Compute $|S|$ and $|A|$ by the counting tools above (permutations, combinations, complement, PIE). Dependence of draws (with/without replacement) changes $|S|$.",
      r"An urn has $12$ balls, $5$ red. Draw $3$ without replacement. $P(\text{exactly }2\text{ red})$.",
      r"$\dfrac{\binom{5}{2}\binom{7}{1}}{\binom{12}{3}}=\dfrac{10\cdot 7}{220}=\dfrac{7}{22}$.",
      r"A fair $6$-sided die is rolled twice. $P(\text{sum}=9)$.",
      r"$4$ outcomes $(3,6),(4,5),(5,4),(6,3)$ out of $36$, so $1/9$. (Not $(4.5,4.5)$.)",
      r"Using $n^k$ when sampling is without replacement, or $\binom{n}{k}$ when order is built into the sample space of sequences.",
      r"$P(\text{both aces})$ when drawing $2$ cards from $52$.",
      r"$\binom{4}{2}/\binom{52}{2}=6/1326=1/221$.",
      r"Five distinct books shelved at random. $P(\text{two particular books are adjacent})$.",
      r"Treat the pair as a block: $2\cdot 4!/5!=2/5$.")

    # S graph basics 781-791
    a(781, r"A graph $G=(V,E)$ consists of a vertex set $V$ and an edge set $E$ of pairs of vertices. Informal language: vertices are nodes, edges are links. Loops join a vertex to itself; multiple edges join the same pair. A drawing is not the graph: only the incidence data matter.",
      r"A graph has vertices $\{a,b,c,d\}$ and edges $\{ab,bc,cd,da,ac\}$. How many vertices and edges? Is $bd$ an edge?",
      r"$|V|=4$, $|E|=5$. No $bd$ edge: it is a square with one diagonal.",
      r"Two drawings of four vertices in a square, one with crossing diagonals and one without. Same graph?",
      r"If both have all six pairs edged, both are $K_4$; drawings may hide crossings.",
      r"Counting a crossing in a drawing as an extra vertex, or treating labels as optional when the problem's vertices are labeled.",
      r"The null graph on $5$ vertices has how many edges?",
      r"$0$.",
      r"Is a single loop at one vertex a graph on two vertices?",
      r"No: one vertex, one loop (a looped unicycle), unless an isolated second vertex is declared.")
    a(782, r"Vertices $V(G)$ and edges $E(G)$ are the two types of objects in a graph. The order is $|V|$, the size is $|E|$. An edge is incident to its two endpoints; those vertices are adjacent (neighbors). Isolated vertices still count in $|V|$.",
      r"A path on $6$ vertices. $|V|$ and $|E|$?",
      r"$|V|=6$, $|E|=5$.",
      r"A cycle $C_8$ has how many vertices and edges?",
      r"$8$ and $8$.",
      r"Forgetting isolated vertices when listing $V$, or counting each undirected edge twice in $|E|$.",
      r"Graph with $9$ vertices all isolated. Size?",
      r"$|E|=0$, order $9$.",
      r"$K_{2,3}$ has how many vertices and edges?",
      r"$5$ vertices, $6$ edges.")
    a(783, r"The degree $\deg(v)$ is the number of incident edge ends at $v$ (a loop contributes $2$). The degree sequence is the list of degrees, usually nonincreasing. The neighborhood $N(v)$ has size $\deg(v)$ in a simple graph. Minimum/maximum degree: $\delta(G)$, $\Delta(G)$.",
      r"In $C_5$ plus one chord, degrees of the two chord endpoints and of a far vertex?",
      r"Chord endpoints degree $3$; the vertex opposite a non-endpoint on $C_5$ may be degree $2$. Concretely $C_5$ on $(1,2,3,4,5)$ with chord $1$-$3$: degrees $3,2,3,2,2$.",
      r"Regular of degree $3$ on $10$ vertices is called",
      r"cubic; every degree is $3$.",
      r"Counting a loop as degree $1$, or mixing up $\delta$ and $\Delta$.",
      r"Degree of each vertex in $K_8$.",
      r"$7$.",
      r"A simple graph on $6$ vertices with $\Delta=5$. What must be true of that vertex?",
      r"It is adjacent to every other vertex.")
    a(784, r"Handshaking lemma: $\sum_{v\in V}\deg(v)=2|E|$. Corollary: the number of odd-degree vertices is even. You cannot have a graph with degree sequence $3,3,3$ (three odds).",
      r"Degrees $4,3,3,2,2,2$. How many edges?",
      r"Sum $16$, so $|E|=8$.",
      r"Is $5,3,3,2,1$ graphic?",
      r"No: five odd numbers, not even count of odds. (Also $5$ exceeds $n-1=4$.)",
      r"Equating the degree sum to $|E|$ rather than $2|E|$, or allowing an odd number of odd vertices.",
      r"A $4$-regular graph on $9$ vertices. $|E|$?",
      r"$(9\cdot 4)/2=18$.",
      r"Seven people at a party, each shakes hands with $3$ others. Possible?",
      r"No: seven odd degrees.")
    a(785, r"A simple graph has no loops and no multiple edges. Then $0\le |E|\le\binom{|V|}{2}$ and $0\le\deg(v)\le n-1$. Many GRE statements (Turán, planar bounds, $\chi\le\Delta+1$) assume simplicity unless they say otherwise.",
      r"Maximum edges in a simple graph on $7$ vertices.",
      r"$\binom{7}{2}=21$ (namely $K_7$).",
      r"Can a simple graph on $5$ vertices have a vertex of degree $5$?",
      r"No: max degree $4$.",
      r"Applying $\binom{n}{2}$ as an upper bound to multigraphs, where parallel edges can exceed it.",
      r"Simple graphs on $3$ labeled vertices: how many?",
      r"$2^{\binom{3}{2}}=8$.",
      r"A looped vertex of degree $2$ and nothing else: simple?",
      r"No, a loop is forbidden in a simple graph.")
    a(786, r"A directed graph (digraph) has ordered pairs as arcs. In-degree $\mathrm{deg}^-(v)$ and out-degree $\mathrm{deg}^+(v)$ satisfy $\sum\mathrm{deg}^+=\sum\mathrm{deg}^-=|A|$. An underlying undirected graph forgets orientation. Tournaments orient each pair of $K_n$ exactly once.",
      r"A digraph with arcs $a\to b$, $a\to c$, $b\to c$, $c\to a$. In- and out-degrees of $a,b,c$.",
      r"$a$: out $2$, in $1$; $b$: out $1$, in $1$; $c$: out $1$, in $2$.",
      r"How many tournaments on $4$ labeled vertices?",
      r"$2^{\binom{4}{2}}=2^6=64$.",
      r"Using $\sum\deg=2|E|$ on a directed graph without converting each arc to one out and one in (the directed handshaking is $\sum\mathrm{deg}^+=|A|$).",
      r"A directed cycle $\vec C_5$. Each in-degree?",
      r"$1$, and each out-degree $1$.",
      r"Can every out-degree be $2$ on a simple digraph with $3$ vertices?",
      r"No: $\sum\mathrm{deg}^+=6$ would need $6$ arcs, but at most $6$ ordered pairs exist; possible if the complete bidirected $K_3$ (two arcs per pair) — not simple oriented. In an orientation of a simple graph, max out-degree sum is $\binom{3}{2}=3$.")
    a(787, r"A walk is a sequence $v_0 e_1 v_1\cdots e_k v_k$ of incident vertices and edges (repetition of vertices and edges allowed). Length is $k$, the number of edges. The $(i,j)$ entry of $A^k$ counts walks of length $k$ from $i$ to $j$ in a simple graph with adjacency matrix $A$.",
      r"In $C_4$ labeled sequentially, how many walks of length $2$ from a vertex to itself?",
      r"$2$: out-and-back along either incident edge. ($A^2_{ii}=\deg(i)=2$.)",
      r"Does a walk of length $3$ exist from $u$ to $v$ if they are adjacent in a path of $2$ edges only?",
      r"Not without extra structure; on $P_3$ with ends $u,v$, walks of length $3$ from $u$ to $v$ do exist (there-and-back-and-there).",
      r"Requiring walks to have distinct vertices (that is a path, not a walk).",
      r"Walks of length $1$ from $v$ equal",
      r"$\deg(v)$.",
      r"On $K_3$, walks of length $2$ from $v$ to a different vertex $w$.",
      r"$1$: the unique walk $v$-$u$-$w$ through the third vertex.")
    a(788, r"A trail is a walk with no repeated edge (vertices may repeat). An Euler trail (see later) traverses every edge exactly once. Closed trails are circuits in some texts. Deleting used edges is the right mental model.",
      r"Does $K_{2,3}$ have a trail that uses all $6$ edges?",
      r"Yes: the three vertices of the size-$2$ part have degrees $3,3$; the other part degrees $2,2,2$. Exactly two odd degrees, so an Euler trail exists.",
      r"Can a trail repeat a vertex?",
      r"Yes; it cannot repeat an edge.",
      r"Calling every trail a path, or allowing a trail to reuse an edge because the vertex is new.",
      r"In a path of $4$ edges, the longest trail has length",
      r"$4$ (the path itself).",
      r"Start at a degree-$1$ vertex in a tree. Any trail can be extended until",
      r"you reach a dead-end; trees have no extra unused edges at interior vertices once you leave them, so a maximal trail from a leaf is a path to another leaf.")
    a(789, r"A path is a walk with no repeated vertex (hence no repeated edge). The path graph $P_n$ has $n$ vertices and $n-1$ edges. Distance $d(u,v)$ is the least length of a $u$--$v$ path (undefined or $\infty$ if none). A graph is a path iff $\delta=\Delta=2$ except two ends of degree $1$, and it is connected.",
      r"How many distinct $u$--$v$ paths in $K_4$ between two fixed vertices, of vertex-length $2$ (one interior vertex)?",
      r"$2$ choices for the interior vertex among the other two vertices? $K_4$ has two other vertices; each gives a path of length $2$. (Length $1$ is the direct edge.)",
      r"Is $v_1 v_2 v_1$ a path?",
      r"No: vertex $v_1$ repeats. It is a closed walk of length $2$ (an out-and-back).",
      r"Using walk, trail, and path as synonyms. GRE questions often hinge on the distinction.",
      r"Number of vertices in a path with $11$ edges.",
      r"$12$.",
      r"In a tree on $9$ vertices, number of paths between a given pair $u\neq v$.",
      r"Exactly one.")
    a(790, r"A cycle is a closed path of length at least $3$ (simple graph): distinct vertices except start $=$ end. The cycle graph $C_n$ is $2$-regular and connected. Girth is the length of a shortest cycle. Forests are graphs with no cycles.",
      r"Does $K_{2,4}$ contain a $3$-cycle? A $4$-cycle?",
      r"No odd cycle (bipartite). Yes $C_4$: any two on the size-$4$ side with the two on the other side.",
      r"How many edges in $C_{11}$?",
      r"$11$.",
      r"Calling a closed walk a cycle when it repeats vertices in the interior (e.g. a figure-eight).",
      r"Smallest $n$ for which $C_n$ is not bipartite.",
      r"$n=3$ (any odd $n$).",
      r"A simple graph with $6$ vertices and $7$ edges. Must it have a cycle?",
      r"Yes: a tree would have $5$ edges; extra edges create cycles.")
    a(791, r"Connected means every pair of vertices is joined by a path. A connected component is a maximal connected subgraph. The relation `joined by a path' is an equivalence relation on $V$. A graph with $c$ components, $n$ vertices, and no cycles is a forest with $n-c$ edges.",
      r"A graph on $10$ vertices with three components, all trees. How many edges?",
      r"$10-3=7$.",
      r"Adding one edge inside a component vs between components: effect on $c$.",
      r"Inside: $c$ unchanged (creates a cycle if it was a tree). Between: $c$ drops by $1$.",
      r"Counting isolated vertices as non-components, or assuming `connected' forbids degree $1$.",
      r"$G$ has $8$ vertices, $6$ edges, and is a forest. Components?",
      r"$c=8-6=2$.",
      r"Is $K_1\cup K_1\cup K_3$ connected? Components?",
      r"No; three components (two isolated vertices and a triangle).")

    # S special graph classes 792-801
    a(792, r"The complete graph $K_n$ has $n$ vertices and every pair adjacent: $|E|=\binom{n}{2}$, it is $(n-1)$-regular, $\chi(K_n)=n$, and $K_n$ is planar only for $n\le 4$. Complement of $K_n$ is empty.",
      r"Edges in $K_9$.",
      r"$\binom{9}{2}=36$.",
      r"$K_1,K_2,K_3$ are",
      r"a vertex; an edge; a triangle.",
      r"Writing $|E(K_n)|=n(n-1)$ (that counts ordered pairs, i.e. the tournament or the directed complete graph).",
      r"Degree in $K_{11}$.",
      r"$10$.",
      r"How many triangles in $K_6$?",
      r"$\binom{6}{3}=20$.")
    a(793, r"A graph is bipartite if $V=X\sqcup Y$ with every edge between $X$ and $Y$. Equivalent: no odd cycle. $K_{m,n}$ is the complete bipartite graph, with $|E|=mn$. Trees are bipartite. $2$-colorable means bipartite.",
      r"Edges in $K_{3,5}$. Odd cycles?",
      r"$15$ edges; no odd cycle.",
      r"Is $C_6$ bipartite? $C_7$?",
      r"Yes (parts of size $3,3$). No.",
      r"Assuming a graph with no triangles is bipartite ($C_5$ is a counterexample), or placing some edges inside a part.",
      r"Maximum edges in a simple bipartite graph on $8$ vertices.",
      r"$K_{4,4}$ has $16$ (balanced is maximal by convexity of $x(n-x)$).",
      r"Why is a tree on $12$ vertices bipartite?",
      r"No cycles at all, hence no odd cycle; $2$-color by distance from a root.")
    a(794, r"A tree is a connected acyclic graph. Equivalent: connected with $n-1$ edges; unique path between any pair; minimally connected; maximally acyclic. Any two of `connected', `acyclic', `$|E|=n-1$' imply the third.",
      r"A connected graph on $15$ vertices with $14$ edges. Must it be a tree?",
      r"Yes: connected $+\,|E|=n-1$ $\Rightarrow$ acyclic.",
      r"A graph on $8$ vertices with $7$ edges. Is it a tree?",
      r"Not necessarily: it could be $C_3$ plus isolateds and a path, i.e. disconnected. Need connectedness.",
      r"Using $|E|=n-1$ alone to declare a tree.",
      r"How many leaves (degree $1$) at least in a tree on $n\ge 2$ vertices?",
      r"At least $2$: if fewer than two leaves then $\sum\deg\ge 1+2(n-1)=2n-1>2n-2=2|E|$.",
      r"Add one edge to a tree. What appears?",
      r"Exactly one cycle (the unique paths close).")
    a(795, r"A rooted tree distinguishes a root $r$. Every other vertex has a unique parent (the neighbor toward $r$); children are the other neighbors. Depth of $v$ is $d(r,v)$. The rooting does not change the underlying undirected tree, only the orientation of edges away from $r$.",
      r"A rooted tree on $7$ vertices. How many parent pointers besides the root?",
      r"$6$, one for each non-root; equivalently $6$ edges.",
      r"Root a path $P_5$ at an endpoint vs at the middle vertex. Heights?",
      r"Height $4$ vs height $2$.",
      r"Assuming every rooted tree is binary, or counting the root as having a parent.",
      r"In a rooted tree, sum over non-roots of $1$ equals",
      r"$n-1$, also equal to the number of children-slots filled.",
      r"Can two vertices have the same parent?",
      r"Yes, they are siblings.")
    a(796, r"A leaf is a degree-$1$ vertex (in a rooted tree, typically a vertex with no children, which for the root would mean $K_1$). Every tree on $n\ge 2$ vertices has at least two leaves. Deleting a leaf from a tree leaves a tree.",
      r"The tree that is a star $K_{1,8}$. How many leaves?",
      r"$8$ (the center is degree $8$, not a leaf).",
      r"A path $P_{9}$. Leaves?",
      r"$2$.",
      r"Calling every degree-$2$ vertex a leaf, or forgetting that in a rooted binary tree an internal node can have one child and is not a leaf.",
      r"Tree on $6$ vertices with $4$ leaves. What is the degree sequence?",
      r"Possible: $3,3,1,1,1,1$ (two adjacent degree-$3$ vertices) or $4,2,1,1,1,1$. Both sum to $10=2\cdot 5$.",
      r"Remove all leaves from $K_{1,5}$. What remains?",
      r"A single vertex (the center).")
    a(797, r"A spanning tree of a connected graph $G$ is a subgraph that is a tree on all of $V(G)$. It has $n-1$ edges. Cayley's formula: $K_n$ has $n^{n-2}$ distinct spanning trees (labeled). Kruskal/Prim find minimum-weight spanning trees when edges are weighted.",
      r"Spanning trees of $K_4$ (labeled), by Cayley.",
      r"$4^{2}=16$.",
      r"Does $C_5$ have a spanning tree? How many edges does it use?",
      r"Yes: delete any one edge, get $P_5$, which has $4$ edges.",
      r"A spanning tree of a disconnected graph (it cannot exist), or counting spanning trees of $K_n$ as $n!$.",
      r"A connected graph on $20$ vertices. Edges in any spanning tree?",
      r"$19$.",
      r"How many spanning trees has $K_{2,3}$?",
      r"$m^{n-1}n^{m-1}=2^{2}3^{1}=12$.")
    a(798, r"An Euler path (Euler trail) traverses every edge exactly once. Existence (connected, ignoring isolated vertices): exactly zero or two odd-degree vertices. If two odds, the path must start at one odd vertex and end at the other.",
      r"Degrees $4,4,3,3,2$. Euler path? Euler circuit?",
      r"Two odds: Euler path yes, circuit no.",
      r"$K_5$ Euler path?",
      r"All degrees $4$, even: it has an Euler circuit, hence a path.",
      r"Checking vertices of degree $0$ as odd, or starting an Euler path at an even vertex when two odds exist (then some edge is stranded).",
      r"$K_{4,3}$ has all degrees? Euler path?",
      r"Degrees $3$ (four vertices of the $4$-side) and $4$ (three vertices). Four odds: no Euler path.",
      r"House-shaped pentagon plus two diagonals from the roof peak to the base corners: classic two odds?",
      r"The square-plus-roof drawing of two rooms: typically two odd vertices; Euler path exists, circuit does not.")
    a(799, r"An Euler circuit (Euler tour) is a closed Euler trail: every edge exactly once, return to start. Existence: the graph is connected (up to isolated vertices) and every degree is even. Then $\sum\deg=2|E|$ is consistent automatically.",
      r"Does $C_7$ have an Euler circuit? $K_4$?",
      r"$C_7$ yes (it is $2$-regular). $K_4$ is $3$-regular, four odd vertices: no.",
      r"$K_{2,2}$ is $C_4$: Euler circuit?",
      r"Yes, all degrees $2$.",
      r"Requiring an Euler circuit to visit every vertex exactly once (that is Hamiltonian).",
      r"A connected $4$-regular graph on $11$ vertices. Euler circuit?",
      r"Yes: connected and all even degrees. $|E|=22$.",
      r"Add one extra copy of a single edge of $C_6$. Euler circuit?",
      r"Those two endpoints become degree $3$; two odds: circuit no, path yes.")
    a(800, r"A Hamiltonian path visits every vertex exactly once (not necessarily all edges). There is no simple local degree criterion analogous to Euler's theorem; existence is NP-complete in general. Sufficient conditions (Dirac: $\delta\ge n/2$; Ore: $\deg u+\deg v\ge n$ for nonadjacent $u,v$) are not necessary.",
      r"Does $K_{2,3}$ have a Hamiltonian path? Hamiltonian cycle?",
      r"Path yes (alternate parts; the parts differ by $1$). Cycle no: bipartite with unequal parts.",
      r"Dirac on $n=7$: $\delta\ge$ how much guarantees a Hamiltonian cycle?",
      r"$\delta\ge 3.5$, so $\delta\ge 4$.",
      r"Applying the Euler even-degree test to Hamiltonian questions, or claiming every tree has a Hamiltonian path (only paths do, among trees).",
      r"Does $P_8$ have a Hamiltonian path? Cycle?",
      r"Path: yes, itself. Cycle: no.",
      r"The Petersen graph is a standard example that",
      r"is non-Hamiltonian (and nonplanar, $\delta=3$, $n=10$, Dirac fails).")
    a(801, r"A Hamiltonian cycle visits every vertex exactly once and returns. $K_n$ for $n\ge 3$ is Hamiltonian. A bipartite graph with parts of unequal size is not. Necessary: $\delta\ge 2$ and no cut-vertex bottleneck that strands a vertex, but these are weak.",
      r"Why has $K_{3,5}$ no Hamiltonian cycle?",
      r"Any cycle alternates parts, so must have even length and equal numbers from each part; $|X|\neq|Y|$.",
      r"$C_9$ is Hamiltonian?",
      r"Yes: it is a $9$-cycle.",
      r"Concluding Hamiltonian from Eulerian or conversely. $K_{2,2}$ is both; $K_4$ is Hamiltonian not Eulerian; $K_{2,2}$ plus a doubled edge can be Eulerian not Hamiltonian if extra vertices... keep the concepts separate.",
      r"Number of distinct Hamiltonian cycles in $K_5$ up to direction and starting point.",
      r"$(5-1)!/2=12$.",
      r"A tree on $\ge 3$ vertices has a Hamiltonian cycle?",
      r"Never: a cycle is not a tree, and extra edges are absent.")

    # S coloring and planarity 802-806
    a(802, r"A (vertex) coloring assigns colors so adjacent vertices get different colors. The chromatic number $\chi(G)$ is the least number of colors. Greedy coloring uses at most $\Delta+1$ colors. Cliques force $\chi\ge\omega(G)$; odd cycles force $\chi\ge 3$.",
      r"Color $C_5$. Fewest colors?",
      r"$3$ (odd cycle, not bipartite).",
      r"Greedy upper bound for a $4$-regular simple graph.",
      r"$\chi\le 5$.",
      r"Coloring edges by mistake (that is chromatic index), or using $\Delta$ colors always (Brooks: $\chi\le\Delta$ except complete graphs and odd cycles).",
      r"$\chi(K_{1,7})$.",
      r"$2$ (a star is bipartite).",
      r"If $G$ contains $K_4$, then $\chi(G)$ is at least",
      r"$4$.")
    a(803, r"$\chi(G)$ equals $1$ iff $G$ has no edges; equals $2$ iff $G$ is bipartite with at least one edge; $\chi(K_n)=n$; $\chi(C_n)=2$ or $3$ as $n$ even or odd. $\chi$ is not determined by $|V|$ and $|E|$ alone.",
      r"$\chi(K_6)$ and $\chi(K_{3,7})$.",
      r"$6$ and $2$.",
      r"A planar triangle-free graph can still have $\chi$ as large as?",
      r"Grötzsch: triangle-free planar graphs are $3$-colorable; do not claim $4$ is needed.",
      r"Assuming $\chi=\Delta$, or $\chi=\omega$ always (Mycielski / odd wheels aside, $\chi$ can exceed clique number; $C_5$ has $\omega=2$, $\chi=3$).",
      r"Chromatic number of a forest with an edge.",
      r"$2$.",
      r"Why $\chi(G)\ge n/\alpha(G)$ roughly: each color class is independent of size $\le\alpha$.",
      r"Yes: $\chi\ge\lceil n/\alpha\rceil$.")
    a(804, r"A graph is planar if it can be drawn in the plane with no edge crossings. $K_5$ and $K_{3,3}$ are the forbidden minors (Kuratowski/Wagner). Subdivisions of those are nonplanar. Planar graphs are $4$-colorable (four-color theorem); $K_4$ is planar, $K_5$ is not.",
      r"Is $K_4$ planar? $K_5$? $K_{2,6}$?",
      r"$K_4$ yes. $K_5$ no. $K_{2,6}$ is a star-like complete bipartite with a part of size $2$, planar (all edges can go without crossing).",
      r"Any tree is planar?",
      r"Yes.",
      r"Declaring a graph nonplanar because a particular drawing has crossings (re-draw it). $K_4$ often looks crossed.",
      r"Is $C_{20}$ planar?",
      r"Yes, as a convex $20$-gon.",
      r"$K_{3,3}$ minus one edge. Planar?",
      r"Yes: that graph is a subdivision of something planar; explicitly drawable.")
    a(805, r"Euler's formula for a connected plane graph: $v-e+f=2$, where $f$ counts faces including the infinite outer face. For a plane graph with $c$ components, $v-e+f=1+c$. A forest has $e=v-c$ and $f=1$, which matches: $v-(v-c)+1=c+1$.",
      r"A connected plane graph with $v=8$, $e=12$. How many faces?",
      r"$f=2-v+e=2-8+12=6$.",
      r"Tree on $10$ vertices drawn in the plane. Faces?",
      r"$f=2-10+9=1$, only the outer face.",
      r"Forgetting the outer face, so $v-e+f=1$ by mistake, or using $v-e+f=2$ on a disconnected graph.",
      r"Cube skeleton: $v=8$, $e=12$, $f=?$",
      r"$6$, and $8-12+6=2$.",
      r"Connected plane graph, all faces degree $3$ (including outer), $v=6$. Find $e,f$.",
      r"$2e=3f$ and $v-e+f=2\Rightarrow 6-e+2e/3=2\Rightarrow 4=e/3\Rightarrow e=12$, $f=8$ (octahedron).")
    a(806, r"Nonplanarity tests: if a simple planar graph has $v\ge 3$ then $e\le 3v-6$; if also triangle-free (or bipartite), $e\le 2v-4$. Thus $K_5$ has $e=10>3\cdot 5-6=9$; $K_{3,3}$ has $e=9>2\cdot 6-4=8$. Passing the inequality does not prove planarity.",
      r"Apply $e\le 3v-6$ to $K_5$ and to $K_{3,3}$.",
      r"$K_5$ violates $10\le 9$, nonplanar. $K_{3,3}$ satisfies $9\le 12$, so the general bound is inconclusive; the bipartite bound $9\le 8$ catches it.",
      r"A simple planar graph on $7$ vertices has at most how many edges?",
      r"$3\cdot 7-6=15$.",
      r"Using $e\le 3v-6$ as a characterization (it is only necessary). Also applying it to $v=1,2$.",
      r"Max edges in a simple planar bipartite graph on $10$ vertices.",
      r"$2\cdot 10-4=16$.",
      r"Does $e=3v-6$ force every face to be a triangle?",
      r"For a maximal planar graph, yes: $2e=3f$ together with Euler.")

    # S representations and algorithms 807-815
    a(807, r"The adjacency matrix $A$ of a simple labeled graph is the $n\times n$ symmetric $0$-$1$ matrix with $A_{ij}=1$ iff $ij\in E$, and $0$ diagonal. Then $(A^k)_{ij}$ equals the number of walks of length $k$ from $i$ to $j$. $\sum_{i,j}A_{ij}=2|E|$.",
      r"Adjacency matrix of $P_3$ with vertices labeled $1{-}2{-}3$ in path order.",
      r"$\begin{pmatrix}0&1&0\\1&0&1\\0&1&0\end{pmatrix}$.",
      r"$(A^2)_{11}$ for that $P_3$.",
      r"$1$: the walk $1$-$2$-$1$.",
      r"Putting $2$ on the diagonal for degree, or using an asymmetric $A$ for an undirected graph without saying so.",
      r"Trace of $A$ for a simple graph.",
      r"$0$.",
      r"$A^3_{ij}$ counts",
      r"walks of length $3$ from $i$ to $j$.")
    a(808, r"An incidence matrix $B$ (oriented) is $n\times m$ with rows vertices and columns edges; each column has a $+1$ and a $-1$ at the endpoints (orientation chosen). Then $B B^T$ is a Laplacian $D-A$. Unoriented $(0,1)$-incidence has two $1$s per column. Rank of the Laplacian is $n-c$.",
      r"A path of two edges (vertices $1,2,3$). Give a $3\times 2$ oriented incidence matrix.",
      r"Columns for $1\to 2$ and $2\to 3$: $\begin{pmatrix}-1&0\\1&-1\\0&1\end{pmatrix}$ (signs only need to be opposite on each column).",
      r"Each column of an oriented incidence matrix sums to",
      r"$0$.",
      r"Confusing incidence with adjacency (square vs $n\times m$), or putting degree on the diagonal of $B$.",
      r"Unoriented incidence: number of $1$s in the whole matrix for a simple graph.",
      r"$2|E|$.",
      r"Kernel dimension of $B^T$ for a connected graph.",
      r"$1$: $B^T\mathbf{1}=0$, and connectedness makes $\ker B^T$ exactly the constants.")
    a(809, r"Breadth-first search (BFS) from $s$ explores vertices in order of increasing distance from $s$. The BFS layers are $\{v:d(s,v)=k\}$. On an unweighted graph, BFS computes shortest-path distances. Queue implementation: $O(|V|+|E|)$.",
      r"Star $K_{1,6}$ with BFS from a leaf. Distances of the center and of the other leaves?",
      r"Center at distance $1$; other leaves at distance $2$.",
      r"BFS from a vertex of $C_6$. Layer sizes?",
      r"$1,2,2,1$ (distances $0,1,2,3$).",
      r"Using BFS to compute shortest paths on a graph with unequal positive edge weights (use Dijkstra).",
      r"In a connected unweighted graph, BFS tree edges vs non-tree edges: a non-tree edge can join",
      r"the same layer or adjacent layers, never skip a layer.",
      r"Runtime on a simple graph with $n=50$, $e=200$, BFS is $\Theta($what$)$?",
      r"$\Theta(n+e)=\Theta(250)$.")
    a(810, r"Depth-first search (DFS) explores as far as possible along each branch before backtracking (stack / recursion). It produces a DFS forest, classifying edges as tree, back, forward, or cross. DFS decides cycle existence: a back edge in an undirected graph means a cycle. Also $O(|V|+|E|)$.",
      r"DFS on a tree. Back edges?",
      r"None: a tree has no extra edges.",
      r"Undirected $C_5$: DFS finds a cycle because",
      r"the last vertex has an edge back to an ancestor on the stack.",
      r"Claiming DFS layers equal distances (that is BFS). DFS visit order depends on adjacency-list order.",
      r"Connected undirected graph, DFS from $s$ produces how many trees in the DFS forest?",
      r"One (the component of $s$); remaining components give additional trees if you restart.",
      r"Space in the recursive implementation is $O($what$)$ in the worst case on a path.",
      r"$O(n)$ recursion depth.")
    a(811, r"Shortest path: in an unweighted graph, BFS distance. With nonnegative edge weights, Dijkstra grows the set of settled vertices by always adding the unsettled vertex of smallest tentative distance. Negative weights need Bellman–Ford. Shortest paths satisfy a triangle inequality $d(s,t)\le d(s,u)+w(u,t)$.",
      r"Path $s{-}a{-}t$ with weights $10,10$ and chord $s{-}t$ of weight $25$. Shortest $s$--$t$?",
      r"$20$ via $a$, not $25$.",
      r"All weights $1$. Which algorithm is enough?",
      r"BFS.",
      r"Running Dijkstra with a negative edge (it can fail). Also summing weights along a walk that repeats vertices when weights are positive (useless, not shorter).",
      r"Nonnegative weights. After Dijkstra settles $u$, $d(s,u)$ is",
      r"the true shortest-path distance.",
      r"A negative cycle reachable from $s$ means",
      r"shortest-path distance to some vertices is $-\infty$ (unbounded).")
    a(812, r"Algorithmic complexity compares growth of time/space as a function of input size $n$ (or $|V|,|E|$). Worst-case $T(n)$ is the quantity of interest on GRE-style questions. Polynomial vs exponential is the practical divide: $n^3$ vs $2^n$. Graph algorithms are often $O(n+m)$ (linear in the representation).",
      r"Which is asymptotically faster for large $n$: $\Theta(n^2)$ or $\Theta(n\log n)$?",
      r"$\Theta(n\log n)$.",
      r"Hamiltonian-cycle brute force on $n$ labeled vertices is about $n!$ checks. Stirling: $n!\sim$",
      r"$(n/e)^n\sqrt{2\pi n}$, super-exponential vs $2^n$.",
      r"Calling an $O(n^2)$ algorithm `quadratic' then claiming it beats $O(2^n)$ for $n=3$ as if that settled asymptotics.",
      r"BFS on an adjacency list is $O(n+m)$. On an adjacency matrix?",
      r"$O(n^2)$ even if $m$ is small, because you scan rows.",
      r"If $T(n)=3T(n/2)+\Theta(n)$, Master theorem $T(n)$ is",
      r"$\Theta(n^{\log_2 3})$.")
    a(813, r"Big-O: $f=O(g)$ if $|f(n)|\le C g(n)$ for some $C$ and all large $n$. $f=\Omega(g)$ is the reverse; $\Theta$ is both. $f=o(g)$ means $f/g\to 0$. Polynomials: only the highest degree matters. $n^a=O(n^b)$ iff $a\le b$. $(\log n)^c=o(n^\varepsilon)$ for every $\varepsilon>0$.",
      r"Is $3n^2+100n+7=O(n^2)$? $=O(n^3)$? $=\Theta(n^2)$?",
      r"Yes; yes; yes.",
      r"$2^n$ vs $n!$ : which is $O$ of the other?",
      r"$2^n=O(n!)$, not conversely.",
      r"Canceling $O(n)+O(n)=O(n)$ is fine, but $O(n)-O(n)=O(1)$ is not (difference of two $n^2$ terms can still be $n^2$).",
      r"Is $n\log n=O(n^{1.1})$?",
      r"Yes.",
      r"Smallest $\Theta$ class among $n^2$, $n\log n$, $2^n$, $n!$, $\log(n!)$ for large $n$.",
      r"$\log(n!)=\Theta(n\log n)$ by Stirling, which is the smallest among those except it ties the order of $n\log n$; $n\log n$ and $\log(n!)$ are $\Theta$ of each other, smaller than $n^2$.")
    a(814, r"A recursive algorithm calls itself on smaller inputs; an iterative one uses a loop. The same recurrence can be implemented either way. Recursion depth costs stack space; tail recursion can be converted to a loop. Correctness of recursion is induction on input size.",
      r"Factorial: recursive $n\cdot(n-1)!$ vs a loop multiplying $1..n$. Same $T(n)$?",
      r"Both $\Theta(n)$ arithmetic steps (ignoring bit-cost of large integers).",
      r"Naive recursive Fibonacci $F_n=F_{n-1}+F_{n-2}$ time is $\Theta(\phi^n)$. Iterative?",
      r"$\Theta(n)$ by storing the last two values.",
      r"Assuming recursive always slower, or that iteration cannot implement DFS (it can, with an explicit stack).",
      r"Binary search recursive vs iterative. $T(n)$?",
      r"Both $\Theta(\log n)$ comparisons on a sorted array.",
      r"Why does naive recursive Fibonacci recompute $F_3$ many times when computing $F_{10}$?",
      r"The recursion tree branches and overlaps; no memoization.")
    a(815, r"Euclidean algorithm: $\gcd(a,b)=\gcd(b,a\bmod b)$, and $\gcd(a,0)=a$. It is the model of a fast recursive/iterative number-theoretic algorithm: $O(\log\min(a,b))$ steps (Lamé: worst case Fibonacci). Bézout: it also yields $ax+by=\gcd$.",
      r"Compute $\gcd(252,198)$ by Euclid.",
      r"$252=1\cdot 198+54$, $198=3\cdot 54+36$, $54=1\cdot 36+18$, $36=2\cdot 18+0$, so $\gcd=18$.",
      r"$\gcd(1071,462)$.",
      r"$1071=2\cdot 462+147$, $462=3\cdot 147+21$, $147=7\cdot 21+0$, so $21$.",
      r"Stopping at the first remainder instead of at remainder $0$, or using $\gcd(a,b)=ab$ (that is $\mathrm{lcm}\cdot\gcd=ab$).",
      r"$\gcd(54,17)$. How many divisions until $0$?",
      r"$54=3\cdot 17+3$, $17=5\cdot 3+2$, $3=1\cdot 2+1$, $2=2\cdot 1+0$: gcd $1$, four division steps.",
      r"Why is Euclid faster than trial division up to $\sqrt{n}$?",
      r"Remainders shrink exponentially (at worst like Fibonacci), not like $\sqrt{n}$ trials.")

    # T probability foundations 816-824
    a(816, r"A sample space $\Omega$ is the set of all outcomes of an experiment. Discrete GRE models take $\Omega$ finite or countable. Outcomes $\omega\in\Omega$ are the atoms; events are subsets. Specify $\Omega$ before assigning probabilities: two dice as $36$ ordered pairs, not $11$ sums.",
      r"Two fair distinguishable dice. $|\Omega|$? Describe $\Omega$.",
      r"$36$; $\Omega=\{1,2,3,4,5,6\}^2$.",
      r"Flip a coin until the first head. A usable $\Omega$ is",
      r"$\{H,TH,TTH,TTTH,\ldots\}$, countably infinite.",
      r"Taking $\Omega=\{\text{sum}=2,\ldots,12\}$ with equal weights for two dice (those $11$ outcomes are not equally likely).",
      r"A $5$-card hand from $52$. $|\Omega|$ if hands are unordered.",
      r"$\binom{52}{5}=2598960$.",
      r"One card from a $52$-card deck. $|\Omega|$.",
      r"$52$.")
    a(817, r"An event is a subset $A\subset\Omega$ (in a $\sigma$-algebra, which for finite $\Omega$ may be the power set). $A^c=\Omega\setminus A$. Disjoint events satisfy $A\cap B=\emptyset$. The sure event is $\Omega$; the impossible event is $\emptyset$.",
      r"One die. Event $A=\{\text{even}\}$, $B=\{\text{prime}\}=\{2,3,5\}$. $A\cap B$ and $A\cup B$.",
      r"$A\cap B=\{2\}$; $A\cup B=\{2,3,4,5,6\}$.",
      r"For $\Omega=\{1,\ldots,10\}$, write the event `divisible by $3$'.",
      r"$\{3,6,9\}$.",
      r"Treating `at least one head in two flips' as a single outcome rather than a $3$-element event $\{HT,TH,HH\}$.",
      r"Two coins, $\Omega=\{HH,HT,TH,TT\}$. Event `exactly one head'.",
      r"$\{HT,TH\}$.",
      r"$A\subset B$ means which relation of occurrence?",
      r"If $A$ happens then $B$ happens.")
    a(818, r"Kolmogorov axioms: $P(A)\ge 0$, $P(\Omega)=1$, and if $A_i$ are pairwise disjoint then $P(\bigcup_i A_i)=\sum_i P(A_i)$ (countable additivity). Finite additivity is the GRE special case. Consequences: $P(\emptyset)=0$, $P(A)\le 1$, monotonicity $A\subset B\Rightarrow P(A)\le P(B)$.",
      r"$P(A)=0.4$, $P(B)=0.35$, $A\cap B=\emptyset$. $P(A\cup B)$?",
      r"$0.75$.",
      r"Why can there be no event with $P(A)=1.2$?",
      r"Axioms force $P\le P(\Omega)=1$.",
      r"Assigning probabilities that sum to more than $1$ over a partition, or using $P(A\cup B)=P(A)+P(B)$ when $A\cap B\neq\emptyset$.",
      r"$P(\emptyset)$.",
      r"$0$.",
      r"If $A\subset B$ and $P(B)=0.2$, the largest possible $P(A)$ is",
      r"$0.2$.")
    a(819, r"Complement rule: $P(A^c)=1-P(A)$. Useful for `at least one' and `never'. Also $P(A\setminus B)=P(A)-P(A\cap B)$.",
      r"$P(\text{at least one head in }4\text{ fair coin flips})$.",
      r"$1-(1/2)^4=15/16$.",
      r"$P(A)=0.28$. $P(A^c)$.",
      r"$0.72$.",
      r"Computing $1-P(\text{exactly one})$ when the problem asked $P(\text{at least one})$, which still includes `exactly two', etc.",
      r"A die is rolled. $P(\text{not a }6)$.",
      r"$5/6$.",
      r"Independent trials, success probability $0.3$, $n=5$. $P(\text{at least one success})$.",
      r"$1-(0.7)^5=1-0.16807=0.83193$.")
    a(820, r"Union: $P(A\cup B)=P(A)+P(B)-P(A\cap B)$. Intersection is not determined by $P(A)$ and $P(B)$ alone; the Fréchet bounds are $\max(0,P(A)+P(B)-1)\le P(A\cap B)\le\min(P(A),P(B))$. For three sets, inclusion-exclusion as in counting.",
      r"$P(A)=0.6$, $P(B)=0.5$, $P(A\cap B)=0.3$. $P(A\cup B)$?",
      r"$0.6+0.5-0.3=0.8$.",
      r"If $P(A)=0.7$ and $P(B)=0.6$, the smallest possible $P(A\cap B)$ is",
      r"$0.3$.",
      r"Writing $P(A\cap B)=P(A)P(B)$ without independence, or $P(A\cup B)=P(A)+P(B)$ always.",
      r"$P(A\cup B\cup C)$ with $P(A)=P(B)=P(C)=0.2$, pairwise intersections $0.05$, triple $0.01$.",
      r"$0.6-0.15+0.01=0.46$.",
      r"$A$ and $B$ disjoint, $P(A)=0.4$, $P(B)=0.1$. $P(A\cap B)$ and $P(A\cup B)$.",
      r"$0$ and $0.5$.")
    a(821, r"Conditional probability: $P(A\mid B)=P(A\cap B)/P(B)$ when $P(B)>0$. Multiplication: $P(A\cap B)=P(B)P(A\mid B)=P(A)P(B\mid A)$. Restrict the sample space to $B$ and renormalize.",
      r"A fair die. $P(\text{six}\mid\text{even})$.",
      r"$(1/6)/(1/2)=1/3$. Equivalently $1$ six among $\{2,4,6\}$.",
      r"Two cards from $52$, no replacement. $P(\text{second ace}\mid\text{first ace})$.",
      r"$3/51=1/17$.",
      r"Using $P(A\mid B)=P(A)/P(B)$, or dropping the condition after the first draw in without-replacement problems.",
      r"$P(A\cap B)=0.12$, $P(B)=0.4$. $P(A\mid B)$.",
      r"$0.3$.",
      r"A bag: $4$ green, $6$ blue. Two draws without replacement. $P(\text{second green}\mid\text{first blue})$.",
      r"$4/9$.")
    a(822, r"$A$ and $B$ are independent if $P(A\cap B)=P(A)P(B)$. Then $P(A\mid B)=P(A)$ when $P(B)>0$. Pairwise independence of several events does not imply mutual independence. Disjoint events of positive probability are dependent, not independent.",
      r"Two fair coins. $A=\{\text{first is H}\}$, $B=\{\text{second is H}\}$. Independent?",
      r"Yes: $P(A\cap B)=1/4=P(A)P(B)$.",
      r"A fair die. $A=\{\text{even}\}$, $B=\{1,2,3\}$. Independent?",
      r"$P(A\cap B)=P(\{2\})=1/6$, $P(A)P(B)=(1/2)(1/2)=1/4\neq 1/6$. Dependent.",
      r"Confusing disjoint with independent. Also checking only $P(A\mid B)=P(B\mid A)$.",
      r"If $P(A)=0.3$, $P(B)=0.5$, independent, $P(A\cup B)$.",
      r"$0.3+0.5-0.15=0.65$.",
      r"Can two events with $P(A)=1$ fail independence with $B$?",
      r"No: $P(A\cap B)=P(B)=P(A)P(B)$. Almost-sure events are independent of everything.")
    a(823, r"Law of total probability: if $\{B_i\}$ is a partition of $\Omega$ (disjoint, union $\Omega$, $P(B_i)>0$), then $P(A)=\sum_i P(A\mid B_i)P(B_i)$. Draw the tree: first branch on the partition, then $A$.",
      r"Factory: $30\%$ of items from line $A$ (defect rate $2\%$), $70\%$ from line $B$ (defect rate $5\%$). $P(\text{defect})$.",
      r"$0.3\cdot 0.02+0.7\cdot 0.05=0.006+0.035=0.041$.",
      r"A coin is chosen at random from $\{\text{fair}, \text{two-headed}\}$, then flipped. $P(H)$.",
      r"$\frac12\cdot\frac12+\frac12\cdot 1=\frac34$.",
      r"Averaging the conditional probabilities with equal weights when the partition pieces are not equally likely.",
      r"Urn $1$ has $2$ red and $3$ white; urn $2$ has $4$ red and $1$ white. Pick an urn at random, then a ball. $P(\text{red})$.",
      r"$\frac12\cdot\frac{2}{5}+\frac12\cdot\frac{4}{5}=\frac{3}{5}$.",
      r"$P(A\mid B)=0.4$, $P(A\mid B^c)=0.1$, $P(B)=0.25$. $P(A)$.",
      r"$0.4\cdot 0.25+0.1\cdot 0.75=0.175$.")
    a(824, r"Bayes: $P(B_j\mid A)=\dfrac{P(A\mid B_j)P(B_j)}{\sum_i P(A\mid B_i)P(B_i)}$. Posterior $\propto$ likelihood $\times$ prior. The denominator is $P(A)$ by the law of total probability.",
      r"Disease prevalence $1\%$. Test: $P(+ \mid D)=0.99$, $P(+ \mid D^c)=0.05$. $P(D\mid +)$.",
      r"$P(+)=0.99\cdot 0.01+0.05\cdot 0.99=0.0099+0.0495=0.0594$. Posterior $0.0099/0.0594=1/6$.",
      r"Two coins: fair and two-headed, pick one at random, flip $H$. $P(\text{two-headed}\mid H)$.",
      r"$(1\cdot\tfrac12)/(\tfrac34)=2/3$.",
      r"Reporting the sensitivity $P(+ \mid D)$ as if it were $P(D\mid +)$ (base-rate neglect).",
      r"Prior $P(B)=0.2$, $P(A\mid B)=0.7$, $P(A\mid B^c)=0.1$. $P(B\mid A)$.",
      r"$P(A)=0.14+0.08=0.22$, posterior $0.14/0.22=7/11$.",
      r"Three drawers: (GG), (GS), (SS). Pick a drawer at random, then a gold coin. $P(\text{other coin gold})$.",
      r"Classic: $2/3$ (not $1/2$). Two golds in GG, one in GS; equally likely golds.")

    # T discrete RVs 825-835
    a(825, r"A random variable is a function $X:\Omega\to\mathbb{R}$. It is discrete if its range is finite or countable. The law of $X$ is $P(X\in\cdot)$, not the particular labeling of $\Omega$. Two different experiments can induce the same law.",
      r"One die. $X=\mathbf{1}_{\{\text{even}\}}$. Range of $X$ and $P(X=1)$.",
      r"Range $\{0,1\}$; $P(X=1)=1/2$.",
      r"Two dice, $S=\text{sum}$. How many values does $S$ take?",
      r"$11$ values, $2$ through $12$.",
      r"Calling $X$ `random' as if $X$ were a random subset rather than a number attached to each $\omega$. Also treating the name $X$ as the event $\{X=1\}$.",
      r"$X(\omega)=0$ for all $\omega$. Is $X$ a random variable?",
      r"Yes, a constant (degenerate) random variable.",
      r"If $X$ is the number of heads in $3$ fair flips, $X(\text{HHT})$.",
      r"$2$.")
    a(826, r"The probability mass function (PMF) of a discrete $X$ is $p_X(x)=P(X=x)$. Requirements: $p_X(x)\ge 0$ and $\sum_x p_X(x)=1$. Then $P(X\in A)=\sum_{x\in A}p_X(x)$. The support is $\{x:p_X(x)>0\}$.",
      r"$p(k)=c\cdot(1/3)^k$ for $k=1,2,3$. Find $c$ and $p(2)$.",
      r"$c\bigl(\frac13+\frac19+\frac1{27}\bigr)=1$, $c\cdot\frac{13}{27}=1$, $c=27/13$. Then $p(2)=(27/13)\cdot(1/9)=3/13$.",
      r"A fair die. PMF of $X$.",
      r"$p(x)=1/6$ for $x=1,\ldots,6$.",
      r"Using a PMF that does not sum to $1$, or writing $p(x)=P(X\le x)$ (that is the CDF).",
      r"$P(X\in\{0,2,4\})$ if $p(x)=1/8$ for $x=0,1,\ldots,7$.",
      r"$3/8$.",
      r"Can $p(3)=1.4$?",
      r"No: PMF values lie in $[0,1]$ and sum to $1$.")
    a(827, r"The CDF of any random variable is $F_X(x)=P(X\le x)$. For discrete $X$, $F$ is a right-continuous step function with jumps of size $p_X(x)$ at atoms. Always: $F$ nondecreasing, $\lim_{x\to-\infty}F=0$, $\lim_{x\to\infty}F=1$, and $P(a<X\le b)=F(b)-F(a)$.",
      r"$X$ takes $1,2,4$ with probabilities $1/2,1/3,1/6$. $F(2)$ and $F(3)$.",
      r"$F(2)=1/2+1/3=5/6$. $F(3)=5/6$ (no mass in $(2,3]$).",
      r"$P(X>x)$ in terms of $F$.",
      r"$1-F(x)$ if one is careful at atoms: $P(X>x)=1-F(x)$, $P(X\ge x)=1-F(x-)$.",
      r"Reading $F(x)=P(X<x)$ (left vs right), or expecting $F$ to be a density.",
      r"$X\sim\mathrm{Unif}\{1,2,3,4\}$. $F(2.7)$.",
      r"$P(X\le 2.7)=P(X\le 2)=1/2$.",
      r"Jumps of $F$ occur where?",
      r"At points of the support; jump size equals the PMF.")
    a(828, r"For discrete $X$, $\mathbb{E}[X]=\sum_x x\,p_X(x)$ (absolutely, when $\sum|x|p(x)<\infty$). Linearity holds even without independence: $\mathbb{E}[aX+b]=a\mathbb{E}[X]+b$. LOTUS: $\mathbb{E}[g(X)]=\sum g(x)p_X(x)$, not $g(\mathbb{E}[X])$ in general.",
      r"$p(1)=1/2$, $p(3)=1/3$, $p(6)=1/6$. $\mathbb{E}[X]$.",
      r"$1\cdot\frac12+3\cdot\frac13+6\cdot\frac16=\frac12+1+1=\frac52$.",
      r"Fair die $\mathbb{E}[X]$.",
      r"$3.5$.",
      r"Replacing $\mathbb{E}[X^2]$ by $(\mathbb{E}[X])^2$, or averaging the values of $X$ with equal weights when the PMF is not uniform.",
      r"$\mathbb{E}[2X-4]$ if $\mathbb{E}[X]=5$.",
      r"$6$.",
      r"$X\in\{0,10\}$ with $P(X=10)=0.2$. $\mathbb{E}[X]$ and $\mathbb{E}[X^2]$.",
      r"$2$ and $20$.")
    a(829, r"$\mathrm{Var}(X)=\mathbb{E}[(X-\mu)^2]=\mathbb{E}[X^2]-\mu^2$ where $\mu=\mathbb{E}[X]$. Always $\mathrm{Var}\ge 0$, and $\mathrm{Var}(aX+b)=a^2\mathrm{Var}(X)$. $\mathrm{Var}(X)=0$ iff $X$ is a.s. constant.",
      r"$X$ takes $0$ and $10$ with probabilities $0.8$ and $0.2$. Variance?",
      r"$\mu=2$, $\mathbb{E}[X^2]=20$, $\mathrm{Var}=20-4=16$. Or $(0-2)^2\cdot 0.8+(10-2)^2\cdot 0.2=3.2+12.8=16$.",
      r"$\mathrm{Var}(3X+7)$ if $\mathrm{Var}(X)=5$.",
      r"$9\cdot 5=45$.",
      r"Using $\mathbb{E}[X^2]-(\mathbb{E}[X])$ (not squared), or $\mathrm{Var}(X+Y)=\mathrm{Var} X+\mathrm{Var} Y$ without independence/uncorrelatedness.",
      r"Fair coin $X=\mathbf{1}_H$. $\mathrm{Var}(X)$.",
      r"$p=1/2$, $\mathrm{Var}=p(1-p)=1/4$.",
      r"If $\mathbb{E}[X]=4$ and $\mathbb{E}[X^2]=20$, $\mathrm{Var}(X)$.",
      r"$4$.")
    a(830, r"Standard deviation $\sigma_X=\sqrt{\mathrm{Var}(X)}$. It has the same units as $X$. Standardized variable $Z=(X-\mu)/\sigma$ has mean $0$ and variance $1$ when $\sigma>0$. Chebyshev: $P(|X-\mu|\ge k\sigma)\le 1/k^2$.",
      r"$\mathrm{Var}(X)=25$. $\sigma_X$? $\sigma_{2X}$?",
      r"$5$; $10$.",
      r"$X$ has $\mu=12$, $\sigma=4$. $P(|X-12|\ge 12)$ by Chebyshev.",
      r"$k=3$, bound $1/9$.",
      r"Reporting variance when asked for SD, or dividing by $\sigma^2$ instead of $\sigma$ when standardizing.",
      r"$Z=(X-8)/3$ if $\mu_X=8$, $\sigma_X=3$. $\mathbb{E}[Z]$ and $\mathrm{Var}(Z)$.",
      r"$0$ and $1$.",
      r"If $\sigma_X=0$, what is the distribution of $X$?",
      r"Point mass at $\mu$.")
    a(831, r"Linearity: $\mathbb{E}[X_1+\cdots+X_n]=\mathbb{E}[X_1]+\cdots+\mathbb{E}[X_n]$ with no independence hypothesis. This is the main reason to introduce indicators. $\mathbb{E}[cX]=c\mathbb{E}[X]$.",
      r"Ten dice, $S=\text{sum}$. $\mathbb{E}[S]$.",
      r"$10\cdot 3.5=35$.",
      r"$n$ people, $X=\#$ of fixed points of a random permutation. $\mathbb{E}[X]$.",
      r"$1$ for $n\ge 1$: $X=\sum_{j=1}^n I_j$ with $I_j=\mathbf{1}_{\{\pi(j)=j\}}$, so $\mathbb{E}[I_j]=(n-1)!/n!=1/n$ and $\mathbb{E}[X]=1$.",
      r"Requiring independence before adding expectations, or applying the same reasoning to $\mathbb{E}[XY]$ or $\mathrm{Var}(X+Y)$.",
      r"$\mathbb{E}[3X-2Y+5]$ if $\mathbb{E}[X]=4$, $\mathbb{E}[Y]=7$.",
      r"$12-14+5=3$.",
      r"Indicators $I_A,I_B$. $\mathbb{E}[I_A+I_B]$ vs $\mathbb{E}[I_A I_B]$.",
      r"$P(A)+P(B)$ vs $P(A\cap B)$.")
    a(832, r"If $X_1,\ldots,X_n$ are pairwise uncorrelated (in particular if independent and square-integrable), $\mathrm{Var}(\sum X_i)=\sum\mathrm{Var}(X_i)$. In general $\mathrm{Var}(\sum X_i)=\sum\mathrm{Var}(X_i)+2\sum_{i<j}\mathrm{Cov}(X_i,X_j)$.",
      r"Independent $X,Y$ with $\mathrm{Var} X=4$, $\mathrm{Var} Y=9$. $\mathrm{Var}(X+Y)$ and $\mathrm{Var}(X-Y)$.",
      r"$13$ and $13$.",
      r"$n$ i.i.d. with variance $\sigma^2$. Variance of the sample mean $\bar X$.",
      r"$\sigma^2/n$.",
      r"Using $\mathrm{Var}(X+Y)=\mathrm{Var} X+\mathrm{Var} Y$ for $X=Y$, which actually gives $4\mathrm{Var} X$. Also $\mathrm{Var}(X-Y)=\mathrm{Var} X-\mathrm{Var} Y$.",
      r"Independent Bernoulli($p$) sum of $n$ is Binomial. Variance?",
      r"$np(1-p)$.",
      r"$\mathrm{Var}(2X+3Y)$ independent, $\mathrm{Var} X=2$, $\mathrm{Var} Y=5$.",
      r"$4\cdot 2+9\cdot 5=53$.")
    a(833, r"The indicator $I_A$ equals $1$ on $A$ and $0$ off $A$. Then $I_A$ is Bernoulli($P(A)$), $\mathbb{E}[I_A]=P(A)$, $\mathrm{Var}(I_A)=P(A)(1-P(A))$, and $I_{A\cap B}=I_A I_B$, $I_{A^c}=1-I_A$. Counts are sums of indicators.",
      r"Throw $n=12$ balls independently into $m=5$ bins uniformly. Expected number of empty bins.",
      r"$5(1-1/5)^{12}=5(0.8)^{12}$.",
      r"$\mathbb{E}[I_A I_B]$ equals",
      r"$P(A\cap B)$.",
      r"Treating dependent indicators as if $\mathrm{Var}(\sum I_i)=\sum\mathrm{Var}(I_i)$ when the problem asks variance of a count with overlapping pairs.",
      r"Expected number of aces in a $5$-card hand.",
      r"$5\cdot(4/52)=5/13$ (indicators on each card position, or linearity on the four ace-types: $4\cdot\binom{51}{4}/\binom{52}{5}=5/13$).",
      r"$I_A+I_{A^c}$ equals",
      r"$1$ almost surely.")
    a(834, r"$\mathrm{Cov}(X,Y)=\mathbb{E}[(X-\mu_X)(Y-\mu_Y)]=\mathbb{E}[XY]-\mu_X\mu_Y$. Bilinear, symmetric. $\mathrm{Cov}(X,X)=\mathrm{Var}(X)$. Independent integrable r.v.s have covariance $0$, but uncorrelated does not imply independent (e.g. $Y=X^2$ with symmetric $X$).",
      r"$X$ uniform on $\{-1,0,1\}$, $Y=X^2$. Compute $\mathrm{Cov}(X,Y)$. Independent?",
      r"$\mathbb{E}[X]=0$, $\mathbb{E}[Y]=2/3$, $\mathbb{E}[XY]=\mathbb{E}[X^3]=0$, so $\mathrm{Cov}=0$. Not independent: $\{Y=0\}=\{X=0\}$.",
      r"$\mathrm{Cov}(aX+b,cY+d)$.",
      r"$ac\,\mathrm{Cov}(X,Y)$.",
      r"Concluding independence from $\mathrm{Cov}=0$, or computing $\mathbb{E}[XY]$ as $\mathbb{E} X\mathbb{E} Y$ before checking independence.",
      r"$\mathrm{Var}(X+Y)$ if $\mathrm{Var} X=4$, $\mathrm{Var} Y=9$, $\mathrm{Cov}(X,Y)=2$.",
      r"$4+9+4=17$.",
      r"Indicators $I_A,I_B$. $\mathrm{Cov}(I_A,I_B)$.",
      r"$P(A\cap B)-P(A)P(B)$.")
    a(835, r"Correlation $\rho(X,Y)=\mathrm{Cov}(X,Y)/(\sigma_X\sigma_Y)$ when $\sigma_X\sigma_Y>0$. Cauchy–Schwarz: $|\rho|\le 1$, with $|\rho|=1$ iff $Y=aX+b$ a.s. with $a\neq 0$. $\rho$ is invariant under positive scaling and shifts.",
      r"$\mathrm{Cov}(X,Y)=6$, $\sigma_X=3$, $\sigma_Y=4$. $\rho$.",
      r"$6/12=1/2$.",
      r"If $Y=-2X+7$ (not constant), $\rho(X,Y)$.",
      r"$-1$.",
      r"Allowing $|\rho|>1$ from a covariance computation error, or thinking $\rho=0$ implies independence.",
      r"$\rho(3X+1,2Y-4)$ if $\rho(X,Y)=0.4$ and $3,2>0$.",
      r"$0.4$.",
      r"$\mathrm{Var} X=9$, $\mathrm{Var} Y=16$, $\rho=0.5$. $\mathrm{Cov}(X,Y)$.",
      r"$0.5\cdot 3\cdot 4=6$.")

    # T continuous RVs 836-842
    a(836, r"A continuous random variable (absolutely continuous) has a PDF $f_X\ge 0$ with $\int_{-\infty}^{\infty}f_X(x)\,dx=1$. Then $P(X\in A)=\int_A f_X$, and $P(X=x)=0$ for every singleton. Do not evaluate $f_X(x)$ as a probability.",
      r"$f(x)=c x$ on $(0,4)$, $0$ else. Find $c$ and $P(X\le 2)$.",
      r"$\int_0^4 c x\,dx=8c=1$, $c=1/8$. $P(X\le 2)=\int_0^2 x/8\,dx=1/4$.",
      r"If $f(2)=3$, is $P(X=2)=3$?",
      r"No: $P(X=2)=0$. The value $3$ is a density, not a mass.",
      r"Treating $f(x)$ as $P(X=x)$, or forgetting to check $\int f=1$.",
      r"$f(x)=e^{-x}$ for $x>0$. Is this a PDF?",
      r"Yes: $\int_0^\infty e^{-x}\,dx=1$ (standard exponential rate $1$).",
      r"$P(1<X<1)$ for a continuous $X$.",
      r"$0$.")
    a(837, r"For a continuous $X$ with PDF $f$, the CDF is $F(x)=\int_{-\infty}^x f(t)\,dt$, absolutely continuous, and $F'=f$ a.e. Then $P(a\le X\le b)=F(b)-F(a)$ (endpoints do not matter). Inverse: $f=F'$ where $F$ is $C^1$.",
      r"$f(x)=1/3$ on $[2,5]$. $F(4)$ and $F(1)$.",
      r"$F(4)=\int_2^4\frac13\,dx=2/3$. $F(1)=0$.",
      r"How is a PDF recovered from a CDF?",
      r"Differentiate: $f=F'$ at continuity points of $f$.",
      r"Using $P(a\le X\le b)=F(b)-F(a)$ for a discrete $X$ without care at atoms (need $F(b)-F(a-)$ etc.), or integrating $F$ instead of $f$.",
      r"$F(x)=0$ for $x<0$, $1-e^{-2x}$ for $x\ge 0$. PDF on $(0,\infty)$?",
      r"$f(x)=2e^{-2x}$.",
      r"$P(X>x)$ for continuous $X$.",
      r"$1-F(x)$.")
    a(838, r"If $X$ has PDF $f$, $\mathbb{E}[X]=\int_{-\infty}^{\infty} x f(x)\,dx$ when $\int|x|f<\infty$. LOTUS: $\mathbb{E}[g(X)]=\int g(x)f(x)\,dx$. For nonnegative continuous $X$, also $\mathbb{E}[X]=\int_0^\infty (1-F(x))\,dx$.",
      r"$f(x)=1/6$ on $[0,6]$. $\mathbb{E}[X]$.",
      r"Midpoint $3$, or $\int_0^6 x/6\,dx=3$.",
      r"$f(x)=2x$ on $[0,1]$. $\mathbb{E}[X]$ and $\mathbb{E}[X^2]$.",
      r"$\int_0^1 2x^2\,dx=2/3$; $\int_0^1 2x^3\,dx=1/2$.",
      r"Writing $\mathbb{E}[X]=\int F(x)\,dx$, or using $\sum x p(x)$ on a PDF.",
      r"Nonnegative $X$ with $F(x)=1-1/(1+x)$ for $x\ge 0$. $\mathbb{E}[X]$ via tail.",
      r"$\int_0^\infty \frac{1}{1+x}\,dx=\infty$ (no finite mean).",
      r"$\mathbb{E}[3X+2]$ if $\mathbb{E}[X]=4$.",
      r"$14$.")
    a(839, r"For a PDF $f$, $\mathrm{Var}(X)=\int(x-\mu)^2 f(x)\,dx=\mathbb{E}[X^2]-\mu^2$ with $\mathbb{E}[X^2]=\int x^2 f(x)\,dx$. Same algebraic identities as in the discrete case.",
      r"$f(x)=1$ on $[0,1]$. Variance of $U\sim\mathrm{Unif}(0,1)$.",
      r"$\mathbb{E}[U]=1/2$, $\mathbb{E}[U^2]=\int_0^1 x^2\,dx=1/3$, $\mathrm{Var}=1/3-1/4=1/12$.",
      r"$f(x)=e^{-x}$ on $(0,\infty)$. $\mathbb{E}[X^2]$ and $\mathrm{Var}$.",
      r"$\mathbb{E}[X]=1$, $\mathbb{E}[X^2]=\int_0^\infty x^2 e^{-x}\,dx=2$, $\mathrm{Var}=1$.",
      r"Computing $\int x^2 f-\mu$ without squaring $\mu$, or using $(b-a)/12$ instead of $(b-a)^2/12$ for a uniform.",
      r"$X$ has $\mathbb{E}[X]=5$, $\mathbb{E}[X^2]=29$. $\mathrm{Var}$.",
      r"$4$.",
      r"If $Y=2X+1$ and $\mathrm{Var} X=3$, $\mathrm{Var} Y$.",
      r"$12$.")
    a(840, r"Continuous uniform $X\sim\mathrm{Unif}(a,b)$ has PDF $f=1/(b-a)$ on $(a,b)$. Then $\mathbb{E}[X]=(a+b)/2$, $\mathrm{Var}(X)=(b-a)^2/12$, CDF $F(x)=(x-a)/(b-a)$ on $[a,b]$. Probabilities are length ratios.",
      r"$X\sim\mathrm{Unif}(2,8)$. $P(X\le 5)$, mean, variance.",
      r"$P=(5-2)/6=1/2$. Mean $5$. Variance $36/12=3$.",
      r"PDF of $\mathrm{Unif}(-1,3)$.",
      r"$1/4$ on $(-1,3)$.",
      r"Using $\mathrm{Var}=(b-a)/12$, or treating $\mathrm{Unif}(a,b)$ as discrete on the integers from $a$ to $b$.",
      r"$P(3<X<7)$ for $X\sim\mathrm{Unif}(0,10)$.",
      r"$2/5$.",
      r"$X\sim\mathrm{Unif}(0,1)$, $P(X^2\le 1/4)$.",
      r"$P(X\le 1/2)=1/2$ (since $X\ge 0$).")
    a(841, r"Exponential law with rate $\lambda>0$: PDF $\lambda e^{-\lambda x}$ for $x>0$, CDF $1-e^{-\lambda x}$, mean $1/\lambda$, variance $1/\lambda^2$. Memoryless: $P(X>s+t\mid X>s)=P(X>t)$. The minimum of independent Exp$(\lambda_i)$ is Exp$(\sum\lambda_i)$.",
      r"$X\sim\mathrm{Exp}(\lambda=3)$. $P(X>2)$ and $\mathbb{E}[X]$.",
      r"$e^{-6}$; mean $1/3$.",
      r"Memoryless: $P(X>5\mid X>2)$ for Exp($1$).",
      r"$P(X>3)=e^{-3}$.",
      r"Using PDF $e^{-\lambda x}$ without the factor $\lambda$, so it is not a density unless $\lambda=1$. Mixing rate and mean parametrizations: some texts use mean $\theta=1/\lambda$.",
      r"CDF of $\mathrm{Exp}(2)$ at $x=1$.",
      r"$1-e^{-2}$.",
      r"Independent $X\sim\mathrm{Exp}(1)$, $Y\sim\mathrm{Exp}(4)$. Law of $\min(X,Y)$.",
      r"$\mathrm{Exp}(5)$.")
    a(842, r"Normal $X\sim N(\mu,\sigma^2)$ has PDF $\frac{1}{\sigma\sqrt{2\pi}}\exp\bigl(-(x-\mu)^2/(2\sigma^2)\bigr)$. $Z=(X-\mu)/\sigma\sim N(0,1)$. Linear images: $aX+b\sim N(a\mu+b,a^2\sigma^2)$. The family is closed under independent sums.",
      r"$X\sim N(10,16)$. $P(X\le 14)$ in terms of $\Phi$.",
      r"$P\bigl(Z\le (14-10)/4\bigr)=\Phi(1)$.",
      r"$X\sim N(0,1)$. $P(|X|<2)$ is about",
      r"$0.95$ (more precisely $2\Phi(2)-1\approx 0.954$).",
      r"Standardizing with $\sigma^2$ in the denominator instead of $\sigma$, or using $N(\mu,\sigma)$ to mean variance $\sigma$ rather than $\sigma^2$.",
      r"$X\sim N(2,9)$. Law of $4X-1$.",
      r"$N(7,144)$.",
      r"Independent $X\sim N(1,4)$, $Y\sim N(3,5)$. Law of $X+Y$.",
      r"$N(4,9)$.")

    # T joint distributions 843-848
    a(843, r"A discrete pair has joint PMF $p(x,y)=P(X=x,Y=y)$, with $\sum_{x,y}p=1$. A continuous pair has joint PDF $f(x,y)\ge 0$, $\iint f=1$, and $P((X,Y)\in A)=\iint_A f$. Independence of coordinates is a special joint, not the default.",
      r"Joint PMF $p(x,y)=c$ on $\{1,2,3\}\times\{1,2\}$. Find $c$ and $P(X=Y)$.",
      r"$6c=1$, $c=1/6$. $P(X=Y)=p(1,1)+p(2,2)=1/3$.",
      r"Joint PDF $f(x,y)=8xy$ on $0<x<y<1$? First check the region: actually take $f=2$ on the triangle $x>0,y>0,x+y<1$. Is that a PDF?",
      r"Area $1/2$, $\iint 2=1$, yes.",
      r"Factoring a joint as $f_X(x)f_Y(y)$ without justification, or integrating a joint PMF as if it were continuous.",
      r"$p(0,0)=0.1$, $p(0,1)=0.2$, $p(1,0)=0.3$, $p(1,1)=0.4$. Valid PMF? $P(X=1)$.",
      r"Sums to $1$, yes. $P(X=1)=0.7$.",
      r"Support of a joint PDF is a disk. $P(Y>X)$ is generally",
      r"an integral over the half-disk $y>x$, not automatically $1/2$ unless the joint is symmetric.")
    a(844, r"Marginal PMF: $p_X(x)=\sum_y p_{X,Y}(x,y)$. Marginal PDF: $f_X(x)=\int f_{X,Y}(x,y)\,dy$. You cannot read a marginal off a single slice of the joint without integrating/summing the other variable.",
      r"Joint $p(x,y)$ on $\{0,1\}^2$: $p(0,0)=0.1$, $p(0,1)=0.2$, $p(1,0)=0.3$, $p(1,1)=0.4$. Marginal of $X$.",
      r"$p_X(0)=0.3$, $p_X(1)=0.7$.",
      r"$f(x,y)=e^{-(x+y)}$ for $x>0,y>0$. $f_X(x)$.",
      r"$e^{-x}\int_0^\infty e^{-y}\,dy=e^{-x}$ (independent Exp($1$) pair).",
      r"Reporting $f(x,y_0)$ for a fixed $y_0$ as the marginal of $X$.",
      r"$f(x,y)=1$ on the square $[0,1]^2$. Marginal of $X$.",
      r"$f_X(x)=1$ on $[0,1]$.",
      r"From the $2\times 2$ table above, $p_Y(1)$.",
      r"$0.2+0.4=0.6$.")
    a(845, r"Discrete conditional: $p_{X\mid Y}(x\mid y)=p(x,y)/p_Y(y)$ for $p_Y(y)>0$. Continuous: $f_{X\mid Y}(x\mid y)=f(x,y)/f_Y(y)$. Each conditional is a probability distribution in the remaining variable.",
      r"From $p(0,0)=0.1$, $p(0,1)=0.2$, $p(1,0)=0.3$, $p(1,1)=0.4$, find $P(X=1\mid Y=0)$.",
      r"$p_Y(0)=0.4$, so $0.3/0.4=3/4$.",
      r"$f(x,y)=2$ on $0<x<y<1$. $f_Y(y)$ and $f_{X\mid Y}(x\mid y)$.",
      r"$f_Y(y)=\int_0^y 2\,dx=2y$ on $(0,1)$. Then $f_{X\mid Y}=2/(2y)=1/y$ on $0<x<y$ (uniform on $(0,y)$).",
      r"Using $p(x,y)/p_X(x)$ when the condition is $Y=y$ (that's $p_{Y\mid X}$).",
      r"$P(Y=1\mid X=1)$ in the table $0.1,0.2,0.3,0.4$.",
      r"$0.4/0.7=4/7$.",
      r"If $X,Y$ independent, $f_{X\mid Y}(x\mid y)$ equals",
      r"$f_X(x)$.")
    a(846, r"Random variables $X,Y$ are independent if $p(x,y)=p_X(x)p_Y(y)$ for all $x,y$ (discrete) or $f(x,y)=f_X(x)f_Y(y)$ a.e. (continuous), equivalently $F_{X,Y}(x,y)=F_X(x)F_Y(y)$. Then $\mathbb{E}[g(X)h(Y)]=\mathbb{E}[g(X)]\mathbb{E}[h(Y)]$ for suitable $g,h$, and $\mathrm{Cov}(X,Y)=0$.",
      r"Table $p(0,0)=0.08$, $p(0,1)=0.12$, $p(1,0)=0.32$, $p(1,1)=0.48$. Independent?",
      r"$p_X(0)=0.2$, $p_Y(0)=0.4$, product $0.08$ matches; $0.2\cdot 0.6=0.12$; $0.8\cdot 0.4=0.32$; $0.8\cdot 0.6=0.48$. Yes.",
      r"Uniform on the triangle $x>0,y>0,x+y<1$. Independent?",
      r"No: the support is not a product set.",
      r"Checking independence by $\mathrm{Cov}=0$ only, or multiplying the original joint by a constant and calling it independent.",
      r"$f(x,y)=6e^{-2x-3y}$ for $x>0,y>0$. Independent? Marginals?",
      r"Yes: $2e^{-2x}$ and $3e^{-3y}$ (the $6=2\cdot 3$).",
      r"Independent $X,Y$. $P(X\le 1,Y\le 2)$.",
      r"$F_X(1)F_Y(2)$.")
    a(847, r"For a random vector $\mathbf{X}=(X_1,\ldots,X_d)$, the covariance matrix $\Sigma$ has $\Sigma_{ij}=\mathrm{Cov}(X_i,X_j)$. $\Sigma$ is symmetric and positive semidefinite. Diagonal entries are variances. For $A$ a matrix, $\mathrm{Cov}(A\mathbf{X})=A\Sigma A^T$. Multivariate normal is determined by mean and $\Sigma$.",
      r"$\mathrm{Var} X=4$, $\mathrm{Var} Y=9$, $\mathrm{Cov}(X,Y)=2$. Write $\Sigma$.",
      r"$\begin{pmatrix}4&2\\2&9\end{pmatrix}$.",
      r"Is $\begin{pmatrix}1&2\\2&1\end{pmatrix}$ a possible covariance matrix?",
      r"No: eigenvalues $3$ and $-1$; not PSD. Also $|\rho|=2>1$.",
      r"Writing a covariance matrix that is not symmetric, or putting correlation (not covariance) off-diagonal while putting variance on-diagonal.",
      r"Independent coordinates, $\mathrm{Var} X_i=\sigma_i^2$. $\Sigma$ is",
      r"diagonal $\mathrm{diag}(\sigma_1^2,\ldots,\sigma_d^2)$.",
      r"$\mathrm{Var}(X+Y)$ from $\Sigma=\bigl(\begin{smallmatrix}4&2\\2&9\end{smallmatrix}\bigr)$.",
      r"$\mathbf{1}^T\Sigma\mathbf{1}=4+9+4=17$.")
    a(848, r"Conditional expectation $\mathbb{E}[X\mid Y=y]$ is the mean of the conditional law of $X$ given $Y=y$. As a random variable, $\mathbb{E}[X\mid Y]$ is a function of $Y$. Tower property: $\mathbb{E}\bigl[\mathbb{E}[X\mid Y]\bigr]=\mathbb{E}[X]$. If independent, $\mathbb{E}[X\mid Y]=\mathbb{E}[X]$.",
      r"From $P(X=1\mid Y=0)=3/4$, $P(X=1\mid Y=1)=4/7$ with $X\in\{0,1\}$, find $\mathbb{E}[X\mid Y=0]$.",
      r"$3/4$.",
      r"$Y\sim\mathrm{Unif}(0,1)$ and $X\mid Y=y\sim\mathrm{Unif}(0,y)$. $\mathbb{E}[X\mid Y]$ and $\mathbb{E}[X]$.",
      r"$\mathbb{E}[X\mid Y]=Y/2$. Tower: $\mathbb{E}[X]=\mathbb{E}[Y/2]=1/4$.",
      r"Treating $\mathbb{E}[X\mid Y]$ as a number rather than a random variable, or replacing it by $\mathbb{E}[X]/\mathbb{E}[Y]$.",
      r"Independent $X,Y$, $\mathbb{E}[X]=5$. $\mathbb{E}[X\mid Y=2]$.",
      r"$5$.",
      r"Tower check: $\mathbb{E}[\mathbb{E}[X\mid Y]]$ always equals",
      r"$\mathbb{E}[X]$, when the expectations exist.")

    # T common distributions 849-858
    a(849, r"Bernoulli($p$): $X\in\{0,1\}$, $P(X=1)=p$, $P(X=0)=1-p$. Mean $p$, variance $p(1-p)$, MGF $1-p+pe^t$. It is the indicator of a success. $n$ i.i.d. copies sum to Binomial($n,p$).",
      r"$X\sim\mathrm{Bern}(0.3)$. Mean, variance, $P(X=0)$.",
      r"$0.3$, $0.21$, $0.7$.",
      r"MGF of $\mathrm{Bern}(p)$ at $t=0$.",
      r"$1$, as for every MGF.",
      r"Using variance $p$, or calling a $\mathrm{Bin}(n,p)$ variable Bernoulli.",
      r"$\mathbb{E}[X^2]$ for $\mathrm{Bern}(p)$.",
      r"$p$, because $X^2=X$.",
      r"$3$ i.i.d. $\mathrm{Bern}(1/2)$. $P(\text{all }1)$.",
      r"$1/8$.")
    a(850, r"Binomial($n,p$): $X=\#$ of successes in $n$ independent Bernoulli($p$) trials. PMF $\binom{n}{k}p^k(1-p)^{n-k}$, mean $np$, variance $np(1-p)$. Additive: $\mathrm{Bin}(n,p)+\mathrm{Bin}(m,p)$ independent is $\mathrm{Bin}(n+m,p)$.",
      r"$X\sim\mathrm{Bin}(8,1/3)$. $P(X=2)$ and $\mathbb{E}[X]$.",
      r"$\binom{8}{2}(1/3)^2(2/3)^6=28\cdot\frac{1}{9}\cdot\frac{64}{729}=\frac{1792}{6561}$. Mean $8/3$.",
      r"Fair coins, $n=10$. $P(\text{exactly }10\text{ heads})$.",
      r"$2^{-10}=1/1024$.",
      r"Using $\binom{n}{k}p^k$ without the $(1-p)^{n-k}$ factor, or variance $np$.",
      r"$\mathrm{Var}$ of $\mathrm{Bin}(20,0.4)$.",
      r"$20\cdot 0.4\cdot 0.6=4.8$.",
      r"Independent $X\sim\mathrm{Bin}(5,0.3)$, $Y\sim\mathrm{Bin}(7,0.3)$. Law of $X+Y$.",
      r"$\mathrm{Bin}(12,0.3)$.")
    a(851, r"Geometric($p$), trials-until-first-success convention: $P(X=k)=(1-p)^{k-1}p$ for $k=1,2,\ldots$. Mean $1/p$, variance $(1-p)/p^2$. Memoryless: $P(X>s+t\mid X>s)=P(X>t)$ for integers. (The failures-before-success version is $X-1$ and has mean $(1-p)/p$.)",
      r"$p=1/5$. $P(X=3)$ and $\mathbb{E}[X]$.",
      r"$(4/5)^2(1/5)=16/125$; mean $5$.",
      r"$P(X>4)$ for Geometric($1/2$) (trials).",
      r"$(1/2)^4=1/16$ (first four trials all fail).",
      r"Mixing the two geometric conventions (mean $1/p$ vs $(1-p)/p$), or starting $k$ at $0$ while using $(1-p)^{k-1}p$.",
      r"Variance of Geometric($1/3$) (trials).",
      r"$(2/3)/(1/9)=6$.",
      r"Memoryless: $P(X>10\mid X>7)$ for Geometric($p$).",
      r"$P(X>3)=(1-p)^3$.")
    a(852, r"Negative binomial, trials until $r$ successes: $P(X=k)=\binom{k-1}{r-1}p^r(1-p)^{k-r}$ for $k=r,r+1,\ldots$. Mean $r/p$, variance $r(1-p)/p^2$. It is the sum of $r$ i.i.d. Geometric($p$) trial-counts.",
      r"$r=3$, $p=1/2$. $P(X=5)$ and $\mathbb{E}[X]$.",
      r"$\binom{4}{2}(1/2)^3(1/2)^{2}=\binom{4}{2}/32=6/32=3/16$. Mean $6$.",
      r"Mean of NB($r=4$, $p=1/5$).",
      r"$20$.",
      r"Using $\binom{k}{r}$ instead of $\binom{k-1}{r-1}$, or starting $k$ at $0$.",
      r"Variance of NB($r=2$, $p=1/4$).",
      r"$2\cdot(3/4)/(1/16)=24$.",
      r"Why is NB($1,p$) geometric?",
      r"One success: $\binom{k-1}{0}p(1-p)^{k-1}$.")
    a(853, r"Hypergeometric: population $N$ with $K$ marked items, draw $n$ without replacement. $P(X=k)=\dfrac{\binom{K}{k}\binom{N-K}{n-k}}{\binom{N}{n}}$. Mean $nK/N$. Variance $n\frac{K}{N}\bigl(1-\frac{K}{N}\bigr)\frac{N-n}{N-1}$ (finite-population correction).",
      r"$N=20$, $K=7$ defective, $n=4$. $P(X=2)$.",
      r"$\binom{7}{2}\binom{13}{2}/\binom{20}{4}=21\cdot 78/4845=1638/4845=546/1615$.",
      r"Mean number of defectives in that draw.",
      r"$4\cdot 7/20=1.4$.",
      r"Using Binomial $p=K/N$ as if draws were independent (reasonable only if $n\ll N$), or putting $\binom{N}{k}$ in the denominator.",
      r"Aces in a $5$-card hand: $N=52$, $K=4$, $n=5$. $P(X=2)$.",
      r"$\binom{4}{2}\binom{48}{3}/\binom{52}{5}$.",
      r"If $n=1$, hypergeometric becomes",
      r"Bernoulli($K/N$).")
    a(854, r"Poisson($\lambda$): $P(X=k)=e^{-\lambda}\lambda^k/k!$ for $k=0,1,\ldots$. Mean $\lambda$, variance $\lambda$, MGF $\exp\bigl(\lambda(e^t-1)\bigr)$. Approximation to $\mathrm{Bin}(n,p)$ when $n$ is large, $p$ small, $\lambda=np$ moderate. Sum of independent Poissons is Poisson with added rates.",
      r"$\lambda=3$. $P(X=2)$ and $\mathbb{E}[X]$.",
      r"$e^{-3}\cdot 9/2=\frac92 e^{-3}$; mean $3$.",
      r"Independent $X\sim\mathrm{Pois}(2)$, $Y\sim\mathrm{Pois}(5)$. Law of $X+Y$.",
      r"$\mathrm{Pois}(7)$.",
      r"Using $e^{-\lambda}\lambda^k$ without $k!$, or variance $\lambda^2$. Also Poisson as a model for a bounded $n$-trial count without stating the rare-event regime.",
      r"$P(X=0)$ for $\mathrm{Pois}(1.5)$.",
      r"$e^{-1.5}$.",
      r"$\mathrm{Bin}(100,0.03)$ is close to which Poisson?",
      r"$\mathrm{Pois}(3)$.")
    a(855, r"Uniform family: discrete $\mathrm{Unif}\{1,\ldots,n\}$ has PMF $1/n$, mean $(n+1)/2$, variance $(n^2-1)/12$. Continuous $\mathrm{Unif}(a,b)$ as in M-840. A uniform law is the maximum-entropy distribution on a bounded interval (continuous) / finite set (discrete) with no further constraints.",
      r"Discrete uniform on $\{1,2,\ldots,9\}$. Mean and $P(X\ge 7)$.",
      r"Mean $5$; $P=3/9=1/3$.",
      r"Variance of $\mathrm{Unif}\{1,\ldots,6\}$ (a fair die).",
      r"$(36-1)/12=35/12$.",
      r"Using continuous variance $(b-a)^2/12$ on a die, or mean $n/2$ for $\{1,\ldots,n\}$.",
      r"$X\sim\mathrm{Unif}\{0,1,2,3,4\}$. $\mathbb{E}[X]$ and $\mathbb{E}[X^2]$.",
      r"Mean $2$; $\mathbb{E}[X^2]=(0+1+4+9+16)/5=6$, $\mathrm{Var}=6-4=2$.",
      r"Continuous $\mathrm{Unif}(3,9)$ vs discrete $\mathrm{Unif}\{3,\ldots,9\}$. Means?",
      r"Both $6$; variances $3$ vs $(49-1)/12=4$.")
    a(856, r"Exponential recap (rate $\lambda$): lack of memory characterizes the continuous nonnegative laws that are exponential. $cX\sim\mathrm{Exp}(\lambda/c)$ for $c>0$. The sum of $k$ i.i.d. Exp($\lambda$) is Gamma($k,\lambda$) (Erlang). Hazard rate is the constant $\lambda$.",
      r"$X\sim\mathrm{Exp}(1/4)$ (rate $1/4$). Mean and $P(X>8\mid X>4)$.",
      r"Mean $4$; memoryless $P(X>4)=e^{-1}$.",
      r"If waiting times are i.i.d. Exp($2$), time until the $3$rd event is",
      r"Erlang/Gamma shape $3$ rate $2$, mean $3/2$.",
      r"Scaling $X$ by $2$ and leaving the rate unchanged, or using $P(X>x)=e^{-x/\lambda}$ while $\lambda$ was already a rate.",
      r"PDF of Exp(rate $5$).",
      r"$5e^{-5x}$ for $x>0$.",
      r"$P(X>x+y\mid X>x)$ vs $P(X>y)$ for exponential.",
      r"Equal, for all $x,y>0$.")
    a(857, r"Normal recap: $68\%$ / $95\%$ / $99.7\%$ of mass within $1,2,3$ SDs of the mean for $N(\mu,\sigma^2)$. Standard tables give $\Phi(z)=P(Z\le z)$. $X\sim N(\mu,\sigma^2)$ iff $Z=(X-\mu)/\sigma\sim N(0,1)$. Affine transforms and independent sums stay normal.",
      r"$X\sim N(50,25)$. Approximate $P(40\le X\le 60)$ by the empirical rule.",
      r"Within $2\sigma=10$, about $0.95$.",
      r"$P(Z>1.5)$ in terms of $\Phi$.",
      r"$1-\Phi(1.5)$.",
      r"Using $P(|X-\mu|<\sigma)\approx 0.95$ (that is $2\sigma$), or forgetting to take square root of a stated variance.",
      r"$X\sim N(100,36)$. $P(X>118)$ as $\Phi$.",
      r"$P(Z>3)=1-\Phi(3)\approx 0.00135$.",
      r"Independent $N(0,1)$ copies $Z_1,Z_2$. Law of $Z_1+Z_2$.",
      r"$N(0,2)$.")
    a(858, r"Gamma($(\alpha,\lambda)$) (shape-rate): PDF $\dfrac{\lambda^\alpha}{\Gamma(\alpha)}x^{\alpha-1}e^{-\lambda x}$ for $x>0$. Mean $\alpha/\lambda$, variance $\alpha/\lambda^2$. Gamma($1,\lambda$)=Exp($\lambda$). Beta($\alpha,\beta$): PDF $\dfrac{\Gamma(\alpha+\beta)}{\Gamma(\alpha)\Gamma(\beta)}x^{\alpha-1}(1-x)^{\beta-1}$ on $(0,1)$, mean $\alpha/(\alpha+\beta)$. Beta($1,1$)=Unif($0,1$).",
      r"Gamma shape $4$, rate $2$. Mean and variance.",
      r"Mean $2$, variance $1$.",
      r"Beta($2,5$). Mean.",
      r"$2/7$.",
      r"Confusing shape-rate with shape-scale (scale $\theta=1/\lambda$ makes mean $\alpha\theta$). Using Beta on $(0,\infty)$.",
      r"Gamma($n$, rate $\lambda$) for integer $n$ is the law of",
      r"the sum of $n$ i.i.d. Exp($\lambda$).",
      r"Mode of Beta($3,2$) is at $x=$? (for $\alpha,\beta>1$, mode $(\alpha-1)/(\alpha+\beta-2)$).",
      r"$(2)/(3)=2/3$.")

    # T limit theorems 859-863
    a(859, r"Weak law of large numbers: if $X_i$ are i.i.d. with finite mean $\mu$, then $\bar X_n=\frac1n\sum_{i=1}^n X_i\to\mu$ in probability: $P(|\bar X_n-\mu|>\varepsilon)\to 0$ for every $\varepsilon>0$. Chebyshev plus $\mathrm{Var}(\bar X_n)=\sigma^2/n\to 0$ proves it when $\sigma^2<\infty$. This is typical-value concentration, not a distributional shape.",
      r"I.i.d. with mean $4$, variance $9$, $n=100$. Chebyshev bound on $P(|\bar X-4|\ge 1)$.",
      r"$\mathrm{Var}(\bar X)=0.09$, so $P\le 0.09/1^2=0.09$.",
      r"Fair-coin sample proportion $\hat p$ with $n=400$. WLLN says $\hat p$ is near",
      r"$1/2$.",
      r"Claiming $\bar X_n=\mu$ for finite $n$, or confusing the WLLN with the CLT (the WLLN does not produce a normal limit by itself).",
      r"Does the WLLN need a finite variance?",
      r"The classical Chebyshev proof does; the WLLN itself needs only a finite mean.",
      r"I.i.d. Exp($1$). $\bar X_n$ converges in probability to",
      r"$1$.")
    a(860, r"Central limit theorem: i.i.d. $X_i$ with mean $\mu$ and finite positive variance $\sigma^2$, then $\sqrt{n}\,(\bar X_n-\mu)/\sigma\to N(0,1)$ in distribution. Equivalently $S_n=\sum X_i$ is approximately $N(n\mu,n\sigma^2)$ for large $n$. The CLT is about fluctuations of order $1/\sqrt{n}$.",
      r"I.i.d. with $\mu=2$, $\sigma=3$, $n=36$. Approximate $P(\bar X>2.5)$.",
      r"$\bar X\approx N(2,9/36)=N(2,1/4)$. $P(\bar X>2.5)=P\bigl(Z>(2.5-2)/(1/2)\bigr)=P(Z>1)=1-\Phi(1)$.",
      r"Sum of $100$ i.i.d. with mean $0$ variance $1$ is approximately",
      r"$N(0,100)$, so $\mathrm{SD}=10$.",
      r"Using $\sigma$ instead of $\sigma/\sqrt{n}$ as the SD of $\bar X$, or applying the CLT to $n=2$ with a highly skewed law as if it were exact.",
      r"Standardize $S_{25}$ if $\mu=4$, $\sigma=2$.",
      r"$(S_{25}-100)/10$ is approx $N(0,1)$.",
      r"If $\sigma=0$, does the CLT apply?",
      r"No: nondegenerate variance is required. The average is already exactly $\mu$.")
    a(861, r"Normal approximation: $\mathrm{Bin}(n,p)\approx N\bigl(np,np(1-p)\bigr)$ when $n$ is large and $p$ is not too near $0$ or $1$ (rule of thumb: $np$ and $n(1-p)$ at least about $5$ or $10$). Poisson($\lambda$) $\approx N(\lambda,\lambda)$ for large $\lambda$. Always convert to $Z$ with the matching mean and variance.",
      r"$X\sim\mathrm{Bin}(100,1/2)$. Approximate $P(X\le 40)$ without continuity correction.",
      r"$X\approx N(50,25)$, $P\bigl(Z\le(40-50)/5\bigr)=\Phi(-2)$.",
      r"$\mathrm{Pois}(64)$ approx $P(X\ge 80)$.",
      r"$N(64,64)$, $P\bigl(Z\ge(80-64)/8\bigr)=P(Z\ge 2)=1-\Phi(2)$.",
      r"Using variance $np$ for a binomial, or approximating $\mathrm{Bin}(n,p)$ by $N(n,p)$.",
      r"$X\sim\mathrm{Bin}(200,0.3)$. Mean and SD for the normal approx.",
      r"Mean $60$, SD $\sqrt{42}=\sqrt{200\cdot 0.3\cdot 0.7}$.",
      r"Why is $\mathrm{Bin}(12,0.04)$ a poor normal approximation?",
      r"$np=0.48<5$; the law is right-skewed and nearly Poisson.")
    a(862, r"Continuity correction: when approximating a lattice (integer-valued) law by a normal $Y$, replace $P(X\le k)$ by $P(Y\le k+1/2)$ and $P(X\ge k)$ by $P(Y\ge k-1/2)$, because the integer $k$ occupies $[k-1/2,k+1/2]$. It usually improves binomial and Poisson approximations.",
      r"$X\sim\mathrm{Bin}(100,1/2)$. Approximate $P(X\ge 55)$ with continuity correction.",
      r"$Y\sim N(50,25)$, $P(Y\ge 54.5)=P\bigl(Z\ge(54.5-50)/5\bigr)=P(Z\ge 0.9)=1-\Phi(0.9)$.",
      r"$P(X\le 40)$ with correction, same $X$.",
      r"$P(Y\le 40.5)=P(Z\le(40.5-50)/5)=P(Z\le -1.9)$.",
      r"Adding $1/2$ in the wrong direction (using $k-1/2$ for a $\le k$ probability), or applying a continuity correction to an already continuous $X$.",
      r"$P(X=50)$ for $\mathrm{Bin}(100,1/2)$ via a normal $Y$.",
      r"$P(49.5\le Y\le 50.5)=P(|Z|\le 0.1)$.",
      r"Poisson($16$), $P(X\le 10)$ with correction, $Y\sim N(16,16)$. $Z$-threshold?",
      r"$(10.5-16)/4=-1.375$.")
    a(863, r"Convergence in distribution (weak convergence): $X_n\Rightarrow X$ if $F_n(x)\to F(x)$ at all continuity points $x$ of $F$. Equivalent (bounded continuous $g$): $\mathbb{E}[g(X_n)]\to\mathbb{E}[g(X)]$. The CLT is $Z_n\Rightarrow N(0,1)$. Convergence in probability implies convergence in distribution; the converse needs a constant limit.",
      r"$X_n=X+1/n$ for a continuous $X$. Does $X_n\Rightarrow X$? In probability?",
      r"Yes and yes: $1/n\to 0$.",
      r"Independent copies $X_n$ of a nondegenerate $X$. Does $X_n\Rightarrow X$? In probability?",
      r"$X_n\Rightarrow X$ always (same law), but $X_n\not\to X$ in probability unless $X$ is a.s. constant.",
      r"Checking $F_n(x)\to F(x)$ at a jump of $F$ and declaring failure of weak convergence (the definition exempts jumps).",
      r"CLT statement as weak convergence: $\sqrt{n}(\bar X_n-\mu)/\sigma\Rightarrow$",
      r"$N(0,1)$.",
      r"If $X_n\Rightarrow c$ a constant, then also",
      r"$X_n\to c$ in probability.")

    # T generating/transform methods 864-868
    a(864, r"The moment-generating function of $X$ is $M_X(t)=\mathbb{E}[e^{tX}]$, defined on a neighborhood of $0$ (or at least at $0$, where $M(0)=1$). Discrete: $\sum e^{tx}p(x)$. Continuous: $\int e^{tx}f(x)\,dx$. Independent sum: $M_{X+Y}=M_X M_Y$. Bernoulli: $1-p+pe^t$. Poisson($\lambda$): $\exp(\lambda(e^t-1))$. $N(\mu,\sigma^2)$: $\exp(\mu t+\sigma^2 t^2/2)$. Exp($\lambda$): $\lambda/(\lambda-t)$ for $t<\lambda$.",
      r"$X\sim\mathrm{Bern}(1/3)$. Write $M_X(t)$ and $M_X(0)$.",
      r"$M(t)=\frac23+\frac13 e^t$. $M(0)=1$.",
      r"$X\sim\mathrm{Pois}(4)$. $M_X(t)$.",
      r"$\exp\bigl(4(e^t-1)\bigr)$.",
      r"Writing $M(t)=\mathbb{E}[t^X]$ (that is a probability-generating function, with $t$ replaced by $e^t$ to get an MGF), or multiplying MGFs without independence.",
      r"MGF of $N(0,1)$.",
      r"$e^{t^2/2}$.",
      r"Independent $X\sim\mathrm{Pois}(2)$, $Y\sim\mathrm{Pois}(3)$. MGF of $X+Y$, hence the law.",
      r"$\exp(5(e^t-1))$, so $\mathrm{Pois}(5)$.")
    a(865, r"If $M$ is finite in a neighborhood of $0$, then $\mathbb{E}[X^k]=M^{(k)}(0)$. In particular $\mathbb{E}[X]=M'(0)$ and $\mathbb{E}[X^2]=M''(0)$, so $\mathrm{Var}(X)=M''(0)-(M'(0))^2$. This recovers means and variances from a closed-form MGF.",
      r"$M(t)=\lambda/(\lambda-t)$ for $t<\lambda$ (exponential rate $\lambda$). Compute $M'(0)$ and $M''(0)$, hence mean and variance.",
      r"$M'(t)=\lambda/(\lambda-t)^2$, $M'(0)=1/\lambda$. $M''(t)=2\lambda/(\lambda-t)^3$, $M''(0)=2/\lambda^2$. $\mathrm{Var}=2/\lambda^2-1/\lambda^2=1/\lambda^2$.",
      r"$M(t)=1-p+pe^t$. $M'(0)$.",
      r"$p$.",
      r"Evaluating $M'(t)$ at $t=1$ instead of $0$, or using $M''(0)$ as the variance without subtracting $(M'(0))^2$.",
      r"$M(t)=\exp(\mu t+\sigma^2 t^2/2)$. $M'(0)$.",
      r"$\mu$ (product rule: $(\mu+\sigma^2 t)M(t)$, at $0$ is $\mu$).",
      r"$X\sim\mathrm{Pois}(\lambda)$, $M(t)=\exp(\lambda(e^t-1))$. Show $M'(0)=\lambda$.",
      r"$M'(t)=\lambda e^t M(t)$, so $M'(0)=\lambda$.")
    a(866, r"Uniqueness: if two random variables have MGFs that agree on an open interval about $0$, they have the same distribution. Practical use: identify a law by matching a computed MGF to a catalog (Poisson, normal, gamma, binomial). Existence of an MGF in a neighborhood is stronger than existence of all moments; some laws (lognormal) are not determined by their moments.",
      r"A r.v. has $M(t)=(0.7+0.3e^t)^{12}$. Name the law.",
      r"$\mathrm{Bin}(12,0.3)$, because that is $\bigl(1-p+pe^t\bigr)^n$.",
      r"$M(t)=\exp(5t+8t^2)$. Law?",
      r"$N(5,16)$ because $\exp(\mu t+\sigma^2 t^2/2)$ with $\sigma^2/2=8$.",
      r"Matching $M(t)$ at a single $t\neq 0$ and declaring the law unique, or assuming every distribution with finite moments has an MGF in a neighborhood of $0$.",
      r"$M(t)=(2/(2-t))^3$ for $t<2$. Law?",
      r"Gamma(shape $3$, rate $2$), sum of three Exp($2$).",
      r"Independent $X_i\sim N(\mu_i,\sigma_i^2)$. MGF of $\sum X_i$ shows the sum is",
      r"$N(\sum\mu_i,\sum\sigma_i^2)$.")
    a(867, r"Transforming one random variable: if $Y=g(X)$ with $g$ strictly monotone and $C^1$, the PDF is $f_Y(y)=f_X(x)\bigl/|g'(x)|\bigr|$ at $x=g^{-1}(y)$. Discrete: just push masses, $P(Y=y)=\sum_{g(x)=y}p_X(x)$. Linear $Y=aX+b$ with $a\neq 0$: $f_Y(y)=f_X((y-b)/a)/|a|$.",
      r"$X\sim\mathrm{Unif}(0,1)$, $Y=-2\ln X$. PDF of $Y$ on $(0,\infty)$.",
      r"$x=e^{-y/2}$, $dx/dy=-e^{-y/2}/2$, $f_Y(y)=1\cdot e^{-y/2}/2$, i.e. Gamma/Erlang: actually $\frac12 e^{-y/2}=\mathrm{Exp}(\text{rate }1/2)$.",
      r"$X\sim N(\mu,\sigma^2)$, $Y=aX+b$ ($a\neq 0$). Law of $Y$.",
      r"$N(a\mu+b,a^2\sigma^2)$.",
      r"Dropping the absolute value $|g'|$, or using $f_Y(y)=f_X(y) |g'(y)|$ with $g$ not inverted.",
      r"$X$ has PDF $2x$ on $(0,1)$, $Y=X^2$. For $y\in(0,1)$, $f_Y(y)$.",
      r"$x=\sqrt{y}$, $dy/dx=2x$, $f_Y(y)=2\sqrt{y}/(2\sqrt{y})=1$ on $(0,1)$: $Y\sim\mathrm{Unif}(0,1)$.",
      r"$X$ discrete, $P(X=-1)=P(X=1)=1/2$, $Y=X^2$. Law of $Y$.",
      r"$Y=1$ a.s.")
    a(868, r"Jacobian method: if $\mathbf{Y}=g(\mathbf{X})$ is a $C^1$ bijection between open sets in $\mathbb{R}^d$, $f_{\mathbf{Y}}(\mathbf{y})=f_{\mathbf{X}}(\mathbf{x})\,\bigl|\det D g^{-1}(\mathbf{y})\bigr|=f_{\mathbf{X}}(x)/|\det Dg(x)|$ at $x=g^{-1}(y)$. For two variables, $|\det|=\bigl|x_u y_v-x_v y_u\bigr|$ in $u,v$-coordinates. Check the image of the support.",
      r"$X,Y$ i.i.d. $N(0,1)$. $U=X+Y$, $V=X-Y$. Jacobian and joint PDF of $(U,V)$.",
      r"$X=(U+V)/2$, $Y=(U-V)/2$, $\det\partial(x,y)/\partial(u,v)=1/2$. Joint of $(X,Y)$ is $(2\pi)^{-1}e^{-(x^2+y^2)/2}$. Times $1/2$: $f_{U,V}(u,v)=(2\pi)^{-1}e^{-(u^2+v^2)/4}\cdot\frac12=\frac{1}{4\pi}e^{-(u^2+v^2)/4}$. So $U,V$ independent $N(0,2)$.",
      r"$U=X$, $V=X+Y$ with $X,Y$ independent Exp($1$). Support of $(U,V)$?",
      r"$v>u>0$.",
      r"Forgetting $|\det J|$, or transforming the PDF as if it were a mass function. Also inverting only one coordinate in a two-dimensional map.",
      r"Polar: $X=R\cos\Theta$, $Y=R\sin\Theta$. Area Jacobian.",
      r"$|\det|=r$, so $dx\,dy=r\,dr\,d\theta$.",
      r"If $g$ is two-to-one (e.g. $Y=X^2$ on $\mathbb{R}$), the Jacobian formula on one branch must be",
      r"summed over preimages: $f_Y(y)=\sum_{x:g(x)=y}f_X(x)/|g'(x)|$.")

    return F

